import assert from 'node:assert/strict';import {chromium} from 'playwright';import {PNG} from 'pngjs';import {mkdtemp,mkdir,rm,writeFile} from 'node:fs/promises';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {control} from './editor-controls.mjs';import {createCorrectionDemos} from '../../demos/create-correction-projects.mjs';import {startServer} from '../../daemon/bootstrap/server.mjs';import {envelope} from '../../protocol/src/protocol.ts';
const root=await mkdtemp(join(tmpdir(),'axiom-corrections-')),evidence=resolve('.axiom/browser-corrections-evidence');await mkdir(evidence,{recursive:true});let daemon,browser,page;const report={criteria:[],pageErrors:[],consoleErrors:[],httpErrors:[]};
const difference=(a,b,lightingOnly=false)=>{const A=PNG.sync.read(a),B=PNG.sync.read(b);let count=0;for(let i=0;i<A.data.length;i+=4)if((!lightingOnly||Math.floor(i/4/A.width)>400||i/4%A.width<200||i/4%A.width>760)&&[0,1,2].some(j=>Math.abs(A.data[i+j]-B.data[i+j])>4))count++;return count;};
try{
 const demos=await createCorrectionDemos(root);daemon=await startServer({projectRoot:root});const command=async(type,data={})=>{const response=await fetch(daemon.origin+'/v1/commands',{method:'POST',headers:{Origin:daemon.origin,Authorization:'Bearer '+daemon.token,'Content-Type':'application/json'},body:JSON.stringify(envelope('command',{type,data}))});const v=await response.json();if(v.kind==='error')throw Error(JSON.stringify(v));return v.payload.data;};
 browser=await chromium.launch({headless:process.env.AXIOM_HEADLESS==='true',channel:'chromium',args:['--no-sandbox','--enable-gpu','--enable-unsafe-webgpu','--enable-unsafe-swiftshader','--enable-features=Vulkan','--use-angle=vulkan','--use-vulkan=swiftshader','--use-webgpu-adapter=swiftshader','--disable-vulkan-surface','--disable-dev-shm-usage']});page=await browser.newPage({viewport:{width:1700,height:1100}});page.on('pageerror',e=>report.pageErrors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});page.on('response',r=>{if(r.status()>=400)report.httpErrors.push({status:r.status(),path:new URL(r.url()).pathname});});page.on('dialog',d=>d.accept());page.setDefaultTimeout(45000);await page.goto(daemon.editorUrl);
 const ready=()=>page.waitForFunction(()=>{try{return JSON.parse(document.querySelector('#frame-trace').textContent).kernel.renderer==='webgpu'&&!document.querySelector('#scene-add').disabled;}catch{return false;}});
 const open=async id=>{await (await control(page,'#project-list')).selectOption(id);await (await control(page,'#project-open')).click();await ready();await page.locator('#scene-tab').click();};const select=async name=>{await page.locator('#entities .entity').filter({hasText:name}).click();};const state=()=>command('scene.get');
 await open(demos[0].id);await select('Empty ·');assert.ok(await page.locator('#light-component').isHidden());assert.ok(await page.locator('#material-component').isHidden());assert.ok(await page.locator('#physics-component').isHidden());await page.locator('#component-choice').selectOption('Light');await page.locator('#component-add').click();await page.waitForFunction(()=>!document.querySelector('#light-component').hidden);await (await control(page,'#light-remove')).click();await page.waitForFunction(()=>document.querySelector('#light-component').hidden);await page.locator('#viewport').focus();await page.keyboard.press('Control+z');await page.waitForFunction(()=>!document.querySelector('#light-component').hidden);await page.locator('#scene-undo').click();await ready();report.criteria.push('empty Inspector, explicit component add/remove and Ctrl+Z through public commands');
 const assembly=page.locator('#entities .tree-row').filter({has:page.locator('.entity',{hasText:'Assembly ·'})});await assembly.locator('.tree-toggle').click();assert.equal(await page.locator('#entities .entity').filter({hasText:'3D cube'}).count(),0);await assembly.locator('.tree-toggle').click();await select('3D cube');await page.locator('#entities .entity').filter({hasText:'3D sphere'}).click({modifiers:['Control']});await page.waitForFunction(()=>document.querySelector('#selection-status').textContent.includes('2 entities'));assert.equal(await page.locator('#entity-fields').evaluate(n=>n.disabled),false);assert.equal(await page.locator('#entity-name').isDisabled(),true);const current=await state(),parent=current.project.scene.entities.find(e=>e.name.startsWith('Empty')).id;
 await page.locator('#entities .entity').filter({hasText:'3D cube'}).dragTo(page.locator('#entities .entity').filter({hasText:'Empty ·'}));await ready();assert.equal((await state()).project.scene.entities.filter(e=>e.parentId===parent).length,2);await page.locator('#viewport').focus();await page.keyboard.press('Control+z');await ready();assert.equal((await state()).project.scene.entities.filter(e=>e.parentId===parent).length,0);await page.keyboard.press('Control+y');await ready();assert.equal((await state()).project.scene.entities.filter(e=>e.parentId===parent).length,2);await page.locator('#entities .entity').filter({hasText:'3D cube'}).dragTo(page.locator('.scene-root-button'));await ready();assert.ok((await state()).project.scene.entities.filter(e=>['3D cube','3D sphere'].includes(e.name)).every(e=>!e.parentId));await page.locator('#scene-undo').click();await ready();await page.locator('#scene-undo').click();await ready();report.criteria.push('compact tree, Ctrl multi-selection, native group parenting/root drop, Ctrl+Z/Ctrl+Y');
 const cylinder=current.project.scene.entities.find(e=>e.name==='3D cylinder'),capsule=current.project.scene.entities.find(e=>e.name==='3D capsule');await select('3D cylinder');await page.locator('#entities .entity').filter({hasText:'3D pyramid'}).click({modifiers:['Shift']});assert.equal(await page.locator('#entities .entity.selected').count(),3);await select('3D cylinder');await page.locator('#entities .entity').filter({hasText:'3D capsule'}).click({modifiers:['Control']});
 const transformBefore=(await state()).project.scene;await page.locator('#position-0').fill('3');await page.locator('#entity-form button[type="submit"]').click();await ready();assert.ok((await state()).project.scene.entities.filter(e=>[cylinder.id,capsule.id].includes(e.id)).every(e=>e.transform.position[0]===3));await page.locator('#scene-undo').click();await ready();await page.locator('#rotation-2').fill('30');await page.locator('#entity-form button[type="submit"]').click();await ready();assert.ok((await state()).project.scene.entities.filter(e=>[cylinder.id,capsule.id].includes(e.id)).every(e=>e.transform.rotation[2]>.2));await page.locator('#scene-undo').click();await ready();await page.locator('#scale-0').fill('1.5');await page.locator('#entity-form button[type="submit"]').click();await ready();assert.ok((await state()).project.scene.entities.filter(e=>[cylinder.id,capsule.id].includes(e.id)).every(e=>e.transform.scale[0]===1.5));await page.locator('#scene-undo').click();await ready();assert.deepEqual((await state()).project.scene,transformBefore);report.criteria.push('Shift range and atomic multi-entity position/rotation/scale edits');
 await page.locator('#viewport').focus();await page.keyboard.press('f');await page.locator('#tool-move').click();await page.waitForTimeout(250);const arrow=page.locator('#scene-overlay polygon[data-handle="0"]');const arrowBox=await arrow.boundingBox();await page.mouse.move(arrowBox.x+arrowBox.width/2,arrowBox.y+arrowBox.height/2);await page.mouse.down();await page.mouse.move(arrowBox.x+arrowBox.width/2+35,arrowBox.y+arrowBox.height/2,{steps:8});await page.mouse.up();await ready();const groupMoved=(await state()).project.scene;const differences=[cylinder.id,capsule.id].map(id=>groupMoved.entities.find(e=>e.id===id).transform.position[0]-transformBefore.entities.find(e=>e.id===id).transform.position[0]);assert.ok(Math.abs(differences[0])>.05);assert.ok(Math.abs(differences[0]-differences[1])<1e-6);await page.locator('#scene-undo').click();await ready();report.criteria.push('Move arrowhead drag translates both selected entities with one Undo');
 await select('3D capsule');const gap=page.locator('.tree-gap').filter({hasNot:page.locator('.entity')});const beforeGap=page.locator(`.tree-gap[data-before-id="${cylinder.id}"]`);await page.locator('#entities .entity').filter({hasText:'3D capsule'}).dragTo(beforeGap);await ready();const ordered=(await state()).project.scene.entities;assert.ok(ordered.findIndex(e=>e.id===capsule.id)<ordered.findIndex(e=>e.id===cylinder.id));await page.locator('#scene-undo').click();await ready();await page.locator('#viewport').focus();await page.keyboard.press('Delete');await ready();assert.ok(!(await state()).project.scene.entities.some(e=>e.id===capsule.id));await page.keyboard.press('Control+z');await ready();report.criteria.push('drop between siblings reorders hierarchy; Delete removes selection and Undo restores it');
 await select('Empty ·');await page.locator('#component-search').fill('l');assert.deepEqual(await page.locator('#component-choice option').allTextContents(),['Light','LOD']);await page.locator('#component-search').fill('');assert.ok(await page.locator('#add-component').evaluate(n=>n===n.parentElement.lastElementChild));assert.ok(await page.locator('#entity-form').evaluate(n=>n.compareDocumentPosition(document.querySelector('#renderable-component'))&Node.DOCUMENT_POSITION_FOLLOWING));report.criteria.push('fundamental Transform comes first; searchable Add Component is last');
 const revisionBeforeResize=(await state()).project.revision;for(const [id,dx,dy]of [['left-resizer',30,0],['right-resizer',-25,0],['bottom-resizer',0,-40]]){const box=await page.locator('#'+id).boundingBox();await page.mouse.move(box.x+box.width/2,box.y+Math.min(box.height/2,200));await page.mouse.down();await page.mouse.move(box.x+box.width/2+dx,box.y+Math.min(box.height/2,200)+dy,{steps:8});await page.mouse.up();await page.waitForFunction(()=>document.querySelector('#editor-workspace').getAttribute('aria-busy')==='false');}const sized=await state();assert.ok(sized.project.revision>=revisionBeforeResize+3);assert.equal(sized.project.editor.leftWidth,250);assert.equal(sized.project.editor.rightWidth,315);assert.equal(sized.project.editor.bottomHeight,230);report.criteria.push('three panel resize handles persist project configuration independently of scene history');

 await page.locator('#file-menu > summary').click();await page.locator('#create-3d-menu > summary').click();await page.locator('#create-3d-menu details > summary').click();await page.locator('.create-primitive[data-dimension="3"][data-shape="cylinder"]').click();await ready();assert.equal((await state()).project.scene.entities.length,current.project.scene.entities.length+1);await page.locator('#scene-undo').click();await ready();await page.locator('#project-tab').click();await page.locator('#project-files button').filter({hasText:'Assets'}).click();assert.ok(await page.locator('#project-icons').getByText('3D-cube.glb',{exact:true}).count()>0);await page.locator('#console-tab').click();assert.ok(await page.locator('#clear').isVisible());assert.ok(await page.locator('#clear').evaluate(n=>!n.closest('nav')));report.criteria.push('File primitive menu, Project explorer first tab and separate Clear action');
 await select('3D pyramid');await page.locator('#viewport').focus();await page.keyboard.press('f');await page.waitForFunction(()=>{try{return JSON.parse(document.querySelector('#frame-trace').textContent).camera.target[0]===3.2;}catch{return false;}});const cameraBefore=JSON.parse(await page.locator('#frame-trace').textContent()).camera;const rect=await page.locator('#viewport').boundingBox();await page.mouse.move(rect.x+rect.width*.8,rect.y+rect.height*.6);await page.mouse.down({button:'right'});await page.mouse.move(rect.x+rect.width*.8+55,rect.y+rect.height*.6+20,{steps:8});await page.mouse.up({button:'right'});await page.waitForFunction(before=>{try{return JSON.stringify(JSON.parse(document.querySelector('#frame-trace').textContent).camera.position)!==JSON.stringify(before);}catch{return false;}},cameraBefore.position);const cameraAfter=JSON.parse(await page.locator('#frame-trace').textContent()).camera;assert.deepEqual(cameraAfter.target,cameraBefore.target);assert.notDeepEqual(cameraAfter.position,cameraBefore.position);report.criteria.push('right drag orbits focus rather than spinning in place');
 // Positive Z screen drag must produce the matching positive world quaternion.
 await page.locator('#orientation-widget circle[data-axis="2"][data-sign="1"]').click();await page.locator('#tool-rotate').click();await page.waitForTimeout(200);
 const rotationBefore=await state();const ring=page.locator('#scene-overlay polyline[data-handle="2"]');
 const points=await ring.getAttribute('points'),path=points.split(' ').map(p=>p.split(',').map(Number));const canvasBox=await page.locator('#viewport').boundingBox();const screen=p=>({x:canvasBox.x+p[0]*canvasBox.width/960,y:canvasBox.y+p[1]*canvasBox.height/540});const a=screen(path[4]),b=screen(path[8]);
 await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:8});await page.mouse.up();await ready();
 const rotated=(await state()).project.scene.entities.find(e=>e.name==='3D pyramid');assert.ok(rotated.transform.rotation[2]>0,'counterclockwise world Z drag follows the cursor');await page.locator('#scene-undo').click();await ready();assert.deepEqual((await state()).project.scene,rotationBefore.project.scene);report.criteria.push('real Rotate ring drag direction and single Undo');
 await page.locator('#tool-move').click();
 await select('Point light ·');await page.locator('#viewport').focus();await page.keyboard.press('f');await page.waitForTimeout(200);const baseline=await state();const before=await page.locator('#viewport').screenshot();const h=page.locator('#scene-overlay polygon[data-handle="0"]');const box=await h.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+65,box.y+box.height/2,{steps:8});await page.waitForTimeout(250);const during=await page.locator('#viewport').screenshot();assert.deepEqual((await state()).project.scene,baseline.project.scene);assert.ok(difference(before,during,true)>100,'light changes shaded pixels outside the gizmo region');await page.keyboard.press('Escape');await page.mouse.up();report.liveLightChangedPixels=difference(before,during,true);report.criteria.push('light illumination changes during uncommitted drag; Escape restores authored scene');
 await page.screenshot({path:join(evidence,'editor-workshop.png')});
 for(let i=1;i<3;i++){await open(demos[i].id);const original=(await state()).project.scene;const offset=original.entities.find(e=>e.name.startsWith('Offset box'));await page.locator('#play-start').click();await page.locator('#diagnostics-tab').click();assert.ok(await page.locator('#physics-component > summary').getByText('Collider',{exact:true}).count());await page.waitForFunction(id=>{try{const f=JSON.parse(document.querySelector('#frame-trace').textContent),b=f.physics.bodies.find(b=>b.id===id);return f.physics.steps>100&&Math.abs(b.rotation[3])<.99;}catch{return false;}},offset.id);const physical=JSON.parse(await page.locator('#frame-trace').textContent()).physics;const body=physical.bodies.find(b=>b.id===offset.id);assert.ok(Math.abs(body.rotation[3])<.9999||Math.hypot(...body.angularVelocity)>.1);assert.ok(physical.contacts.every(c=>c.point.every(Number.isFinite)));await page.screenshot({path:join(evidence,'angular-'+(i===1?'2d':'3d')+'.png')});await page.locator('#play-stop').click();assert.deepEqual((await state()).project.scene,original);report.criteria.push(`${i===1?'2D':'3D'} off-center impact produces angular motion and Stop restores scene`);}
 assert.deepEqual(report.pageErrors,[]);assert.deepEqual(report.consoleErrors,[]);assert.deepEqual(report.httpErrors,[]);report.passed=true;console.log('CORRECTIONS_BROWSER='+JSON.stringify(report));
}catch(error){report.failure=error.message;if(page){report.frame=await page.locator('#frame-trace').textContent().catch(()=>null);await page.screenshot({path:join(evidence,'failure.png')}).catch(()=>{});}throw error;}finally{await writeFile(join(evidence,'report.json'),JSON.stringify(report,null,2));await browser?.close();await daemon?.close();await rm(root,{recursive:true,force:true});}
