import {control} from './editor-controls.mjs';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {PNG} from 'pngjs';import {mkdtemp,mkdir,rm,writeFile} from 'node:fs/promises';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {createM10Demos} from '../../demos/create-m10-projects.mjs';import {startServer} from '../../daemon/bootstrap/server.mjs';import {envelope} from '../../protocol/src/protocol.ts';
const root=await mkdtemp(join(tmpdir(),'axiom-m10-browser-')),evidence=resolve('.axiom/browser-m10-evidence');await mkdir(evidence,{recursive:true});let daemon,browser,page;const report={criteria:[],pageErrors:[],consoleErrors:[],httpErrors:[],samples:[]};
function difference(a,b){const A=PNG.sync.read(a),B=PNG.sync.read(b);let changed=0;for(let i=0;i<A.data.length;i+=4)if([0,1,2].reduce((s,j)=>s+Math.abs(A.data[i+j]-B.data[i+j]),0)>8)changed++;return changed;}
try{
 const demos=await createM10Demos(root,{compile:true,requireScript:true,onProgress:console.log});daemon=await startServer({projectRoot:root});
 const command=async(type,data={})=>{const r=await fetch(daemon.origin+'/v1/commands',{method:'POST',headers:{Origin:daemon.origin,Authorization:'Bearer '+daemon.token,'Content-Type':'application/json'},body:JSON.stringify(envelope('command',{type,data}))});const v=await r.json();if(v.kind==='error')throw Error(JSON.stringify(v));return v.payload.data;};
 browser=await chromium.launch({headless:process.env.AXIOM_HEADLESS==='true',channel:'chromium',args:['--no-sandbox','--enable-gpu','--enable-unsafe-webgpu','--enable-unsafe-swiftshader','--enable-features=Vulkan','--use-angle=vulkan','--use-vulkan=swiftshader','--use-webgpu-adapter=swiftshader','--disable-vulkan-surface','--disable-dev-shm-usage']});
 page=await browser.newPage({viewport:{width:1700,height:1100}});function watch(p){p.on('pageerror',e=>report.pageErrors.push(e.message));p.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});p.on('response',r=>{if(r.status()>=400)report.httpErrors.push(r.status()+' '+new URL(r.url()).pathname);});p.on('dialog',d=>d.accept());p.setDefaultTimeout(60000);}watch(page);await page.goto(daemon.editorUrl);
 const trace=()=>page.locator('#frame-trace').textContent().then(JSON.parse);
 async function ready(){await page.waitForFunction(()=>{try{const f=JSON.parse(document.querySelector('#frame-trace').textContent);return f.rendering?.mode==='2d'&&f.kernel.view==='game'&&f.kernel.renderer==='webgpu';}catch{return false;}});await page.waitForTimeout(300);}
 async function refresh(){await (await control(page,'#workspace-refresh')).click();await ready();}
 async function open(id){await (await control(page,'#project-list')).selectOption(id);await (await control(page,'#project-open')).click();await (await control(page,'#game-tab')).click();await ready();}
 async function image(name){const buffer=await page.locator('#viewport').screenshot();await writeFile(join(evidence,name+'.png'),buffer);return buffer;}
 await open(demos[0].id);let f=await trace();assert.equal(f.rendering.time,0);assert.equal(f.rendering.particles,0);assert.equal(f.rendering.pixelScale,3);assert.equal(f.rendering.lights,2);const stopped=await image('adventure-stopped');await page.waitForTimeout(450);assert.equal(difference(stopped,await image('adventure-stopped-again')),0);const px=PNG.sync.read(stopped);let colored=0;for(let i=0;i<px.data.length;i+=4)if(Math.max(...px.data.slice(i,i+3))-Math.min(...px.data.slice(i,i+3))>25)colored++;assert.ok(colored>10000);report.criteria.push('Stopped Game preview renders atlas sprites, tilemap, 2D lighting and screen UI without advancing runtime');
 await page.locator('#entities .entity').filter({hasText:'Tilemap · select'}).click();const before=await command('scene.get');await page.locator('#two-d-tilemap [data-brush]').fill('2');await page.locator('#two-d-tilemap [data-cell="30"]').click();await ready();await page.waitForFunction(()=>document.querySelector('#editor-workspace').getAttribute('aria-busy')==='false');assert.equal((await command('scene.get')).project.scene.entities.find(e=>e.tilemap).tilemap.cells[30],2);assert.ok(difference(stopped,await image('tile-painted'))>100);await (await control(page,'#scene-undo')).click();await ready();assert.deepEqual((await command('scene.get')).project.scene,before.project.scene);report.criteria.push('Human tile-cell painting changes real pixels and one canonical Undo restores the scene');
 const s=await command('scene.get'),light=s.project.scene.entities.find(e=>e.light2D);await command('scene.light2D.set',{id:s.project.id,expectedSceneRevision:s.sceneRevision,entityId:light.id,value:{...light.light2D,intensity:0}});await refresh();const lightOff=await image('light-off');assert.ok(difference(stopped,lightOff)>100);await (await control(page,'#scene-undo')).click();await ready();report.criteria.push('2D radial lighting has measured visible pixel effect');
 await page.locator('#entities .entity').filter({hasText:'Hero · animated'}).click();await page.locator('#two-d-sprite2D [data-field="flipX"]').check();await page.locator('#two-d-sprite2D button[type="submit"]').click();await ready();assert.equal((await command('scene.get')).project.scene.entities.find(e=>e.spriteAnimation).sprite2D.flipX,true);await (await control(page,'#scene-undo')).click();await ready();
 await (await control(page,'#play-start')).click();await ready();await page.waitForFunction(()=>{try{const f=JSON.parse(document.querySelector('#frame-trace').textContent);return f.rendering.time>.4&&f.rendering.particles>0&&f.physics?.steps>5&&f.script.active;}catch{return false;}});const running=await image('adventure-play');assert.ok(difference(stopped,running)>500);const heroX=()=>trace().then(f=>f.script.entities.find(e=>e.id===demos[0].playerId).position[0]);const x=await heroX();await page.keyboard.down('ArrowRight');await page.waitForTimeout(650);await page.keyboard.up('ArrowRight');assert.ok(await heroX()>x+.8);report.criteria.push('Actual C# input moves the animated sprite through real Rust physics while particles emit');
 const box=await page.locator('#viewport').boundingBox();const clickPause=()=>page.mouse.click(box.x+box.width*.89,box.y+box.height*.075);await clickPause();await page.waitForFunction(()=>{try{return JSON.parse(document.querySelector('#frame-trace').textContent).rendering.paused;}catch{return false;}});const pause=await trace(),pausedImage=await image('adventure-paused');await page.keyboard.down('ArrowRight');await page.waitForTimeout(500);await page.keyboard.up('ArrowRight');const after=await trace();assert.equal(after.rendering.time,pause.rendering.time);assert.deepEqual(after.script.entities,pause.script.entities);assert.equal(after.physics.steps,pause.physics.steps);assert.equal(difference(pausedImage,await image('adventure-paused-again')),0);await clickPause();await page.waitForFunction(()=>{try{return !JSON.parse(document.querySelector('#frame-trace').textContent).rendering.paused;}catch{return false;}});report.criteria.push('Game UI consumes clicks, pauses animation/particles/scripts/physics and resumes without authoring mutation');
 await (await control(page,'#scene-tab')).click();const sceneX=await heroX();await page.keyboard.down('ArrowRight');await page.waitForTimeout(450);await page.keyboard.up('ArrowRight');assert.ok(Math.abs(await heroX()-sceneX)<.2);await (await control(page,'#play-stop')).click();await (await control(page,'#game-tab')).click();await ready();assert.equal((await trace()).rendering.time,0);assert.equal(difference(stopped,await image('adventure-reset')),0);report.criteria.push('Scene routes no Game input; Stop resets deterministic animation/particles and authored physics positions');await page.screenshot({path:join(evidence,'adventure-editor.png')});
 if(await page.locator('#scene-save').isEnabled())await (await control(page,'#scene-save')).click();await open(demos[1].id);f=await trace();assert.equal(f.rendering.quads,164);assert.equal(f.rendering.batches,2);assert.equal(f.rendering.submitted,2);report.samples.push(f.rendering);const alpha=await image('batching-alpha');const state=await command('scene.get'),front=state.project.scene.entities.find(e=>e.name.startsWith('Alpha front'));await command('scene.sprite2D.set',{id:state.project.id,expectedSceneRevision:state.sceneRevision,entityId:front.id,value:{...front.sprite2D,order:0}});await refresh();assert.ok(difference(alpha,await image('alpha-reordered'))>1000);await (await control(page,'#scene-undo')).click();await ready();assert.equal(difference(alpha,await image('alpha-restored')),0);report.criteria.push('164 ordered atlas/UI quads submit in two actual batches; alpha order changes pixels and Undo restores the golden');await page.screenshot({path:join(evidence,'batching-editor.png')});
 await page.close();await new Promise(resolve=>setTimeout(resolve,5200)); // Let the closed editor's 5s security lease expire.
 page=await browser.newPage({viewport:{width:1700,height:1100}});watch(page);await page.goto(daemon.editorUrl.replace('#','?renderer=null#'));await page.waitForFunction(()=>{try{const f=JSON.parse(document.querySelector('#frame-trace').textContent);return f.rendering?.mode==='2d'&&f.kernel.renderer==='null';}catch{return false;}});await (await control(page,'#game-tab')).click();await page.waitForFunction(()=>{try{return JSON.parse(document.querySelector('#frame-trace').textContent).kernel.view==='game';}catch{return false;}});f=await trace();assert.equal(f.rendering.submitted,0);assert.equal(f.rendering.pixels,'unavailable');assert.equal(f.rendering.quads,164);await page.screenshot({path:join(evidence,'null-editor.png')});report.criteria.push('Null shares bounded planning with zero GPU submissions and explicitly unavailable pixels');assert.deepEqual(report.pageErrors,[]);assert.deepEqual(report.consoleErrors,[]);assert.deepEqual(report.httpErrors,[]);const faults=await command('diagnostics.query',{limit:100,maxBytes:65536});assert.deepEqual(faults.items,[],'Editor/GPU errors must be absent');report.passed=true;console.log('M10_BROWSER='+JSON.stringify(report));
}catch(error){report.failure=error.message;if(page){report.editorLogs=await page.locator('#logs').textContent().catch(()=>null);report.lastFrame=await page.locator('#frame-trace').textContent().catch(()=>null);console.error(await page.locator('body').innerText().catch(()=>''));await page.screenshot({path:join(evidence,'failure.png'),timeout:10000}).catch(()=>{});}throw error;}finally{await writeFile(join(evidence,'report.json'),JSON.stringify(report,null,2));await browser?.close();await daemon?.close();await rm(root,{recursive:true,force:true});}
