import {control} from './editor-controls.mjs';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {PNG} from 'pngjs';import {mkdtemp,mkdir,rm,writeFile} from 'node:fs/promises';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {createM11Demos} from '../../demos/create-m11-projects.mjs';import {startServer} from '../../daemon/bootstrap/server.mjs';import {envelope} from '../../protocol/src/protocol.ts';import {renderingDefaults} from '../../engine/renderer/render-plan.mjs';
const root=await mkdtemp(join(tmpdir(),'axiom-m11-browser-')),evidence=resolve('.axiom/browser-m11-evidence');await mkdir(evidence,{recursive:true});let daemon,browser,page;const report={criteria:[],pageErrors:[],consoleErrors:[],httpErrors:[],samples:[]};
function difference(a,b){const A=PNG.sync.read(a),B=PNG.sync.read(b);let changed=0;for(let i=0;i<A.data.length;i+=4)if([0,1,2].reduce((s,j)=>s+Math.abs(A.data[i+j]-B.data[i+j]),0)>8)changed++;return changed;}
try{const demos=await createM11Demos(root,{compile:true,requireScript:true,onProgress:console.log});daemon=await startServer({projectRoot:root});
 const command=async(type,data={})=>{const r=await fetch(daemon.origin+'/v1/commands',{method:'POST',headers:{Origin:daemon.origin,Authorization:'Bearer '+daemon.token,'Content-Type':'application/json'},body:JSON.stringify(envelope('command',{type,data}))});const v=await r.json();if(v.kind==='error')throw Error(JSON.stringify(v));return v.payload.data;};
 browser=await chromium.launch({headless:process.env.AXIOM_HEADLESS==='true',channel:'chromium',args:['--no-sandbox','--enable-gpu','--enable-unsafe-webgpu','--enable-unsafe-swiftshader','--enable-features=Vulkan','--use-angle=vulkan','--use-vulkan=swiftshader','--use-webgpu-adapter=swiftshader','--disable-vulkan-surface','--disable-dev-shm-usage']});
 function watch(p){p.on('pageerror',e=>report.pageErrors.push(e.message));p.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});p.on('response',r=>{if(r.status()>=400)report.httpErrors.push(r.status()+' '+new URL(r.url()).pathname);});p.on('dialog',d=>d.accept());p.setDefaultTimeout(60000);}
 page=await browser.newPage({viewport:{width:1700,height:1100}});watch(page);await page.goto(daemon.editorUrl);const trace=()=>page.locator('#frame-trace').textContent().then(JSON.parse);
 async function ready(count=2,backend='webgpu'){await page.waitForFunction(()=>document.querySelector('#editor-workspace').getAttribute('aria-busy')==='false');const s=await command('scene.get');await page.waitForFunction(({count,backend,id,revision,playing})=>{try{const f=JSON.parse(document.querySelector('#frame-trace').textContent);return f.animation?.length===count&&f.kernel.renderer===backend&&f.kernel.sceneId===id&&f.animationProvenance?.sceneRevision===revision&&f.kernel.mode===(playing?'play':'stopped');}catch{return false;}},{count,backend,id:s.project.scene.id,revision:s.sceneRevision,playing:s.playing});await page.waitForTimeout(300);}
 async function open(id,count=2){await (await control(page,'#project-list')).selectOption(id);await (await control(page,'#project-open')).click();await (await control(page,'#game-tab')).click();await ready(count);}
 async function refresh(count=2){await (await control(page,'#workspace-refresh')).click();await ready(count);}
 async function select(id){await page.locator('.tree-row[data-entity-id="'+id+'"] > .entity').click();}
 async function image(name){const bytes=await page.locator('#viewport').screenshot();await writeFile(join(evidence,name+'.png'),bytes);return bytes;}
 async function animationWait(fn){const end=Date.now()+60000;while(Date.now()<end){if(fn((await trace()).animation))return;await page.waitForTimeout(50);}throw Error('Timed out waiting for observed animation state');}
 await open(demos[0].id);let state=await command('scene.get'),args=x=>({id:state.project.id,expectedSceneRevision:state.sceneRevision,...x});const bind=await image('skin-bind');await page.waitForTimeout(400);assert.equal(difference(bind,await image('skin-bind-again')),0);assert.equal((await trace()).animation[0].whyAnimationNotPlaying,'Play is stopped');report.criteria.push('Imported skeleton bind pose renders in stopped Game without advancing time');
 await select(demos[0].animatedId);assert.ok(await page.locator('#animation-component').isVisible());const speed=page.locator('#animation-component form > label input[name="speed"]');await speed.fill('1.5');await page.locator('#animation-component button[type="submit"]').click();await ready();assert.equal((await command('scene.get')).project.scene.entities[0].animator.speed,1.5);await (await control(page,'#scene-undo')).click();await ready();assert.equal((await command('scene.get')).project.scene.entities[0].animator.speed,1);report.criteria.push('Human Animator fields use canonical authoring and one Undo');await page.screenshot({path:join(evidence,'skin-editor.png')});
 await (await control(page,'#play-start')).click();await animationWait(a=>a[0].time>.4);assert.ok(difference(bind,await image('skin-play'))>100);let f=await trace();assert.equal(f.animation[1].whyAnimationNotPlaying,'Animator paused');report.criteria.push('Real Rust pose drives WebGPU skinning; independent autoplay-disabled instance remains paused');
 await select(demos[0].animatedId);await page.getByRole('button',{name:'Pause Animator',exact:true}).click();await animationWait(a=>a[0].paused);const paused=await image('skin-paused');await page.waitForTimeout(500);assert.equal(difference(paused,await image('skin-paused-again')),0);await page.getByRole('button',{name:'Resume Animator',exact:true}).click();await animationWait(a=>!a[0].paused);report.criteria.push('Human pause freezes actual skinned pixels and resume advances the same instance');
 state=await command('scene.get');await page.locator('#viewport').focus();await page.keyboard.down('Digit1');await animationWait(a=>a[0].currentAnimation==='Wave');await page.keyboard.up('Digit1');await page.keyboard.down('Digit2');await animationWait(a=>a[0].currentAnimation==='Idle');await page.keyboard.up('Digit2');await command('animation.control',args({entityId:demos[0].animatedId,action:'parameter',name:'energy',value:1}));await animationWait(a=>a[0].currentAnimation==='Wave');await animationWait(a=>a[0].transition===null);const observed=await command('animation.query',args({entityId:demos[0].animatedId}));assert.equal(observed.status,'observed');assert.equal(observed.items[0].currentAnimation,'Wave');assert.equal(observed.items[0].whyAnimationNotPlaying,null);report.samples.push(observed);await command('animation.control',args({entityId:demos[0].animatedId,action:'state',name:'Bounce',duration:1}));await animationWait(a=>a[0].currentAnimation==='Bounce'&&a[0].transition!==null);await image('skin-crossfade');await command('animation.control',args({entityId:demos[0].animatedId,action:'parameter',name:'energy',value:0}));await animationWait(a=>a[0].currentAnimation==='Idle'&&a[0].transition===null);report.criteria.push('C# keyboard API, AI runtime parameter, crossfade and completion transitions expose observed currentAnimation/transition/reason without authoring');
 await (await control(page,'#play-stop')).click();await ready();assert.equal(difference(bind,await image('skin-reset')),0);assert.deepEqual((await command('scene.get')).project.scene.entities,state.project.scene.entities);report.criteria.push('Stop restores deterministic bind pixels and discards runtime parameters without dirtying authoring');
 state=await command('scene.get');await command('scene.rendering.update',args({value:{...renderingDefaults,culling:'cpu',shadows:false,bloom:0,fxaa:false}}));await refresh();const hdr=await image('skin-hdr-bind');await (await control(page,'#play-start')).click();await animationWait(a=>a[0].time>.5);assert.ok(difference(hdr,await image('skin-hdr-play'))>100);assert.equal((await trace()).rendering.hdrFormat,'rgba16float');await (await control(page,'#play-stop')).click();await ready();await (await control(page,'#scene-undo')).click();await ready();report.criteria.push('HDR and legacy passes consume the same GPU-skinned pose with animated bounds');
 await open(demos[1].id);const rigid=await image('rigid-bind');await (await control(page,'#play-start')).click();await animationWait(a=>a[0].time>.5);assert.ok(difference(rigid,await image('rigid-play'))>50);await (await control(page,'#play-stop')).click();await ready();await open(demos[2].id,0);await page.locator('.scene-root-button').click();await (await control(page,'#scene-tab')).click();await ready(0);const scene=PNG.sync.read(await image('pixel-scene'));await (await control(page,'#game-tab')).click();await ready(0);const game=PNG.sync.read(await image('pixel-game'));const colors=p=>{const set=new Set();for(let i=0;i<p.data.length;i+=4){const [r,g,b]=p.data.slice(i,i+3);if(g>r+40&&g>b)set.add([r,g,b].join(','));}return [...set].sort();};assert.deepEqual(colors(scene),colors(game));assert.ok(colors(scene).length<=2);report.criteria.push('Rigid clips animate normally; pixelPerfect Scene preserves exact sprite colors while retaining free camera');
 await page.close();await new Promise(r=>setTimeout(r,5200));page=await browser.newPage({viewport:{width:1700,height:1100}});watch(page);const nullUrl=new URL(daemon.editorUrl);nullUrl.searchParams.set('renderer','null');await page.goto(nullUrl.href);await (await control(page,'#project-list')).selectOption(demos[0].id);await (await control(page,'#project-open')).click();await (await control(page,'#game-tab')).click();await ready(2,'null');await (await control(page,'#play-start')).click();await animationWait(a=>a[0].time>.3);f=await trace();assert.equal(f.kernel.renderer,'null');assert.equal(f.animation[0].currentAnimation,'Idle');await page.screenshot({path:join(evidence,'null-editor.png')});report.criteria.push('Null consumes real Rust animation and observed diagnostics with no GPU requirement');
 const diagnostics=await command('diagnostics.query',{limit:100,maxBytes:65536});assert.equal(diagnostics.items.filter(i=>['editor','renderer'].includes(i.subsystem)).length,0);assert.deepEqual(report.pageErrors,[]);assert.deepEqual(report.consoleErrors,[]);assert.deepEqual(report.httpErrors,[]);report.passed=true;await writeFile(join(evidence,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}catch(error){if(page){await page.screenshot({path:join(evidence,'failure.png')}).catch(()=>{});await writeFile(join(evidence,'failure.txt'),(await page.locator('body').innerText().catch(()=>''))+'\n'+error.stack);}report.error=error.stack;await writeFile(join(evidence,'report.json'),JSON.stringify(report,null,2));throw error;}finally{await browser?.close();await daemon?.close();await rm(root,{recursive:true,force:true});}
