import {control} from './editor-controls.mjs';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {createM12Demos} from '../../demos/create-m12-projects.mjs';import {startServer} from '../../daemon/bootstrap/server.mjs';import {envelope} from '../../protocol/src/protocol.ts';
const root=await mkdtemp(join(tmpdir(),'axiom-audio-browser-')),evidence=resolve('.axiom/browser-m12-evidence');await mkdir(evidence,{recursive:true});const report={criteria:[],samples:[],pageErrors:[],consoleErrors:[],httpErrors:[],expectedReadCancellations:[]};let daemon,browser,page;
try{const demos=await createM12Demos(root,{compile:true,requireScript:true,onProgress:console.log});daemon=await startServer({projectRoot:root});const command=async(type,data={})=>{const r=await fetch(daemon.origin+'/v1/commands',{method:'POST',headers:{Origin:daemon.origin,Authorization:'Bearer '+daemon.token,'Content-Type':'application/json'},body:JSON.stringify(envelope('command',{type,data}))});const v=await r.json();if(v.kind==='error')throw Error(JSON.stringify(v));return v.payload.data;};
 browser=await chromium.launch({headless:process.env.AXIOM_HEADLESS==='true',channel:'chromium',args:['--no-sandbox','--autoplay-policy=document-user-activation-required','--disable-features=PreloadMediaEngagementData,MediaEngagementBypassAutoplayPolicies','--mute-audio','--enable-gpu','--enable-unsafe-webgpu','--enable-unsafe-swiftshader','--enable-features=Vulkan','--use-angle=vulkan','--use-vulkan=swiftshader','--use-webgpu-adapter=swiftshader','--disable-vulkan-surface','--disable-dev-shm-usage']});
 function watch(p){p.on('pageerror',e=>report.pageErrors.push(e.message));p.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});p.on('response',async r=>{if(r.status()<400)return;try{const request=r.request().postDataJSON(),body=await r.json();if(r.status()===422&&request?.payload?.type==='asset.audio.read'&&body.payload?.code==='AX_SCENE_0002'){const current=await command('scene.get'),old=request.payload.data;if(old.id!==current.project?.id||old.expectedSceneRevision!==current.sceneRevision){report.expectedReadCancellations.push({id:old.id,expectedSceneRevision:old.expectedSceneRevision,currentSceneRevision:current.sceneRevision,code:body.payload.code});return;}}}catch{}report.httpErrors.push(r.status()+' '+new URL(r.url()).pathname);});p.on('dialog',d=>d.accept());p.setDefaultTimeout(60000);}
 async function next(url=daemon.editorUrl){if(page){await page.close();await new Promise(r=>setTimeout(r,5200));}page=await browser.newPage({viewport:{width:1700,height:1100}});watch(page);await page.goto(url);}
 const trace=()=>page.locator('#frame-trace').textContent().then(JSON.parse);async function wait(fn){const end=Date.now()+60000;while(Date.now()<end){try{const f=await trace();if(fn(f))return f;}catch{}await page.waitForTimeout(50);}throw Error('Timed out waiting for observed audio');}
 async function ready(count){await page.waitForFunction(()=>document.querySelector('#editor-workspace').getAttribute('aria-busy')==='false');const s=await command('scene.get');await wait(f=>f.audioProvenance?.projectId===s.project.id&&f.audioProvenance?.sceneRevision===s.sceneRevision&&f.audio?.sources?.length===count&&f.audio.loaded&&f.audio.sources.every(i=>i.assetId)&&f.kernel.sceneId===s.project.scene.id&&f.kernel.mode===(s.playing?'play':'stopped'));}
 async function open(id,count){await (await control(page,'#project-list')).selectOption(id);await (await control(page,'#project-open')).click();await (await control(page,'#game-tab')).click();await ready(count);}
 async function select(id){await page.locator('.tree-row[data-entity-id="'+id+'"] > .entity').click();}async function screenshot(name){await page.screenshot({path:join(evidence,name+'.png')});}
 await next();await open(demos[0].id,1);let s=await command('scene.get');const args=x=>({id:s.project.id,expectedSceneRevision:s.sceneRevision,...x});let f=await trace();assert.equal(f.audio.sources[0].positionSeconds,0);assert.equal(f.audio.masterRms??0,0);assert.equal(f.audio.sources[0].whyAudioNotPlaying,'Play is stopped');await page.waitForTimeout(300);assert.equal((await trace()).audio.sources[0].positionSeconds,0);report.criteria.push('Stopped Scene/Game previews are silent and do not advance WAV playback');
 await select(demos[0].sourceId);await page.locator('#audio-component input[name="volume"]').first().fill('.4');await page.getByRole('button',{name:'Apply AudioSource',exact:true}).click();await ready(1);assert.equal((await command('scene.get')).project.scene.entities.find(e=>e.audioSource).audioSource.volume,.4);await (await control(page,'#scene-undo')).click();await ready(1);assert.equal((await command('scene.get')).project.scene.entities.find(e=>e.audioSource).audioSource.volume,.7);await screenshot('spatial-editor');report.criteria.push('Human AudioSource editing uses canonical validation and one Undo');
 await (await control(page,'#play-start')).click();f=await wait(f=>f.audio?.masterRms>.002&&f.audio.sources[0].positionSeconds>.2);assert.ok(f.audio.stereoRms[0]>f.audio.stereoRms[1]*1.3);report.samples.push({name:'left spatial signal',audio:f.audio});await screenshot('spatial-left');report.criteria.push('Actual Web Audio stereo signal demonstrates spatial pan and listener-relative attenuation');
 await page.locator('#viewport').focus();await page.keyboard.down('Digit1');await wait(f=>f.audio?.sources[0].whyAudioNotPlaying==='Source paused');await page.keyboard.up('Digit1');await page.waitForTimeout(350);const paused=(await trace()).audio.sources[0].positionSeconds;await page.waitForTimeout(400);assert.equal((await trace()).audio.sources[0].positionSeconds,paused);assert.ok((await trace()).audio.masterRms<.0001);await page.keyboard.down('Digit2');await wait(f=>f.audio?.masterRms>.002);await page.keyboard.up('Digit2');await page.keyboard.down('ArrowRight');f=await wait(f=>f.audio?.stereoRms[1]>f.audio?.stereoRms[0]*1.3);await page.keyboard.up('ArrowRight');report.samples.push({name:'right spatial signal',audio:f.audio});await screenshot('spatial-right');report.criteria.push('C# pause/resume freezes the clip and Arrow movement changes actual left/right output');
 s=await command('scene.get');const original=structuredClone(s.project.scene.entities);await command('audio.control',args({entityId:demos[0].sourceId,action:'volume',value:.05}));await wait(f=>f.audio?.sources[0].volume===.05);await command('audio.control',args({action:'busMute',name:'Effects',value:1}));await wait(f=>f.audio?.sources[0].whyAudioNotPlaying==='Bus muted'&&f.audio.masterRms<.0001);const observed=await command('audio.query',args({entityId:demos[0].sourceId}));assert.equal(observed.status,'observed');assert.equal(observed.items[0].whyAudioNotPlaying,'Bus muted');report.samples.push(observed);await (await control(page,'#scene-tab')).click();await wait(f=>f.audio?.sources[0].whyAudioNotPlaying==='Scene view is silent');await (await control(page,'#play-stop')).click();await ready(1);assert.equal((await trace()).audio.sources[0].positionSeconds,0);assert.deepEqual((await command('scene.get')).project.scene.entities,original);report.criteria.push('AI volume/bus controls expose observed reasons, Scene is silent, and Stop resets without authoring mutation');
 await open(demos[1].id,2);await (await control(page,'#play-start')).click();f=await wait(f=>f.audio?.masterRms>.002&&f.audio.sources[0].positionSeconds>1&&f.audio.reads>4);assert.equal(f.audio.sources[0].stream,true);assert.ok(f.audio.sources[0].queuedFrames<=16384);assert.ok(f.audio.decodedBytes<100000);report.samples.push({name:'bounded streaming output',audio:f.audio});await select(demos[1].sourceId);await page.getByRole('button',{name:'pause audio',exact:true}).click();await wait(f=>f.audio?.sources[0].whyAudioNotPlaying==='Source paused');await page.waitForTimeout(350);const streamPaused=(await trace()).audio.sources[0].positionSeconds;await page.waitForTimeout(400);assert.equal((await trace()).audio.sources[0].positionSeconds,streamPaused);await page.getByRole('button',{name:'resume audio',exact:true}).click();await wait(f=>f.audio?.masterRms>.002&&f.audio.sources[0].positionSeconds>streamPaused+.2);await screenshot('streaming-editor');report.criteria.push('Actual AudioWorklet streams a 90-second stereo WAV in bounded chunks, with measured output and pause-preserved playhead');
 s=await command('scene.get');await command('audio.control',args({action:'busMute',name:'Music',value:1}));await select(demos[1].shotId);await page.getByRole('button',{name:'play audio',exact:true}).click();await wait(f=>f.audio?.sources.find(i=>i.entityId===demos[1].shotId)?.playing&&f.audio.masterRms>.002);await wait(f=>f.audio?.sources.find(i=>i.entityId===demos[1].shotId)?.whyAudioNotPlaying==='Nonlooping source completed'&&f.audio.masterRms<.0001);await (await control(page,'#play-stop')).click();await ready(2);report.criteria.push('Human one-shot starts from stopped state, produces a real effect and completes while a muted stream keeps its transport');
 s=await command('scene.get');const beforeFilter=structuredClone(s.project.scene.audio);await command('scene.audio.update',args({value:{...beforeFilter,buses:beforeFilter.buses.map(b=>b.name==='Music'?{...b,lowpassHz:20}:b)}}));await ready(2);await (await control(page,'#play-start')).click();f=await wait(f=>f.audio?.sources[0].positionSeconds>.4&&f.audio.masterRms>0);const fullBand=report.samples.find(s=>s.name==='bounded streaming output').audio.masterRms;assert.ok(f.audio.masterRms<fullBand*.2);report.samples.push({name:'measured lowpass output',audio:f.audio});await (await control(page,'#play-stop')).click();await ready(2);await (await control(page,'#scene-undo')).click();await ready(2);assert.deepEqual((await command('scene.get')).project.scene.audio,beforeFilter);report.criteria.push('Authored bus lowpass attenuates actual streamed signal and one Undo restores mixer settings');
 const nullUrl=new URL(daemon.editorUrl);nullUrl.searchParams.set('renderer','null');await next(nullUrl.href);await open(demos[1].id,2);await (await control(page,'#play-start')).click();f=await wait(f=>f.audio?.backend==='null'&&f.kernel.mode==='play');assert.equal(f.audio.masterRms,null);assert.equal(f.audio.reads,0);assert.ok(f.audio.sources.every(i=>i.whyAudioNotPlaying==='Null audio backend'&&!i.playing));await screenshot('null-editor');await (await control(page,'#play-stop')).click();await ready(2);report.criteria.push('Null exposes semantic audio state with explicitly unavailable sound, zero decoded memory and no PCM reads');
 // Playwright evaluations carry userGesture:true. Observe this fresh page through
 // CDP without granting activation, so this exercises Chromium's real policy.
 await next();const cdp=await page.context().newCDPSession(page);
 const raw=async expression=>(await cdp.send('Runtime.evaluate',{expression,returnByValue:true,userGesture:false})).result.value;
 async function waitUnactivated(predicate){const end=Date.now()+60000;while(Date.now()<end){const observed=await raw("(()=>{try{return JSON.parse(document.querySelector('#frame-trace').textContent)}catch{return null}})()");if(observed&&predicate(observed))return observed;await new Promise(r=>setTimeout(r,50));}throw Error('Timed out waiting for unactivated browser audio');}
 await waitUnactivated(f=>f.audio?.loaded&&f.audio.sources.length===2&&f.kernel.mode==='stopped');
 await raw("document.querySelector('#game-tab').click()");s=await command('scene.get');await command('play.start',args());f=await waitUnactivated(f=>f.kernel.mode==='play'&&f.audio?.sources[0].whyAudioNotPlaying==='Browser audio activation required');assert.equal(await raw('navigator.userActivation.hasBeenActive'),false);assert.equal(f.audio.contextState,'suspended');assert.equal(f.audio.masterRms,null);report.samples.push({name:'unactivated browser context',audio:f.audio});await screenshot('activation-required');await (await control(page,'#audio-settings')).getByRole('button',{name:'Enable browser audio',exact:true}).click();await wait(f=>f.audio?.contextState==='running'&&f.audio.masterRms>.002);report.criteria.push('A fresh non-gesture Play reports browser activation required; a human gesture enables actual output');
 assert.deepEqual(report.pageErrors,[]);const staleReadConsole=report.consoleErrors.filter(v=>v==='Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)');assert.equal(staleReadConsole.length,report.expectedReadCancellations.length,'Every resource rejection must be a verified stale PCM lease');assert.deepEqual(report.consoleErrors.filter(v=>!staleReadConsole.includes(v)),[]);assert.deepEqual(report.httpErrors,[]);const faults=await command('diagnostics.query',{limit:100,maxBytes:65536});assert.equal(faults.items.filter(i=>['editor','renderer'].includes(i.subsystem)).length,0);report.passed=true;console.log('M12_BROWSER='+JSON.stringify(report));
}catch(error){report.error=error.stack;if(page){await page.screenshot({path:join(evidence,'failure.png')}).catch(()=>{});report.lastFrame=await page.locator('#frame-trace').textContent().catch(()=>null);await writeFile(join(evidence,'failure.txt'),(await page.locator('body').innerText().catch(()=>''))+'\n'+error.stack);}throw error;}finally{await writeFile(join(evidence,'report.json'),JSON.stringify(report,null,2));await browser?.close();await daemon?.close();await rm(root,{recursive:true,force:true});}
