import {control} from './editor-controls.mjs';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {createM13Demos} from '../../demos/create-m13-projects.mjs';import {renderingDefaults} from '../../engine/renderer/render-plan.mjs';import {startServer} from '../../daemon/bootstrap/server.mjs';import {envelope} from '../../protocol/src/protocol.ts';
const root=await mkdtemp(join(tmpdir(),'axiom-profiler-browser-')),evidence=resolve('.axiom/browser-m13-evidence');await mkdir(evidence,{recursive:true});const report={criteria:[],samples:[],pageErrors:[],consoleErrors:[],httpErrors:[]};let daemon,browser,page;
try{const demos=await createM13Demos(root,{compile:true,requireScript:true,onProgress:console.log});daemon=await startServer({projectRoot:root});const command=async(type,data={})=>{const r=await fetch(daemon.origin+'/v1/commands',{method:'POST',headers:{Origin:daemon.origin,Authorization:'Bearer '+daemon.token,'Content-Type':'application/json'},body:JSON.stringify(envelope('command',{type,data}))});const v=await r.json();if(v.kind==='error')throw Error(JSON.stringify(v));return v.payload.data;};
 browser=await chromium.launch({headless:process.env.AXIOM_HEADLESS==='true',channel:'chromium',args:['--no-sandbox','--enable-gpu','--enable-unsafe-webgpu','--enable-unsafe-swiftshader','--enable-features=Vulkan','--use-angle=vulkan','--use-vulkan=swiftshader','--use-webgpu-adapter=swiftshader','--disable-vulkan-surface','--disable-dev-shm-usage']});
 async function next(url=daemon.editorUrl){if(page){await page.close();await new Promise(r=>setTimeout(r,5200));}page=await browser.newPage({viewport:{width:1700,height:1100}});page.setDefaultTimeout(60000);page.on('pageerror',e=>report.pageErrors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});page.on('response',r=>{if(r.status()>=400)report.httpErrors.push(r.status()+' '+new URL(r.url()).pathname);});page.on('dialog',d=>d.accept());await page.goto(url);}
 const trace=()=>page.locator('#frame-trace').textContent().then(JSON.parse);async function wait(fn){const end=Date.now()+60000;while(Date.now()<end){try{const f=await trace();if(fn(f))return f;}catch{}await page.waitForTimeout(50);}throw Error('Timed out waiting for profiler evidence');}
 async function ready(){await page.waitForFunction(()=>document.querySelector('#editor-workspace').getAttribute('aria-busy')==='false');const s=await command('scene.get');return wait(f=>f.profileContext?.projectId===s.project.id&&f.profileContext.sceneRevision===s.sceneRevision&&f.kernel.mode===(s.playing?'play':'stopped'));}
 async function open(id){await (await control(page,'#project-list')).selectOption(id);await (await control(page,'#project-open')).click();await (await control(page,'#game-tab')).click();await ready();await page.locator('#profiler-tab').click();}
 let s;const args=x=>({id:s.project.id,expectedSceneRevision:s.sceneRevision,...x});async function history(){s=await command('scene.get');return command('profiler.query',args({limit:20}));}async function allFrames(){let h=await history(),items=[...h.items];while(h.nextBefore){h=await command('profiler.query',args({limit:20,beforeFrame:h.nextBefore}));items.unshift(...h.items);}return items;}
 async function screenshot(name){await page.screenshot({path:join(evidence,name+'.png')});}
 await next();await open(demos[0].id);let h=await history();assert.equal(h.status,'observed');assert.ok(h.items.every(f=>f.scopes.some(s=>s.name==='kernel.world-physics')&&f.scopes.some(s=>s.name==='audio.update')));assert.ok(h.items.every(f=>!f.playing));report.criteria.push('Stopped Game previews collect real bounded scopes without entering Play');
 await (await control(page,'#play-start')).click();await ready();await wait(f=>f.kernel.frame>=60&&f.script?.active);const original=structuredClone((await command('scene.get')).project.scene);await page.locator('#viewport').focus();await page.keyboard.down('Digit1');await page.waitForTimeout(300);await page.keyboard.up('Digit1');await page.locator('#profiler-pause').check();await page.locator('#profiler-refresh').click();const frames=await allFrames(),pulse=frames.find(f=>f.scopes.some(s=>s.name==='worker.dispatch'&&s.milliseconds>=130));assert.ok(pulse,'Actual C# pulse was retained');const explanation=await command('profiler.explainFrameSpike',args({frameSequence:pulse.frameSequence,metric:'elapsed'}));assert.equal(explanation.status,'explained');assert.equal(explanation.spike,true);assert.ok(explanation.contributors.some(c=>c.name==='worker.dispatch'&&c.deltaMs>100));assert.ok(explanation.contributors.some(c=>c.name==='script.roundtrip'&&c.overlap));report.samples.push(explanation);report.criteria.push('A real 140ms C# regression is attributed to measured worker dispatch and overlapping roundtrip, with a prior comparable baseline');
 await page.locator('#profiler-frame').fill(String(pulse.frameSequence));await page.locator('#profiler-explain').click();const human=JSON.parse(await page.locator('#profiler-detail').textContent());assert.deepEqual(human,explanation);await screenshot('worker-spike-profiler');const count=(await history()).retained,frameBefore=(await trace()).kernel.frame;await page.waitForTimeout(400);assert.equal((await history()).retained,count);await wait(f=>f.kernel.frame>frameBefore);assert.deepEqual((await command('scene.get')).project.scene,original);report.criteria.push('Human and agent spike explanations are identical; pause collection keeps gameplay advancing and leaves authoring untouched');
 const samples=frames.filter(f=>f.gpuStatus==='observed');if(samples.length){assert.ok(samples.length>=2);assert.ok(samples.every(f=>f.gpuScopes.some(s=>s.name==='legacy.color')&&f.gpuTimeMs>=0));report.samples.push({name:'legacy timestamps',items:samples});}else{assert.ok(frames.every(f=>f.gpuTimeMs===null));assert.ok(frames.some(f=>/unavailable|sampled|readback/.test(f.gpuReason)));}report.criteria.push('Repeated asynchronous GPU samples carry exact frame/session provenance, or explicit timestamp unavailability');
 await page.locator('#profiler-clear').click();assert.equal((await history()).retained,0);assert.equal((await command('profiler.explainFrameSpike',args({frameSequence:pulse.frameSequence}))).status,'unavailable');await page.locator('#profiler-pause').uncheck();await wait(f=>f.kernel.frame>frameBefore+30);await (await control(page,'#play-stop')).click();await ready();s=await command('scene.get');assert.deepEqual(s.project.scene,original);h=await history();assert.ok(h.items.every(f=>!f.playing&&f.generation!==pulse.generation));report.criteria.push('Clear, Stop and snapshot replacement discard old evidence; Stop restores the authored scene');
 // The same editable project exercises multi-pass production timestamps.
 await command('scene.rendering.update',args({value:renderingDefaults}));await ready();await wait(f=>f.kernel.frame>=60&&f.rendering?.hdrFormat==='rgba16float');await page.locator('#profiler-pause').check();h=await history();const hdr=(await allFrames()).filter(f=>f.gpuStatus==='observed');if(samples.length){assert.ok(hdr.length>=2);assert.ok(hdr.every(f=>['hdr.light-tiles','hdr.shadow','hdr.color','hdr.bloom','hdr.post'].every(name=>f.gpuScopes.some(s=>s.name===name))));}report.samples.push({name:'HDR timestamps',items:hdr});await screenshot('hdr-pass-profiler');report.criteria.push('HDR compute, shadow, color, bloom and post passes use bounded GPU timestamp instrumentation');
 await page.locator('#profiler-pause').uncheck();await open(demos[1].id);await wait(f=>f.kernel.frame>=60&&f.rendering?.mode==='2d'&&f.rendering.visible===5);await page.locator('#profiler-pause').check();const twoD=await allFrames();assert.ok(twoD.every(f=>f.route==='2d'&&f.projectId===demos[1].id));if(samples.length)assert.ok(twoD.some(f=>f.gpuScopes.some(s=>s.name==='2d.color')));report.samples.push({name:'2D timestamp samples',items:twoD.filter(f=>f.gpuStatus==='observed')});await screenshot('two-d-profiler');report.criteria.push('Editable sprite demo exposes the independent 2D pass and never mixes project histories');
 const nullUrl=new URL(daemon.editorUrl);nullUrl.searchParams.set('renderer','null');await next(nullUrl.href);await open(demos[1].id);await wait(f=>f.kernel.frame>=15);h=await history();assert.ok(h.items.every(f=>f.renderer==='null'&&f.gpuTimeMs===null&&f.gpuStatus==='unavailable'));const nullResult=await command('profiler.explainFrameSpike',args({frameSequence:h.items.at(-1).frameSequence,metric:'gpu'}));assert.equal(nullResult.status,'unavailable');assert.match(nullResult.message,/Null/);await screenshot('null-profiler');report.criteria.push('Null continues measured main scopes and reports GPU unavailable rather than zero');
 assert.deepEqual(report.pageErrors,[]);assert.deepEqual(report.consoleErrors,[]);assert.deepEqual(report.httpErrors,[]);const faults=await command('diagnostics.query',{limit:100,maxBytes:65536});assert.equal(faults.items.filter(i=>['editor','renderer'].includes(i.subsystem)).length,0);report.passed=true;console.log('M13_BROWSER='+JSON.stringify(report));
}catch(error){report.error=error.stack;if(page){await page.screenshot({path:join(evidence,'failure.png')}).catch(()=>{});report.lastFrame=await page.locator('#frame-trace').textContent().catch(()=>null);await writeFile(join(evidence,'failure.txt'),(await page.locator('body').innerText().catch(()=>''))+'\n'+error.stack);}throw error;}finally{await writeFile(join(evidence,'report.json'),JSON.stringify(report,null,2));await browser?.close();await daemon?.close();await rm(root,{recursive:true,force:true});}
