import {control} from './editor-controls.mjs';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {createM14Demos} from '../../demos/create-m14-projects.mjs';
import {startServer} from '../../daemon/bootstrap/server.mjs';
import {envelope} from '../../protocol/src/protocol.ts';
const root=await mkdtemp(join(tmpdir(),'axiom-m14-browser-')),evidence=resolve('.axiom/browser-m14-evidence');
await mkdir(evidence,{recursive:true});const report={criteria:[],samples:[],pageErrors:[],consoleErrors:[]};let daemon,browser,page;
try {
 const demos=await createM14Demos(root,{compile:true,requireScript:true,onProgress:console.log});
 daemon=await startServer({projectRoot:root});
 const command=async(type,data={})=>{const r=await fetch(daemon.origin+'/v1/commands',{method:'POST',headers:{Origin:daemon.origin,Authorization:'Bearer '+daemon.token,'Content-Type':'application/json'},body:JSON.stringify(envelope('command',{type,data}))});const v=await r.json();if(v.kind==='error')throw Error(JSON.stringify(v));return v.payload.data;};
 browser=await chromium.launch({headless:process.env.AXIOM_HEADLESS==='true',channel:'chromium',args:['--no-sandbox','--enable-gpu','--enable-unsafe-webgpu','--enable-unsafe-swiftshader','--enable-features=Vulkan','--use-angle=vulkan','--use-vulkan=swiftshader','--use-webgpu-adapter=swiftshader','--disable-vulkan-surface','--disable-dev-shm-usage']});
 async function next(renderer){if(page){await page.close();await new Promise(r=>setTimeout(r,5200));}page=await browser.newPage({viewport:{width:1700,height:1100}});page.setDefaultTimeout(60000);page.on('pageerror',e=>report.pageErrors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});page.on('dialog',d=>d.accept());const url=new URL(daemon.editorUrl);if(renderer)url.searchParams.set('renderer',renderer);await page.goto(url.href);await page.locator('#connection').filter({hasText:'Connected'}).waitFor();}
 async function ready(){await page.waitForFunction(()=>document.querySelector('#editor-workspace').getAttribute('aria-busy')==='false');const s=await command('scene.get'),end=Date.now()+15000;while(Date.now()<end){const status=(await command('runtime.status')).editor;if(status.connected&&status.projectId===s.project.id&&status.sceneRevision===s.sceneRevision)return s;await page.waitForTimeout(100);}throw Error('Renderer did not acknowledge project');}
 async function open(demo){await (await control(page,'#project-list')).selectOption(demo.id);await (await control(page,'#project-open')).click();return ready();}
 let s;const args=data=>({id:s.project.id,expectedSceneRevision:s.sceneRevision,...data});
 const test=data=>command('gameTest.control',args(data));
 async function until(status){const end=Date.now()+60000;while(Date.now()<end){const r=await test({action:'query'});if(status.includes(r.status))return r;await page.waitForTimeout(30);}throw Error('Test did not finish');}
 async function run(suite){await test({action:'run',suite});return until(['completed','failed','cancelled']);}
 await next();s=await open(demos[0]);await page.locator('#gpu-state').filter({hasText:'WebGPU active'}).waitFor();
 assert.deepEqual(await page.locator('.menubar > details > summary').allTextContents(),['File','Create','Panels','Config','Help']);
 assert.equal(await page.locator('[data-dock="bottom"] [data-panel]').first().getAttribute('data-panel'),'project');
 await page.locator('#help-menu > summary').click();assert.match(await page.locator('#help-menu').textContent(),/0\.0\.27/);await page.locator('#help-menu > summary').click();
 report.criteria.push('Default Project first; File/Create/Panels/Config/Help order and release version');
 const original=JSON.stringify((await command('scene.get')).project.scene);
 await test({action:'begin',suite:demos[0].suites[0]});let paused=await until(['paused']);assert.equal(paused.frames,0);await page.waitForTimeout(200);assert.equal((await test({action:'query'})).frames,0);
 await test({action:'step',step:demos[0].suites[0].steps[0]});paused=await until(['paused']);assert.equal(paused.frames,30);assert.equal(paused.results[0].passed,true);assert.ok(Math.abs(paused.results[0].actual[0]-1)<.01);await test({action:'finish'});assert.equal((await until(['completed','failed'])).status,'completed');assert.equal(JSON.stringify((await command('scene.get')).project.scene),original);
 report.criteria.push('Public begin pauses at frame zero; exact 30 real C# controlled frames move 1 unit; finish restores authored scene');
 const a=await run(demos[0].suites[0]),b=await run(demos[0].suites[0]);assert.equal(a.status,'completed');assert.deepEqual(a.results,b.results);report.samples.push(a,b);report.criteria.push('Repeated real C#/Wasm fixed-step suites produce identical results');
 const failed=await run(demos[0].suites[1]);assert.equal(failed.status,'failed');assert.equal(failed.results[0].passed,false);
 const visual=await run(demos[0].suites[2]);assert.equal(visual.status,'completed',JSON.stringify(visual));report.samples.push(visual);report.criteria.push('Known failing assertion is reported; real WebGPU pixel assertion passes');
 await test({action:'run',suite:{name:'Cancel active C# test',steps:[{frames:120,keys:['ArrowRight']},{frames:120},{frames:120},{frames:120},{frames:120}]}});await test({action:'cancel'});assert.equal((await until(['cancelled'])).status,'cancelled');assert.equal(JSON.stringify((await command('scene.get')).project.scene),original);report.criteria.push('Public cancellation releases runtime/input and preserves authored source');
 await (await control(page,'#game-test-source')).fill(JSON.stringify(demos[0].suites[0],null,2));await page.locator('#game-test-run').click();await page.locator('#game-test-status').filter({hasText:'completed'}).waitFor();await page.screenshot({path:join(evidence,'game-tests.png')});await page.locator('#settings-menu > summary').click();report.criteria.push('Human Game Tests UI runs the same saved suite and displays assertions');
 // The real Game canvas in a separate window shares the one runtime/lease with Scene.
 await (await control(page,'#scene-tab')).click();await page.locator('#viewport').focus();await page.keyboard.press('f');await page.waitForTimeout(100);await (await control(page,'#game-tab')).click();const event=page.waitForEvent('popup');await page.locator('[data-detach="game"]').click();const popup=await event;popup.on('pageerror',e=>report.pageErrors.push(e.message));await popup.locator('[data-parallel-view="game"]').waitFor({state:'visible'});await page.locator('#viewport').waitFor({state:'visible'});
 await (await control(page,'#play-start')).click();await ready();await popup.waitForFunction(()=>Number(document.querySelector('[data-parallel-view="game"]').dataset.frame)>20);
 const before=await popup.locator('[data-parallel-view="game"]').getAttribute('data-frame');await popup.locator('[data-parallel-view="game"]').focus();await popup.keyboard.down('ArrowRight');await popup.waitForTimeout(400);await popup.keyboard.up('ArrowRight');assert.ok(Number(await popup.locator('[data-parallel-view="game"]').getAttribute('data-frame'))>Number(before));
 const cameras=await Promise.all([page.locator('#viewport').getAttribute('data-camera'),popup.locator('[data-parallel-view="game"]').getAttribute('data-camera')]);assert.notEqual(cameras[0],cameras[1]);assert.equal((await command('runtime.status')).editor.connected,true);await page.screenshot({path:join(evidence,'parallel-scene.png')});await popup.screenshot({path:join(evidence,'parallel-game.png')});await (await control(page,'#play-stop')).click();await ready();await popup.close();await page.locator('#game-tab').click();await page.locator('#viewport').waitFor({state:'visible'});assert.equal(JSON.stringify((await command('scene.get')).project.scene),original);report.criteria.push('Scene and Game render independent cameras simultaneously; popup keyboard controls one shared simulation; closing restores Game');
 // Tab ordering, self-drop, close/reopen, project persistence.
 async function dragTab(id,target){const r=await page.locator('#'+id+'-tab').boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(r.x+r.width/2+20,r.y+r.height/2+8,{steps:5});await page.waitForFunction(()=>document.querySelector('#editor-workspace').classList.contains('dock-dragging'));const t=await page.locator('#'+target+'-tab').boundingBox();await page.mouse.move(t.x+Math.max(2,t.width/4),t.y+t.height/2,{steps:10});await page.mouse.up();await ready();}
 await dragTab('console','project');let order=(await command('scene.get')).project.editor.docks.order;assert.ok(order.indexOf('console')<order.indexOf('project'));await dragTab('console','console');assert.deepEqual((await command('scene.get')).project.editor.docks.order,order);
 await page.locator('#profiler-tab').click();await page.locator('[data-close="profiler"]').click();await ready();assert.equal(await page.locator('#profiler-tab').isHidden(),true);await page.locator('#panels-menu > summary').click();await page.locator('[data-open-panel="profiler"]').click();await ready();assert.equal(await page.locator('#profiler-tab').isVisible(),true);
 await page.reload();await page.locator('#connection').filter({hasText:'Connected'}).waitFor();s=await ready();assert.equal(await page.locator('[data-dock="bottom"] [data-panel]').first().getAttribute('data-panel'),'console');await (await control(page,'#dock-reset')).click();s=await ready();assert.equal(await page.locator('[data-dock="bottom"] [data-panel]').first().getAttribute('data-panel'),'project');report.criteria.push('Physical tab reorder, self-drop no-op, close/Panels reopen, persisted order and reset');
 // Save icon and shortcut use confirmed canonical dirty state, including form focus.
 await (await control(page,'#scene-add')).click();s=await ready();assert.equal(await page.locator('#save-dirty').isVisible(),true);await (await control(page,'#entity-name')).focus();await page.keyboard.press('Control+s');s=await ready();await page.locator('#save-dirty').waitFor({state:'hidden'});assert.equal(s.dirty,false);assert.equal(await page.locator('.menubar').evaluate(n=>n.previousElementSibling.id),'toolbar-save');report.criteria.push('Save icon precedes File; dirty asterisk and Ctrl+S work from Inspector');
 s=await open(demos[1]);const collision=await run(demos[1].suites[0]);assert.equal(collision.status,'completed',JSON.stringify(collision));report.samples.push(collision);report.criteria.push('Real Rust 3D collision assertions pass after exact 120 steps');
 await next('null');s=await ready();const nullVisual=await run(demos[1].suites[2]);assert.equal(nullVisual.status,'failed');assert.match(nullVisual.results[0].reason,/Null/);report.samples.push(nullVisual);report.criteria.push('Null renderer explicitly fails pixel assertions without fabricated screenshot');
 assert.deepEqual(report.pageErrors,[]);assert.deepEqual(report.consoleErrors,[]);report.passed=true;console.log('M14_BROWSER='+JSON.stringify(report));
} catch(error){report.error=error.stack;await page?.screenshot({path:join(evidence,'failure.png')}).catch(()=>{});if(page)await writeFile(join(evidence,'failure.txt'),await page.locator('body').innerText().catch(()=>''));throw error;} finally {await writeFile(join(evidence,'report.json'),JSON.stringify(report,null,2));await browser?.close();await daemon?.close();await rm(root,{recursive:true,force:true});}
