import {control} from './editor-controls.mjs';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {createM15Demos} from '../../demos/create-m15-projects.mjs';
import {startServer} from '../../daemon/bootstrap/server.mjs';
import {envelope} from '../../protocol/src/protocol.ts';
const root=await mkdtemp(join(tmpdir(),'axiom-m15-browser-')),evidence=resolve('.axiom/browser-m15-evidence');
await mkdir(evidence,{recursive:true});const report={criteria:[],samples:[],pageErrors:[],consoleErrors:[]};let daemon,browser,page;
try {
 const demos=await createM15Demos(root,{compile:true,requireScript:true,onProgress:console.log});
 daemon=await startServer({projectRoot:root});
 const command=async(type,data={})=>{const r=await fetch(daemon.origin+'/v1/commands',{method:'POST',headers:{Origin:daemon.origin,Authorization:'Bearer '+daemon.token,'Content-Type':'application/json'},body:JSON.stringify(envelope('command',{type,data}))});const v=await r.json();if(v.kind==='error')throw Error(JSON.stringify(v));return v.payload.data;};
 browser=await chromium.launch({headless:process.env.AXIOM_HEADLESS==='true',channel:'chromium',args:['--no-sandbox','--enable-gpu','--enable-unsafe-webgpu','--enable-unsafe-swiftshader','--enable-features=Vulkan','--use-angle=vulkan','--use-vulkan=swiftshader','--use-webgpu-adapter=swiftshader','--disable-vulkan-surface','--disable-dev-shm-usage']});
 async function next(renderer){if(page){await page.close();await new Promise(r=>setTimeout(r,5200));}page=await browser.newPage({viewport:{width:1700,height:1100}});page.setDefaultTimeout(60000);page.on('pageerror',e=>report.pageErrors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});page.on('dialog',d=>d.accept());const url=new URL(daemon.editorUrl);if(renderer)url.searchParams.set('renderer',renderer);await page.goto(url.href);await page.locator('#connection').filter({hasText:'Connected'}).waitFor();}
 async function ready(){await page.waitForFunction(()=>document.querySelector('#editor-workspace').getAttribute('aria-busy')==='false');const s=await command('scene.get'),end=Date.now()+15000;while(Date.now()<end){const status=(await command('runtime.status')).editor;if(status.connected&&status.projectId===s.project.id&&status.sceneRevision===s.sceneRevision)return s;await page.waitForTimeout(100);}throw Error('Renderer did not acknowledge project');}
 async function open(demo){await (await control(page,'#project-list')).selectOption(demo.id);await (await control(page,'#project-open')).click();return ready();}
 let s;const args=data=>({id:s.project.id,expectedSceneRevision:s.sceneRevision,...data});
 const test=data=>command('gameTest.control',args(data));
 async function until(status){const end=Date.now()+60000;while(Date.now()<end){const r=await test({action:'query'});if(status.includes(r.status))return r;if(['failed','cancelled','completed'].includes(r.status))throw Error('Unexpected test result: '+JSON.stringify(r));await page.waitForTimeout(30);}throw Error('Test did not finish');}
 async function run(suite){await test({action:'run',suite});return until(['completed','failed','cancelled']);}
 await next();s=await open(demos[0]);await page.locator('#gpu-state').filter({hasText:'WebGPU ·'}).waitFor();
 assert.deepEqual(await page.locator('.menubar > details > summary').allTextContents(),['File','Create','Panels','AI','Config','Help']);
 assert.deepEqual(await page.locator('#ai-menu > .menu-popup > details > summary').allTextContents(),['Connect AI model','Config AI assistant','Assisted Project Master Document Creation','Talk to AI assistant','AI proposal','Talk to AI master (advanced)']);report.criteria.push('AI menu contains the six requested options in order with truthful MCP/chat status');
 await (await control(page,'#project-master-file')).setInputFiles({name:'master-test.md',mimeType:'text/markdown',buffer:Buffer.from('# Uploaded master\nA seeded replay project')});await page.locator('#ai-operation-status').filter({hasText:'Project settings saved'}).waitFor();s=await ready();assert.equal((await command('scene.get')).project.editor.masterDocument.name,'master-test.md');await page.reload();await page.locator('#connection').filter({hasText:'Connected'}).waitFor();s=await ready();assert.equal((await command('scene.get')).project.editor.masterDocument.text,'# Uploaded master\nA seeded replay project');report.criteria.push('Config master document upload persists through project settings and reload');
 const source=JSON.stringify(s.project.scene);const replay=data=>command('replay.control',args(data));async function finish(){const end=Date.now()+60000;while(Date.now()<end){const r=await replay({action:'query'});if(['completed','failed','cancelled'].includes(r.status))return r;await page.waitForTimeout(50);}throw Error('Replay timed out');}
 await replay({action:'record',suite:demos[0].plan,seed:42});let r=await finish();assert.equal(r.status,'completed',JSON.stringify(r));assert.equal(r.frames,240);assert.deepEqual(r.recording.checkpoints,[0,60,120,180,240]);const exported=(await replay({action:'export'})).recording;assert.ok(Math.abs(exported.checkpoints[0].state.entities.find(e=>e.id===demos[0].playerId).transform.position[1]-.2523451747838408)<.000001);report.criteria.push('Actual C# ReplayRandom seed and 240 controlled inputs produce bounded state checkpoints');
 await replay({action:'replay',from:120,to:240,diagnostic:{kind:'whyScriptNotRunning',entityId:demos[0].playerId}});r=await finish();assert.equal(r.status,'completed',JSON.stringify(r));assert.equal(r.verifiedCheckpoints,5);assert.ok(r.diagnostics.length);assert.ok(r.diagnostics.every(d=>d.recordingId===exported.id&&d.evidence.status!=='unavailable'));report.samples.push(r);assert.equal(JSON.stringify((await command('scene.get')).project.scene),source);report.criteria.push('C# private lifecycle state reconstructs and verifies range checkpoints; diagnostics retain source recording identity; authored scene unchanged');
 await replay({action:'clear'});await replay({action:'import',recordingJson:JSON.stringify(exported)});await replay({action:'replay',from:60,to:120});assert.equal((await finish()).status,'completed');report.criteria.push('Export/import roundtrip reproduces a second range through public tools');
 await (await control(page,'#replay-source')).fill(JSON.stringify(demos[0].plan));await page.locator('#replay-record').click();await page.locator('#replay-status').filter({hasText:'completed'}).waitFor();await page.locator('#replay-from').fill('120');await page.locator('#replay-to').fill('240');await page.locator('#replay-diagnostic').selectOption('whyScriptNotRunning');await page.locator('#replay-run').click();await page.locator('#replay-status').filter({hasText:'completed'}).waitFor();await page.screenshot({path:join(evidence,'replay-controls.png')});await page.locator('#settings-menu > summary').click();report.criteria.push('Human record/range controls display actual checkpoint and diagnostic results');
 await replay({action:'record',suite:{name:'Cancel replay',steps:Array.from({length:5},()=>({frames:120,keys:['ArrowRight']}))},seed:42});await replay({action:'cancel'});assert.equal((await finish()).status,'cancelled');report.criteria.push('Cancellation releases C# runtime and input without publishing partial recording');
 s=await open(demos[1]);await replay({action:'record',suite:demos[1].plan,seed:7});assert.equal((await finish()).status,'completed');await replay({action:'replay',from:60,to:120,diagnostic:{kind:'whyNotColliding',entityId:demos[1].playerId,otherId:demos[1].floorId}});r=await finish();assert.equal(r.status,'completed',JSON.stringify(r));assert.ok(r.diagnostics.at(-1).evidence.nodes.some(n=>n.code==='AX_CAUSAL_0124'));report.samples.push(r);report.criteria.push('Real Wasm collision replay re-executes causal contact diagnostics');
 s=await open(demos[2]);await replay({action:'record',suite:demos[2].plan,seed:42});assert.equal((await finish()).status,'completed');await replay({action:'replay',from:60,to:120});assert.equal((await finish()).status,'completed');report.criteria.push('Real animator state/time checkpoints reproduce across range replay');
 // Human starter and entity-camera workflow, stopped Game and parallel view.
 await replay({action:'clear'});
 assert.equal(await page.locator('#file-menu').getByText('Game Camera',{exact:true}).count(),0);
 assert.equal(await page.locator('#create-menu').getByText('Primitives',{exact:true}).count(),0);
 await (await control(page,'#project-name')).fill('M15 editable camera');await (await control(page,'#project-dimension')).selectOption('3');await (await control(page,'#project-new')).click();s=await ready();assert.equal(s.project.scene.entities.length,3);assert.equal(s.playing,false);const cameraEntity=s.project.scene.entities.find(e=>e.camera);
 await page.locator('#entities .entity').filter({hasText:'Camera'}).click();await page.locator('#camera-component').waitFor({state:'visible'});assert.equal(await page.locator('#camera-component #camera-projection').count(),1);
 await (await control(page,'#game-tab')).click();await page.waitForFunction(id=>JSON.parse(document.querySelector('#viewport').dataset.camera).entityId===id,cameraEntity.id);const beforeCamera=await page.locator('#viewport').screenshot();
 await page.locator('#camera-projection').selectOption('orthographic');await page.locator('#camera-ortho').fill('10');await page.locator('#camera-form button[type="submit"]').click();s=await ready();await page.waitForFunction(()=>JSON.parse(document.querySelector('#viewport').dataset.camera).projection==='orthographic');assert.equal(s.playing,false);assert.ok(!beforeCamera.equals(await page.locator('#viewport').screenshot()));
 await page.locator('#position-0').fill('2');await page.locator('#rotation-1').fill('10');await page.locator('#entity-form button[type="submit"]').click();s=await ready();await page.waitForFunction(()=>JSON.parse(document.querySelector('#viewport').dataset.camera).position[0]===2);
 const popEvent=page.waitForEvent('popup');await page.locator('[data-detach="game"]').click();const cameraPopup=await popEvent;await cameraPopup.locator('[data-parallel-view="game"]').waitFor({state:'visible'});await cameraPopup.waitForFunction(id=>JSON.parse(document.querySelector('[data-parallel-view="game"]').dataset.camera??'{}').entityId===id,cameraEntity.id);assert.equal((await command('scene.get')).playing,false);await cameraPopup.close();await page.locator('#game-tab').click();await page.locator('#viewport').waitFor({state:'visible'});
 await page.locator('#camera-active').uncheck();await page.locator('#camera-form button[type="submit"]').click();s=await ready();await page.waitForFunction(()=>document.querySelector('#viewport').dataset.activeCamera==='none');await (await control(page,'#scene-undo')).click();s=await ready();await page.waitForFunction(id=>document.querySelector('#viewport').dataset.activeCamera===id,cameraEntity.id);
 await page.screenshot({path:join(evidence,'camera-inspector.png')});report.criteria.push('Human 3D starter, Camera Inspector projection and Transform, stopped Game, parallel Game and missing-camera Undo');
 await (await control(page,'#scene-save')).click();s=await ready();await (await control(page,'#project-name')).fill('M15 2D starter');await (await control(page,'#project-dimension')).selectOption('2');await (await control(page,'#project-new')).click();s=await ready();assert.equal(s.project.scene.entities.length,3);assert.ok(s.project.scene.entities.some(e=>e.light2D));assert.equal(s.project.scene.entities.find(e=>e.camera).camera.projection,'orthographic');report.criteria.push('Human 2D starter contains Camera + listener, Square sprite and explicit 2D light');
 s=await open(demos[2]);
 await next('null');s=await ready();await replay({action:'record',suite:demos[2].plan,seed:42});assert.equal((await finish()).status,'completed');await replay({action:'replay',from:60,to:120});assert.equal((await finish()).status,'completed');report.criteria.push('Null renderer repeats CPU/Wasm replay without invented pixels');
 assert.deepEqual(report.pageErrors,[]);assert.deepEqual(report.consoleErrors,[]);report.passed=true;

} catch(error){report.error=error.stack;await page?.screenshot({path:join(evidence,'failure.png')}).catch(()=>{});if(page)await writeFile(join(evidence,'failure.txt'),await page.locator('body').innerText().catch(()=>''));throw error;} finally {await writeFile(join(evidence,'report.json'),JSON.stringify(report,null,2));await browser?.close();await daemon?.close();await rm(root,{recursive:true,force:true});}
