import {control} from './editor-controls.mjs';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {createM17Projects} from '../../demos/create-m17-projects.mjs';import {startServer} from '../../daemon/bootstrap/server.mjs';import {envelope} from '../../protocol/src/protocol.ts';
const root=await mkdtemp(join(tmpdir(),'axiom-m17-')),evidence=resolve('.axiom/browser-m17-evidence'),report={criteria:[],errors:[]};await mkdir(evidence,{recursive:true});let daemon,browser,page;
try{
 const demos=await createM17Projects(root);daemon=await startServer({projectRoot:root});const command=async(type,data={})=>{const r=await fetch(daemon.origin+'/v1/commands',{method:'POST',headers:{Origin:daemon.origin,Authorization:'Bearer '+daemon.token,'Content-Type':'application/json'},body:JSON.stringify(envelope('command',{type,data}))});const v=await r.json();if(v.kind==='error')throw Error(JSON.stringify(v));return v.payload.data;};
 browser=await chromium.launch({headless:false,channel:'chromium',args:['--no-sandbox','--enable-gpu','--enable-unsafe-webgpu','--enable-unsafe-swiftshader','--enable-features=Vulkan','--use-angle=vulkan','--use-vulkan=swiftshader','--use-webgpu-adapter=swiftshader','--disable-vulkan-surface','--disable-dev-shm-usage']});page=await browser.newPage({viewport:{width:1700,height:1100}});page.setDefaultTimeout(180000);page.on('pageerror',e=>report.errors.push(e.message));page.on('dialog',d=>void d.accept());await page.goto(daemon.editorUrl);await page.locator('#connection').filter({hasText:'Connected'}).waitFor();const ready=()=>page.waitForFunction(()=>document.querySelector('#editor-workspace').getAttribute('aria-busy')==='false');const open=async d=>{await (await control(page,'#project-list')).selectOption(d.id);await (await control(page,'#project-open')).click();await ready();};
 await open(demos[0]);await (await control(page,'#game-tab')).click();await page.waitForFunction(()=>document.querySelector('#gpu-state').textContent.includes('WebGPU'));await page.screenshot({path:join(evidence,'cad.png')});const scene=(await command('scene.get')).project.scene;for(const ext of ['.step','.iges','.obj','.stl'])assert.ok(scene.assets.some(a=>a.name.endsWith(ext)));assert.equal(scene.entities.filter(e=>e.collider).length,3);assert.equal(scene.entities.find(e=>e.name.includes('LOD')).lod.levels.length,2);report.criteria.push('All four imported formats render in Game with generated collision and LOD components');
 for(const selector of ['#viewport','#scene-content canvas']){if(await page.locator(selector).isVisible()){await page.locator(selector).dispatchEvent('contextmenu',{bubbles:true});assert.equal(await page.locator('.editor-context').count(),0);}}await (await control(page,'#scene-tab')).click();await page.locator('#viewport').dispatchEvent('contextmenu',{bubbles:true});assert.equal(await page.locator('.editor-context').count(),0);report.criteria.push('Scene and Game right mouse do not open empty context menus');
 await open(demos[1]);const row=page.locator('#entities .entity').filter({hasText:'Cube'}).first();await row.click();await page.locator('#script-components .script-property').first().waitFor();assert.equal(await page.locator('#script-components .script-property').count(),2);const speed=page.locator('#script-components input[aria-label="Speed"]');await speed.fill('2.5');await speed.press('Tab');await ready();assert.equal((await command('scene.get')).project.scene.entities.find(e=>e.name==='Cube').scriptComponents[0].values.Speed,2.5);assert.equal(await page.locator('#script-components input[aria-label="Frames"]').isDisabled(),true);report.criteria.push('Physical Project scripts expose typed per-instance fields with readonly and layout attributes');
 await page.keyboard.press('Escape');await row.click();await page.waitForTimeout(750);assert.equal(await page.locator('#entities input').count(),0);report.criteria.push('Deselect/reselect clears delayed rename state');
 await page.locator('#script-components .script-source-link').first().click();await page.locator('#ide-code').waitFor();await page.locator('#ide-code').press('Control+End');await page.locator('#ide-code').press('Enter');await page.locator('#ide-code').pressSequentially('// pending first buffer');await page.locator('#script-components .script-source-link').nth(1).click();await page.locator('#ide-code').press('Control+End');await page.locator('#ide-code').press('Enter');await page.locator('#ide-code').pressSequentially('// pending second buffer');assert.equal(await page.locator('#ide-tabs .dirty').count(),2);await page.locator('#ide-code').press('Control+s');await ready();assert.equal(await page.locator('#ide-tabs .dirty').count(),1);await page.locator('#ide-save-all').click();await ready();assert.equal(await page.locator('#ide-tabs .dirty').count(),0);report.criteria.push('Multiple IDE buffers retain edits, Ctrl+S saves only the current script, Save All saves all');
 await page.locator('#ide-code').press('Control+f');await page.locator('#ide-find').fill('pending second buffer');await page.locator('#ide-replace').fill('saved replacement');await page.locator('#ide-replace-one').click();assert.ok((await page.locator('#ide-code').inputValue()).includes('saved replacement'));await page.locator('#ide-file-save').click();await ready();report.criteria.push('IDE scoped Find/Replace and save icon persist edited source');
 await (await control(page,'#play-start')).click();await page.waitForFunction(()=>{try{const d=JSON.parse(document.querySelector('#frame-trace').textContent);return d.script.active;}catch{return false;}});const authoring=(await command('scene.get')).project.scene;await page.locator('#entities .entity').filter({hasText:'Cube'}).first().click();await page.waitForFunction(()=>Number(document.querySelector('#script-components input[aria-label="Frames"]')?.value)>1);const a=JSON.parse(await page.locator('#frame-trace').textContent());await page.waitForTimeout(350);const b=JSON.parse(await page.locator('#frame-trace').textContent());assert.notDeepEqual(a.script.entities,b.script.entities);assert.deepEqual((await command('scene.get')).project.scene,authoring);report.criteria.push('Real .NET/Wasm compiles multiple classes, hydrates instance values and reports readonly fields without mutating authoring');await page.screenshot({path:join(evidence,'scripts.png')});await (await control(page,'#play-stop')).click();await ready();
 assert.deepEqual(report.errors,[]);report.passed=true;
}catch(error){report.error=error.stack;await page?.screenshot({path:join(evidence,'failure.png')}).catch(()=>{});throw error;}finally{await writeFile(join(evidence,'report.json'),JSON.stringify(report,null,2));console.log('M17_BROWSER='+JSON.stringify(report));await browser?.close();await daemon?.close();await rm(root,{recursive:true,force:true});}
