import {control} from './editor-controls.mjs';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';
import {createM18Projects} from '../../demos/create-m18-projects.mjs';
import {startServer} from '../../daemon/bootstrap/server.mjs';
import {envelope} from '../../protocol/src/protocol.ts';
const root=await mkdtemp(join(tmpdir(),'axiom-m18-')),evidence=resolve('.axiom/browser-m18-evidence'),report={criteria:[],errors:[],autonomy:[]};await mkdir(evidence,{recursive:true});let daemon,browser,page;
try{
 const demos=await createM18Projects(root);daemon=await startServer({projectRoot:root});
 const command=async(type,data={})=>{const response=await fetch(daemon.origin+'/v1/commands',{method:'POST',headers:{Origin:daemon.origin,Authorization:'Bearer '+daemon.token,'Content-Type':'application/json'},body:JSON.stringify(envelope('command',{type,data}))});const r=await response.json();if(r.kind==='error')throw Error(JSON.stringify(r));return r.payload.data;};
 browser=await chromium.launch({headless:false,channel:'chromium',args:['--no-sandbox','--enable-gpu','--enable-unsafe-webgpu','--enable-unsafe-swiftshader','--enable-features=Vulkan','--use-angle=vulkan','--use-vulkan=swiftshader','--use-webgpu-adapter=swiftshader','--disable-vulkan-surface','--disable-dev-shm-usage']});page=await browser.newPage({viewport:{width:1700,height:1100}});page.setDefaultTimeout(240000);page.on('pageerror',error=>report.errors.push(error.message));page.on('dialog',dialog=>void dialog.accept());await page.goto(daemon.editorUrl);await page.locator('#connection').filter({hasText:'Connected'}).waitFor();
 const ready=()=>page.waitForFunction(()=>document.querySelector('#editor-workspace').getAttribute('aria-busy')==='false');
 const open=async d=>{await (await control(page,'#project-list')).selectOption(d.id);await (await control(page,'#project-open')).click();await ready();};
 const state=()=>command('scene.get');const save=async()=>{if((await state()).dirty){await (await control(page,'#scene-save')).click();await ready();}};
 await open(demos[0]);await page.waitForFunction(()=>document.querySelector('#toolbar-compile').dataset.state==='compiled');assert.equal(await page.locator('#toolbar-compile').isDisabled(),true);assert.match(await page.locator('#project-title').textContent(),/^● /);report.criteria.push('Opening physical C# projects compiles automatically and shows Compiled with a disabled green check');
 await page.keyboard.press('Escape');assert.equal(await page.locator('#entity-form').isVisible(),false);assert.equal(await page.locator('#component-add').isVisible(),false);
 const cube=page.locator('#entities .entity').filter({hasText:'Cube'}).first();await cube.click();const speed=page.locator('#script-components input[aria-label="Speed"]');await speed.waitFor();const card=page.locator('#script-components .script-property').first();await card.locator('.component-fold').click();assert.equal(await speed.isVisible(),false);await card.locator('.component-fold').click();assert.equal(await speed.isVisible(),true);const label=card.locator('.numeric-label').filter({hasText:'Speed'});const box=await label.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+15,box.y+box.height/2,{steps:4});await page.mouse.up();await ready();assert.ok((await state()).project.scene.entities.find(e=>e.name.toLowerCase().includes('cube')).scriptComponents[0].values.Speed>1);report.criteria.push('Empty selection hides Transform/Add Component, component arrows fold, numeric labels scrub and scalar labels share one row');
 const inspectorPopup=page.waitForEvent('popup');await page.locator('[data-detach="inspector"]').click();const inspector=await inspectorPopup;const detachedSpeed=inspector.locator('#script-components input[aria-label="Speed"]');await detachedSpeed.waitFor();const previousSpeed=Number(await detachedSpeed.inputValue()),detachedLabel=inspector.locator('#script-components .numeric-label').filter({hasText:'Speed'}).first();await detachedLabel.scrollIntoViewIfNeeded();const detachedBox=await detachedLabel.boundingBox();await inspector.mouse.move(detachedBox.x+detachedBox.width/2,detachedBox.y+detachedBox.height/2);await inspector.mouse.down();await inspector.mouse.move(detachedBox.x+detachedBox.width/2+10,detachedBox.y+detachedBox.height/2,{steps:4});await inspector.mouse.up();await ready();await page.waitForFunction(()=>document.querySelector('#editor-workspace').getAttribute('aria-busy')==='false');let detachedValue;for(let attempt=0;attempt<40;attempt++){detachedValue=(await state()).project.scene.entities.find(e=>e.name.toLowerCase().includes('cube')).scriptComponents[0].values.Speed;if(detachedValue>previousSpeed)break;await page.waitForTimeout(50);}assert.ok(detachedValue>previousSpeed,JSON.stringify({previousSpeed,detachedValue,input:await detachedSpeed.inputValue(),disabled:await detachedSpeed.isDisabled()}));await inspector.getByRole('button',{name:'Return to editor'}).click();await page.waitForFunction(()=>!!document.querySelector('#script-components'));report.detachedInspector=true;
 await card.click({button:'right',position:{x:30,y:14}});await page.locator('.editor-context').getByRole('button',{name:'Show in Project',exact:true}).click();await ready();assert.equal(await page.locator('#entity-form').isVisible(),false);assert.equal(await page.locator('#component-add').isVisible(),false);assert.equal(await page.locator('#file-inspector').isVisible(),true);await cube.click();await card.locator('.script-source-link').click();assert.equal(await page.locator('#entity-form').isVisible(),true);await (await control(page,'#play-start')).click();await page.waitForFunction(()=>{try{return JSON.parse(document.querySelector('#frame-trace').textContent).script.active;}catch{return false;}});await cube.click();const authored=(await state()).project.scene;await speed.fill('0');await speed.press('Tab');await ready();await page.waitForTimeout(400);const a=JSON.parse(await page.locator('#frame-trace').textContent());await page.waitForTimeout(400);const b=JSON.parse(await page.locator('#frame-trace').textContent());const cubeId=authored.entities.find(e=>e.name.toLowerCase().includes('cube')).id;assert.deepEqual(a.script.entities.find(e=>e.id===cubeId),b.script.entities.find(e=>e.id===cubeId));assert.deepEqual((await state()).project.scene,authored);report.criteria.push('Inspector edits hydrate the running C# instance and affect gameplay immediately without changing authoring');
 await page.locator('#script-components .script-source-link').first().click();assert.equal(await page.locator('#ide-code').isDisabled(),false);await page.locator('#ide-code').press('Control+End');await page.locator('#ide-code').press('Enter');await page.locator('#ide-code').pressSequentially('// edited while running');await page.locator('#ide-code').press('Control+s');await ready();await page.waitForFunction(()=>document.querySelector('#toolbar-compile').dataset.state==='pending');assert.equal((await state()).playing,true);await page.waitForTimeout(300);const c=JSON.parse(await page.locator('#frame-trace').textContent());assert.equal(c.script.generation,b.script.generation);report.criteria.push('IDE remains editable/savable during Play, pending sources keep the old runtime until compilation');
 await (await control(page,'#play-stop')).click();await ready();assert.equal(await page.locator('#scene-content').isVisible(),true);report.criteria.push('Stop restores Scene focus and authored component values');
 await page.keyboard.press('Control+d');await page.waitForFunction(()=>document.querySelector('#toolbar-compile').dataset.state==='compiled');await ready();await save();
 await page.locator('#ide-tab').click();await page.locator('#ide-code').press('Control+End');await page.locator('#ide-code').pressSequentially('\nINVALID SOURCE');await page.locator('#ide-code').press('Control+s');await ready();await page.locator('#toolbar-compile').click();await page.waitForFunction(()=>document.querySelector('#toolbar-compile').dataset.state==='error');assert.equal(await page.locator('#toolbar-compile').isDisabled(),true);await page.locator('#ide-code').fill((await page.locator('#ide-code').inputValue()).replace('\nINVALID SOURCE',''));await page.locator('#compile-auto').check();await page.locator('#ide-code').press('Control+s');await page.waitForFunction(()=>document.querySelector('#toolbar-compile').dataset.state==='compiled');await ready();await save();assert.equal(await page.locator('#script-diagnostics').textContent(),'');report.criteria.push('Ctrl+D, compilation errors and saved-source Auto transitions share one compiler state and real diagnostics');await page.screenshot({path:join(evidence,'script-component-lab.png')});
 for(const demo of demos.slice(1)){
  await open(demo);if(demo.name.includes('Compiler'))await page.waitForFunction(()=>document.querySelector('#toolbar-compile').dataset.state==='error');await ready();
  const original=(await state()).project.scene;await page.locator('#ai-menu > summary').click();await page.locator('#ai-proposals > summary').click();await page.locator('#autonomy-run').waitFor();await page.waitForFunction(prefix=>document.querySelector('#autonomy-plans').selectedOptions[0]?.textContent.startsWith(prefix),demo.name.includes('Compiler')?'Repair the controller':'Place the target');const objective=JSON.parse(await page.locator('#autonomy-plan').inputValue()).objective;await page.locator('#autonomy-run').click();await page.waitForFunction(objective=>{try{const result=JSON.parse(document.querySelector('#autonomy-result').textContent);return result.objective===objective&&['completed','failed','cancelled'].includes(result.status);}catch{return false;}},objective,{timeout:600000});
  const result=JSON.parse(await page.locator('#autonomy-result').textContent());assert.equal(result.status,'completed',JSON.stringify(result));assert.equal(result.iteration,2);assert.ok(result.evidence.some(e=>e.passed===false));assert.ok(result.repairs.length);assert.equal(result.benchmark.samples,2);assert.ok(result.evidence.filter(e=>e.kind==='benchmark').every(e=>e.passed));assert.ok(result.changeSet.reviewHash);assert.equal((await state()).workspaceId??null,null);assert.deepEqual((await state()).project.scene,original);report.autonomy.push(result);await writeFile(join(evidence,demo.name.includes('Compiler')?'compiler-repair.json':'position-repair.json'),JSON.stringify(result,null,2));await page.screenshot({path:join(evidence,demo.name.includes('Compiler')?'compiler-repair.png':'position-repair.png')});
 }
 report.criteria.push('Real editor bridge runs isolated position and C# compiler failure → diagnosis → repair → fresh-world retest → two measured benchmark cycles');report.criteria.push('Autonomy preserves MAIN and returns a revision/hash bound change set for human review, with exportable immutable attempt evidence');assert.deepEqual(report.errors,[]);report.passed=true;
}catch(error){report.error=error.stack;report.commandError=await page?.locator('#project-error').textContent().catch(()=>null);report.compilerState=await page?.locator('#toolbar-compile').getAttribute('data-state').catch(()=>null);report.scriptDiagnostics=await page?.locator('#script-diagnostics').textContent().catch(()=>null);report.autonomyState=await page?.locator('#autonomy-result').textContent().catch(()=>null);await page?.screenshot({path:join(evidence,'failure.png')}).catch(()=>{});throw error;}finally{await writeFile(join(evidence,'report.json'),JSON.stringify(report,null,2));console.log('M18_BROWSER='+JSON.stringify(report));await browser?.close();await daemon?.close();await rm(root,{recursive:true,force:true});}
