import assert from 'node:assert/strict';
import {mkdtemp,mkdir,rm,readFile,readdir,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {chromium} from 'playwright';
import {PNG} from 'pngjs';
import {startServer} from '../../daemon/bootstrap/server.mjs';
import {mcpClient} from '../mcp-client.mjs';
import {imageFixture} from '../fixtures.mjs';
const root=await mkdtemp(join(tmpdir(),'axiom-m6-')),evidence=resolve('.axiom/browser-m6-evidence');await mkdir(evidence,{recursive:true});let daemon=await startServer({projectRoot:root}),client,browser,page;const report={criteria:[],pageErrors:[]};
try{
 client=await mcpClient(daemon);const call=async(name,args={})=>(await client.call(name,args)).structuredContent.payload.data;
 const source=await call('project.create',{name:'M6 protected source'}),id=source.project.id,path=join(root,id.slice(10)+'.json'),original=await readFile(path);
 await assert.rejects(client.call('scene.entity.create',{id,expectedSceneRevision:source.sceneRevision,name:'Forbidden direct edit'}),/AX_WORKSPACE_0001/);
 assert.equal((await client.request('tools/call',{name:'workspace.accept',arguments:{}})).error.code,-32602);
 browser=await chromium.launch({headless:false,channel:'chromium',args:['--no-sandbox','--enable-gpu','--enable-unsafe-webgpu','--enable-unsafe-swiftshader','--enable-features=Vulkan','--use-angle=vulkan','--use-vulkan=swiftshader','--use-webgpu-adapter=swiftshader','--disable-vulkan-surface','--disable-dev-shm-usage']});page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>report.pageErrors.push(e.message));page.setDefaultTimeout(30000);await page.goto(daemon.editorUrl);
 async function ready(workspaceId=null){const until=Date.now()+30000;while(Date.now()<until){const s=await call('runtime.status',workspaceId?{workspaceId}:{});if(s.editor.connected&&s.editor.renderer==='webgpu'&&s.editor.workspaceId===workspaceId&&s.editor.sceneRevision===s.sceneRevision)return s;await new Promise(r=>setTimeout(r,300));}throw Error('Preview failed to synchronize');}
 await ready();
 async function proposal(name){const main=await call('scene.query',{id});const w=await call('workspace.begin',{id,expectedSceneRevision:main.sceneRevision,name});const scope=async()=>({id,workspaceId:w.id,expectedSceneRevision:(await call('scene.query',{id,workspaceId:w.id})).sceneRevision});await call('asset.import',{...await scope(),name:'proposal.png',base64:imageFixture().toString('base64')});const asset=(await call('asset.query',await scope())).items[0];await call('scene.asset.place',{...await scope(),assetId:asset.id});return{w,scope};}
 const first=await proposal('Reject this isolated proposal');assert.equal((await call('scene.query',{id})).entityCount,0);assert.deepEqual(await readFile(path),original);assert.ok(!(await readdir(root)).some(p=>p.endsWith('.assets')));
 await call('workspace.preview',{workspaceId:first.w.id,expectedWorkspaceRevision:(await first.scope()).expectedSceneRevision});await ready(first.w.id);
 const capture=await client.call('renderer.capture',{...await first.scope(),width:640,height:360});const png=Buffer.from(capture.content.find(c=>c.type==='image').data,'base64');await writeFile(join(evidence,'proposal-capture.png'),png);assert.equal(PNG.sync.read(png).width,640);assert.equal(capture.structuredContent.payload.data.workspaceId,first.w.id);
 await page.locator('#proposal-list').selectOption(first.w.id);await page.locator('#proposal-review').click();await page.waitForFunction(()=>!document.querySelector('#proposal-accept').disabled);assert.match(await page.locator('#proposal-diff').textContent(),/entities/);await page.screenshot({path:join(evidence,'review.png')});await page.locator('#proposal-reject').click();await ready();assert.equal((await call('scene.query',{id})).entityCount,0);assert.deepEqual(await readFile(path),original);assert.deepEqual(await readdir(join(root,'.proposals')),[]);
 report.criteria.push('MCP cannot edit source or accept its own proposal','copy-on-write resources leave source files unchanged','human diff review and real proposal preview','reject removes overlay and restores source view');
 const second=await proposal('Accept this reviewed proposal');const entity=(await call('entity.query',await second.scope())).items[0];const job=(await call('script.compile',{...await second.scope(),source:'using Axiom.Gameplay; namespace Game; public sealed class GameScript : Script { public override void OnStart() { Log.Info("accepted proposal script"); } }',attachments:[entity.id]})).job;
 const until=Date.now()+180000;let status;do{status=(await call('script.job.get',{id,workspaceId:second.w.id,jobId:job.id})).job;if(['failed','cancelled'].includes(status.status))throw Error(JSON.stringify(status));if(status.status==='completed')break;await new Promise(r=>setTimeout(r,500));}while(Date.now()<until);assert.equal(status.status,'completed');
 await call('workspace.preview',{workspaceId:second.w.id,expectedWorkspaceRevision:(await second.scope()).expectedSceneRevision});await ready(second.w.id);await page.locator('#proposal-list').selectOption(second.w.id);await page.locator('#proposal-review').click();await page.waitForFunction(()=>!document.querySelector('#proposal-accept').disabled);await page.locator('#proposal-accept').click();await ready();const accepted=await call('scene.query',{id});assert.equal(accepted.entityCount,1);assert.equal(accepted.dirty,true);assert.deepEqual(await readFile(path),original);await page.locator('#scene-save').click();await page.waitForFunction(()=>document.querySelector('#project-status').textContent.includes('Saved'));assert.deepEqual(await readdir(join(root,'.proposals')),[]);
 report.criteria.push('human acceptance publishes one draft change set','proposal-only asset and C# bundle survive acceptance and explicit save');
 await page.close();await client.close();client=null;await daemon.close();daemon=await startServer({projectRoot:root});client=await mcpClient(daemon);await call('project.open',{id});page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>report.pageErrors.push(e.message));await page.goto(daemon.editorUrl);await ready();await page.locator('#play-start').click();await page.waitForFunction(()=>document.querySelector('#logs').textContent.includes('accepted proposal script'));await page.locator('#play-stop').click();await ready();assert.equal((await call('scene.query',{id})).entityCount,1);assert.deepEqual(report.pageErrors,[]);await page.screenshot({path:join(evidence,'accepted.png')});report.criteria.push('accepted project and compiled script reopen after daemon restart');report.passed=true;console.log('M6_BROWSER='+JSON.stringify(report));
}catch(error){report.failure=error.message;if(page&&!page.isClosed()){console.error(await page.locator('body').innerText());await page.screenshot({path:join(evidence,'failure.png')}).catch(()=>{});}throw error;}
finally{await writeFile(join(evidence,'report.json'),JSON.stringify(report,null,2));await client?.close();await browser?.close();await daemon.close();await rm(root,{recursive:true,force:true});}
