import assert from 'node:assert/strict';import {chromium} from 'playwright';import {mkdtemp,mkdir,rm,writeFile,readFile} from 'node:fs/promises';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';
import {createDemos} from '../../demos/create-projects.mjs';import {startServer} from '../../daemon/bootstrap/server.mjs';import {envelope} from '../../protocol/src/protocol.ts';
const root=await mkdtemp(join(tmpdir(),'axiom-m7-')),evidence=resolve('.axiom/browser-m7-evidence');await mkdir(evidence,{recursive:true});let daemon,browser,page;const report={criteria:[],pageErrors:[]};
try{
 const demos=await createDemos(root);daemon=await startServer({projectRoot:root});
 const command=async(type,data={})=>{const r=await fetch(daemon.origin+'/v1/commands',{method:'POST',headers:{Origin:daemon.origin,Authorization:'Bearer '+daemon.token,'Content-Type':'application/json'},body:JSON.stringify(envelope('command',{type,data}))});const value=await r.json();if(value.kind==='error')throw Error(JSON.stringify(value));return value.payload.data;};
 browser=await chromium.launch({headless:false,channel:'chromium',args:['--no-sandbox','--enable-gpu','--enable-unsafe-webgpu','--enable-unsafe-swiftshader','--enable-features=Vulkan','--use-angle=vulkan','--use-vulkan=swiftshader','--use-webgpu-adapter=swiftshader','--disable-vulkan-surface','--disable-dev-shm-usage']});page=await browser.newPage({viewport:{width:1600,height:1000}});page.on('pageerror',e=>report.pageErrors.push(e.message));page.setDefaultTimeout(45000);await page.goto(daemon.editorUrl);
 await page.locator('#project-list').selectOption(demos[0].id);await page.locator('#project-open').click();await page.waitForFunction(()=>document.querySelectorAll('#entities button').length===7);await page.locator('#entities button').filter({hasText:'Player ·'}).click();await page.waitForFunction(()=>document.querySelector('#physics-motion').value==='dynamic');
 const authoring=(await command('scene.get')).project.scene,original=await readFile(join(root,demos[0].id.slice(10)+'.json'));
 await page.locator('#play-start').click();await page.waitForFunction(()=>{try{const d=JSON.parse(document.querySelector('#frame-trace').textContent);return d.physics.steps>90&&d.script.active;}catch{return false;}});
 const before=JSON.parse(await page.locator('#frame-trace').textContent()).physics.bodies.find(b=>b.id===demos[0].playerId);assert.ok(before.position[1]<authoring.entities.find(e=>e.id===before.id).transform.position[1]);
 await page.locator('#viewport').click();await page.keyboard.down('ArrowRight');await page.waitForFunction(({id,x})=>JSON.parse(document.querySelector('#frame-trace').textContent).physics.bodies.find(b=>b.id===id).position[0]>x+.3,{id:before.id,x:before.position[0]});await page.keyboard.up('ArrowRight');await page.keyboard.down('Space');await page.waitForFunction(id=>JSON.parse(document.querySelector('#frame-trace').textContent).physics.bodies.find(b=>b.id===id).velocity[1]>1,before.id);await page.keyboard.up('Space');
 await page.screenshot({path:join(evidence,'playground-2d.png')});assert.deepEqual((await command('scene.get')).project.scene,authoring);assert.deepEqual(await readFile(join(root,demos[0].id.slice(10)+'.json')),original);
 await page.locator('#play-stop').click();await page.waitForFunction(()=>document.querySelector('#play-stop').disabled);assert.deepEqual((await command('scene.get')).project.scene,authoring);
 report.criteria.push('demo creation and actual C# compilation','physics Inspector reflects authored components','2D gravity and contacts in real Wasm/WebGPU','C# velocity controls and jump','Play/Stop preserves authoring and saved bytes');
 await page.locator('#project-list').selectOption(demos[1].id);await page.locator('#project-open').click();await page.waitForFunction(()=>document.querySelector('#project-status').textContent.includes('3D Falling'));await page.locator('#play-start').click();await page.waitForFunction(()=>{try{return JSON.parse(document.querySelector('#frame-trace').textContent).physics.steps>180;}catch{return false;}});const physical=JSON.parse(await page.locator('#frame-trace').textContent()).physics;assert.equal(physical.bodies.length,7);assert.ok(physical.contacts.length>0);await page.screenshot({path:join(evidence,'falling-blocks-3d.png')});report.criteria.push('3D imported mesh bodies settle against static foundation');
 await page.locator('#play-stop').click();await page.waitForFunction(()=>document.querySelector('#play-stop').disabled);await page.goto(daemon.editorUrl.replace('/#','/?renderer=null#'));await page.locator('#play-start').click();await page.waitForFunction(()=>{try{const d=JSON.parse(document.querySelector('#frame-trace').textContent);return d.physics.steps>60&&d.kernel.renderer==='null';}catch{return false;}});report.criteria.push('Null renderer runs the same physics');assert.deepEqual(report.pageErrors,[]);report.passed=true;console.log('M7_BROWSER='+JSON.stringify(report));
}catch(error){report.failure=error.message;if(page){console.error(await page.locator('body').innerText());await page.screenshot({path:join(evidence,'failure.png')}).catch(()=>{});}throw error;}finally{await writeFile(join(evidence,'report.json'),JSON.stringify(report,null,2));await browser?.close();await daemon?.close();await rm(root,{recursive:true,force:true});}
