import assert from 'node:assert/strict';import {chromium} from 'playwright';import {mkdtemp,mkdir,rm,writeFile} from 'node:fs/promises';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';
import {createM8Demos} from '../../demos/create-m8-projects.mjs';import {startServer} from '../../daemon/bootstrap/server.mjs';import {envelope} from '../../protocol/src/protocol.ts';
const root=await mkdtemp(join(tmpdir(),'axiom-m8-')),evidence=resolve('.axiom/browser-m8-evidence');await mkdir(evidence,{recursive:true});let daemon,browser,page;const report={criteria:[],pageErrors:[]};
try{
 const demos=await createM8Demos(root);assert.equal(demos.length,2);daemon=await startServer({projectRoot:root});
 const command=async(type,data={})=>{const r=await fetch(daemon.origin+'/v1/commands',{method:'POST',headers:{Origin:daemon.origin,Authorization:'Bearer '+daemon.token,'Content-Type':'application/json'},body:JSON.stringify(envelope('command',{type,data}))});const value=await r.json();if(value.kind==='error')throw Error(JSON.stringify(value));return value.payload.data;};
 browser=await chromium.launch({headless:process.env.AXIOM_HEADLESS==='true',channel:'chromium',args:['--no-sandbox','--enable-gpu','--enable-unsafe-webgpu','--enable-unsafe-swiftshader','--enable-features=Vulkan','--use-angle=vulkan','--use-vulkan=swiftshader','--use-webgpu-adapter=swiftshader','--disable-vulkan-surface','--disable-dev-shm-usage']});page=await browser.newPage({viewport:{width:1700,height:1100}});page.on('pageerror',e=>report.pageErrors.push(e.message));page.on('dialog',dialog=>dialog.accept());page.setDefaultTimeout(45000);console.log('M8: opening editor');await page.goto(daemon.editorUrl);
 const open=async id=>{await page.locator('#project-list').selectOption(id);await page.locator('#project-open').click();await page.waitForFunction(id=>document.querySelector('#project-status').textContent.includes(id),id===demos[0].id?'Scene Workshop':'Diagnostic Lab');await page.waitForFunction(()=>document.querySelector('#frame-trace').textContent.includes('"frameSequence"'));};
 console.log('M8: opening Scene Workshop');await open(demos[0].id);const original=(await command('scene.get')).project.scene;
 await page.locator('#game-tab').click();assert.equal((await command('scene.get')).playing,false);await page.waitForFunction(()=>JSON.parse(document.querySelector('#frame-trace').textContent).kernel.view==='game');console.log('M8: stopped Game frame ready');const gameImage=await page.locator('#viewport').screenshot();
 await page.locator('#scene-tab').click();await page.waitForFunction(()=>document.querySelector('#scene-overlay').hidden===false);
 const rect=await page.locator('#viewport').boundingBox();await page.keyboard.down('Alt');await page.mouse.move(rect.x+rect.width*.8,rect.y+rect.height*.75);await page.mouse.down();await page.mouse.move(rect.x+rect.width*.8+65,rect.y+rect.height*.75+20,{steps:6});await page.mouse.up();await page.keyboard.up('Alt');
 await page.mouse.move(rect.x+rect.width*.8,rect.y+rect.height*.75);await page.mouse.down({button:'right'});await page.keyboard.down('w');await page.waitForTimeout(250);await page.keyboard.up('w');await page.mouse.move(rect.x+rect.width*.8+20,rect.y+rect.height*.75+10);await page.mouse.up({button:'right'});await page.mouse.wheel(0,120);assert.deepEqual((await command('scene.get')).project.scene,original);await page.locator('#game-tab').click();await page.waitForFunction(()=>JSON.parse(document.querySelector('#frame-trace').textContent).kernel.view==='game');assert.deepEqual(await page.locator('#viewport').screenshot(),gameImage);report.criteria.push('stopped Game preview and independent Scene navigation preserve game camera');
 await page.locator('#scene-tab').click();await page.locator('#entities button').filter({hasText:'Move me'}).click();const first=original.entities[0];await page.waitForFunction(id=>document.querySelector('#scene-overlay [data-selection]')?.getAttribute('data-selection')===id,first.id);
 // Frame the selected object and click its projected center to test picking.
 await page.locator('#viewport').focus();await page.keyboard.press('f');await page.waitForTimeout(150);const outline=await page.locator('#scene-overlay [data-selection]').boundingBox();await page.mouse.click(outline.x+outline.width*.45,outline.y+outline.height*.55);assert.equal(await page.locator('#entity-name').inputValue(),first.name);
 async function dragHandle(tool,selector,dx,dy){await page.locator('#tool-'+tool).click();await page.waitForTimeout(100);const handle=page.locator(selector).first();let p;
  if(tool==='rotate'){p=await handle.evaluate(el=>{const coords=el.getAttribute('points').split(' ')[10].split(',').map(Number),svg=el.ownerSVGElement,rect=svg.getBoundingClientRect();return {x:rect.x+coords[0]*rect.width/960,y:rect.y+coords[1]*rect.height/540};});}
  else{const b=await handle.boundingBox();p={x:b.x+b.width/2,y:b.y+b.height/2};}
  await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(p.x+dx,p.y+dy,{steps:8});await page.mouse.up();await page.waitForTimeout(200);
 }
 console.log('M8: selecting and moving');await dragHandle('move','#scene-overlay circle[data-handle="0"]',35,0);let moved=(await command('scene.get')).project.scene.entities[0].transform;assert.notDeepEqual(moved.position,first.transform.position);await page.locator('#scene-undo').click();await page.waitForTimeout(150);assert.deepEqual((await command('scene.get')).project.scene.entities[0].transform,first.transform);report.criteria.push('bidirectional selection, triangle picking and one-drag Undo');
 await dragHandle('rotate','#scene-overlay polyline[data-handle="2"]',25,20);assert.notDeepEqual((await command('scene.get')).project.scene.entities[0].transform.rotation,first.transform.rotation);await page.locator('#scene-undo').click();await page.waitForTimeout(150);
 await dragHandle('scale','#scene-overlay rect[data-handle="all"]',25,-15);assert.notDeepEqual((await command('scene.get')).project.scene.entities[0].transform.scale,first.transform.scale);await page.locator('#scene-undo').click();await page.waitForTimeout(150);
 await page.locator('#tool-move').click();await page.waitForTimeout(100);const handle=await page.locator('#scene-overlay circle[data-handle="0"]').boundingBox();await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2);await page.mouse.down();await page.mouse.move(handle.x+50,handle.y);await page.keyboard.press('Escape');await page.mouse.up();assert.deepEqual((await command('scene.get')).project.scene,original);report.criteria.push('rotation/scale gizmos and Escape discard transient preview');
 await page.locator('#orientation-widget circle[data-axis="1"][data-sign="1"]').click();await page.waitForTimeout(150);await page.locator('#tool-projection').click();assert.equal(await page.locator('#tool-projection').textContent(),'Ortho');await page.screenshot({path:join(evidence,'scene-tools.png')});report.criteria.push('axis alignment and projection switch');
 console.log('M8: opening Diagnostic Lab');await open(demos[1].id);await page.locator('#diagnostics-tab').click();await page.locator('#entities button').filter({hasText:'Invisible ·'}).click();await page.locator('#diagnostic-explain').click();await page.waitForFunction(()=>document.querySelector('#decision-graph').textContent.includes('AX_CAUSAL_0106'));
 await page.locator('#entities button').filter({hasText:'Outside camera'}).click();await page.locator('#diagnostic-explain').click();await page.waitForFunction(()=>document.querySelector('#decision-graph').textContent.includes('AX_CAUSAL_0110'));
 await page.locator('#diagnostic-kind').selectOption('whyNotColliding');const lab=(await command('scene.get')).project;const partner=lab.scene.entities.find(e=>e.name==='Overlap partner');await page.locator('#diagnostic-other').selectOption(partner.id);await page.locator('#entities button').filter({hasText:'Mask 0'}).click();await page.locator('#play-start').click();await page.waitForFunction(()=>JSON.parse(document.querySelector('#frame-trace').textContent).physics.steps>30);await page.locator('#diagnostic-explain').click();await page.waitForFunction(()=>document.querySelector('#decision-graph').textContent.includes('AX_CAUSAL_0121'));
 const s=await command('scene.get');const explained=await command('diagnostics.explain',{id:lab.id,expectedSceneRevision:s.sceneRevision,kind:'whyNotColliding',entityId:lab.scene.entities.find(e=>e.name.startsWith('Mask 0')).id,otherId:partner.id});assert.equal(explained.code,'AX_CAUSAL_0121');assert.ok(explained.correlationId);await page.screenshot({path:join(evidence,'diagnostic-lab.png')});report.criteria.push('visible Diagnostics tab with causal graph and real bridge/API evidence');
 await page.locator('#deep-trace').check();await page.waitForTimeout(600);await page.locator('#diagnostic-kind').selectOption('whyScriptNotRunning');await page.locator('#diagnostic-explain').click();const stored=JSON.parse(await page.locator('#decision-graph').textContent);await page.locator('#diagnostic-trace').fill(stored.traceId);await page.locator('#diagnostic-explain').click();assert.notEqual(JSON.parse(await page.locator('#decision-graph').textContent).status,'unavailable');await page.locator('#play-stop').click();report.criteria.push('opt-in retained frame trace lookup');
 assert.deepEqual(report.pageErrors,[]);report.passed=true;console.log('M8_BROWSER='+JSON.stringify(report));
}catch(error){report.failure=error.message;if(page){console.error(await page.locator('body').innerText());await page.screenshot({path:join(evidence,'failure.png'),timeout:10000}).catch(()=>{});}throw error;}finally{await writeFile(join(evidence,'report.json'),JSON.stringify(report,null,2));await browser?.close();await daemon?.close();await rm(root,{recursive:true,force:true});}
