import {control} from './editor-controls.mjs';
import assert from 'node:assert/strict';import {chromium} from 'playwright';import {PNG} from 'pngjs';import {mkdtemp,mkdir,rm,writeFile} from 'node:fs/promises';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';
import {createM9Demos} from '../../demos/create-m9-projects.mjs';import {startServer} from '../../daemon/bootstrap/server.mjs';import {envelope} from '../../protocol/src/protocol.ts';
const root=await mkdtemp(join(tmpdir(),'axiom-m9-')),evidence=resolve('.axiom/browser-m9-evidence');await mkdir(evidence,{recursive:true});let daemon,browser,page;const report={criteria:[],pageErrors:[],consoleErrors:[],samples:[],httpErrors:[]};
function difference(a,b){const A=PNG.sync.read(a),B=PNG.sync.read(b);let sum=0,changed=0;for(let i=0;i<A.data.length;i+=4){let d=0;for(let j=0;j<3;j++)d+=Math.abs(A.data[i+j]-B.data[i+j]);sum+=d;if(d>6)changed++;}return {mean:sum/(A.width*A.height*3),changed};}
try{
 const demos=await createM9Demos(root);daemon=await startServer({projectRoot:root});
 const command=async(type,data={})=>{const r=await fetch(daemon.origin+'/v1/commands',{method:'POST',headers:{Origin:daemon.origin,Authorization:'Bearer '+daemon.token,'Content-Type':'application/json'},body:JSON.stringify(envelope('command',{type,data}))});const v=await r.json();if(v.kind==='error')throw Error(JSON.stringify(v));return v.payload.data;};
 browser=await chromium.launch({headless:process.env.AXIOM_HEADLESS==='true',channel:'chromium',args:['--no-sandbox','--enable-gpu','--enable-unsafe-webgpu','--enable-unsafe-swiftshader','--enable-features=Vulkan','--use-angle=vulkan','--use-vulkan=swiftshader','--use-webgpu-adapter=swiftshader','--disable-vulkan-surface','--disable-dev-shm-usage']});
 page=await browser.newPage({viewport:{width:1700,height:1100}});page.on('pageerror',e=>report.pageErrors.push(e.message));page.on('response',r=>{if(r.status()>=400&&report.httpErrors.length<16)report.httpErrors.push({status:r.status(),path:new URL(r.url()).pathname});});page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});page.on('dialog',d=>d.accept());page.setDefaultTimeout(60000);await page.goto(daemon.editorUrl);
 const trace=()=>page.locator('#frame-trace').textContent().then(JSON.parse);
 async function ready(){await page.waitForFunction(()=>{try{const f=JSON.parse(document.querySelector('#frame-trace').textContent);return f.rendering&&f.kernel.renderer==='webgpu'&&f.kernel.view==='game';}catch{return false;}});await page.waitForTimeout(200);}
 async function open(id){await (await control(page,'#project-list')).selectOption(id);await (await control(page,'#project-open')).click();await (await control(page,'#game-tab')).click();await ready();}
 async function setting(patch){const s=await command('scene.get');await command('scene.rendering.update',{id:s.project.id,expectedSceneRevision:s.sceneRevision,value:{...s.project.scene.rendering,...patch}});await (await control(page,'#workspace-refresh')).click();await ready();await page.waitForFunction(patch=>{try{const r=JSON.parse(document.querySelector('#frame-trace').textContent).rendering;return (!patch.culling||r.culling===patch.culling)&&(!patch.tier||r.lighting===(patch.tier==='low'?'forward':'forward+'));}catch{return false;}},patch);}
 async function image(name){const value=await page.locator('#viewport').screenshot();await writeFile(join(evidence,name+'.png'),value);return value;}
 console.log('M9: PBR gallery');await open(demos[0].id);let f=await trace();assert.equal(f.rendering.hdrFormat,'rgba16float');assert.equal(f.rendering.pipelines,8);assert.equal(f.rendering.lights,3);assert.equal((await command('scene.get')).playing,false);const initial=await image('gallery-hdr');const px=PNG.sync.read(initial);let colorful=0;for(let i=0;i<px.data.length;i+=4)if(Math.max(...px.data.slice(i,i+3))-Math.min(...px.data.slice(i,i+3))>30)colorful++;assert.ok(colorful>10000,'PBR gallery must draw colored geometry');report.criteria.push('PBR GGX, three light kinds, HDR and stopped Game preview draw real geometry');
 await setting({culling:'cpu'});const cpu=await image('gallery-cpu');await setting({culling:'gpu'});const gpu=await image('gallery-gpu');assert.equal(difference(cpu,gpu).changed,0,'CPU and GPU admission goldens differ');report.criteria.push('CPU and actual compute/indirect GPU culling produce identical golden pixels');
 await setting({bloom:0});const noBloom=await image('gallery-no-bloom');assert.ok(difference(gpu,noBloom).changed>100,'Bloom must affect rendered pixels');await setting({bloom:.15,toneMapping:'reinhard'});const reinhard=await image('gallery-reinhard');assert.ok(difference(gpu,reinhard).changed>10000,'Tone mapping must change HDR output');await setting({toneMapping:'aces',shadows:false});const noShadow=await image('gallery-no-shadow');assert.ok(difference(gpu,noShadow).changed>100,'Shadow map must affect visible receivers');report.criteria.push('bloom, tone mapping and directional PCF shadows have observed pixel effects');
 const s=await command('scene.get'),point=s.project.scene.entities.find(e=>e.light?.kind==='point');await command('scene.light.set',{id:s.project.id,expectedSceneRevision:s.sceneRevision,entityId:point.id,value:{...point.light,intensity:0}});await (await control(page,'#workspace-refresh')).click();await ready();assert.ok(difference(noShadow,await image('gallery-point-off')).changed>100,'Point lighting must affect visible pixels');await (await control(page,'#scene-undo')).click();await ready();
 await page.locator('#entities .entity').filter({hasText:'Material · metallic 0 · roughness 0.2'}).click();await page.locator('summary').filter({hasText:'PBR Material'}).click();await (await control(page,'#material-metallic')).fill('1');await page.locator('#material-form button[type="submit"]').click();await ready();assert.equal((await command('scene.get')).project.scene.entities.find(e=>e.name==='Material · metallic 0 · roughness 0.2').material.metallic,1);await (await control(page,'#scene-undo')).click();await ready();report.criteria.push('human material Inspector and Undo use canonical authoring commands');
 await (await control(page,'#scene-save')).click();await ready();await page.screenshot({path:join(evidence,'gallery-editor.png')});
 console.log('M9: instancing and LOD');await open(demos[1].id);await page.waitForFunction(()=>{try{return JSON.parse(document.querySelector('#frame-trace').textContent).rendering.gpuSample?.instances>0;}catch{return false;}});f=await trace();assert.ok(f.rendering.instances>=145);assert.ok(f.rendering.batches<=3);assert.ok(f.rendering.culled>=24);assert.equal(f.rendering.lodInstances,1);assert.equal(f.rendering.gpuSample.instances,f.rendering.cpuVisible);assert.ok(f.rendering.vertexBytes<150000);report.samples.push(f.rendering);const lab=await image('instancing-lod');await setting({culling:'cpu'});assert.equal(difference(lab,await image('instancing-cpu')).changed,0);await setting({tier:'low',culling:'gpu',bloom:.5});f=await trace();assert.equal(f.rendering.lighting,'forward');assert.ok(f.rendering.fallbacks.some(v=>v.includes('Bloom')));report.criteria.push('145 instances batch into at most three draws, actual GPU readback agrees, authored LOD and low-tier fallback operate');
 await (await control(page,'#diagnostics-tab')).click();await page.locator('#entities .entity').filter({hasText:'Shared cube 144'}).click();await (await control(page,'#diagnostic-explain')).click();await page.waitForFunction(()=>document.querySelector('#decision-graph').textContent.includes('AX_CAUSAL_0140'));assert.ok((await page.locator('#decision-graph').textContent()).includes('AX_CAUSAL_0110'));report.criteria.push('production culling reference appears in bounded causal graph');
 await page.screenshot({path:join(evidence,'lab-editor.png')});await page.close();page=await browser.newPage({viewport:{width:1700,height:1100}});page.on('pageerror',e=>report.pageErrors.push(e.message));await page.goto(daemon.editorUrl.replace('#','?renderer=null#'));await page.waitForFunction(()=>{try{const r=JSON.parse(document.querySelector('#frame-trace').textContent);return r.kernel.renderer==='null'&&r.rendering;}catch{return false;}});f=await trace();assert.equal(f.rendering.gpuSample,null);assert.equal(f.rendering.submittedReference,0);assert.equal(f.rendering.pixels,'unavailable');await page.screenshot({path:join(evidence,'null-renderer.png')});report.criteria.push('Null retains rendering decisions with zero submissions and no invented GPU/pixel evidence');
 assert.deepEqual(report.pageErrors,[]);assert.deepEqual(report.consoleErrors,[]);assert.deepEqual(report.httpErrors,[]);report.passed=true;console.log('M9_BROWSER='+JSON.stringify(report));
}catch(error){report.failure=error.message;if(page){console.error(await page.locator('body').innerText().catch(()=>''));await page.screenshot({path:join(evidence,'failure.png'),timeout:10000}).catch(()=>{});}throw error;}finally{await writeFile(join(evidence,'report.json'),JSON.stringify(report,null,2));await browser?.close();await daemon?.close();await rm(root,{recursive:true,force:true});}
