import {projectFiles,projectPath} from '../scene/project-files.mjs';
const fail=message=>{throw Object.assign(Error(message),{code:'AX_SCRIPT_0001'});};
const vectorSizes={Vec3:3,Vector2:2,Vector3:3,Vector4:4,Vector2Int:2,Vector3Int:3,Vector4Int:4,Quaternion:4,Quat:4,Color:4,Color32:4,Rect:4,Bounds:6};
const numberTypes=['int','uint','float','double','long','short','byte'];
function stripComments(source){return source.replace(/"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|\/\*[\s\S]*?\*\/|\/\/[^\n]*/g,token=>token.startsWith('/')?token.replace(/[^\n]/g,' '):token);}
function members(text,start){const open=text.indexOf('{',start);let depth=0,result='',quoted=false,escaped=false;for(let i=open;i<text.length;i++){const c=text[i];if(quoted){if(depth===1)result+=c;if(!escaped&&c==='"')quoted=false;escaped=!escaped&&c==='\\';continue;}if(c==='"'){quoted=true;if(depth===1)result+=c;continue;}if(c==='{'){depth++;if(depth===2)result+=';';continue;}if(c==='}'){if(--depth===0)break;continue;}if(depth===1)result+=c;}return result;}
// Inspector metadata is bounded declarative authoring data. The C# compiler remains
// authoritative about executable code. Unsupported complex members stay in IDE.
export function scriptMetadata(file){if(file.kind!=='script'||typeof file.text!=='string')fail('Select a Project C# source');const text=stripComments(file.text),entry=text.match(/\b(?:public\s+)?(?:sealed\s+|partial\s+)?class\s+([A-Za-z_]\w*)\s*:\s*(?:Axiom\.Gameplay\.)?(?:Script|MonoBehaviour)\b/);if(!entry)return null;const namespace=text.match(/\bnamespace\s+([\w.]+)\s*[;{]/)?.[1]??'',enums={};for(const m of text.matchAll(/\benum\s+(\w+)\s*{([^}]+)}/g)){let n=-1;const options=[];for(const token of m[2].split(',')){const match=token.trim().match(/^(\w+)(?:\s*=\s*(-?\d+))?$/);if(!match)continue;n=match[2]===undefined?n+1:Number(match[2]);options.push({name:match[1],value:n});}enums[m[1]]=options;}
 const fields=[];const pattern=/((?:\s*\[[^\]\n]+\]\s*)*)(public|private|protected|internal)\s+(readonly\s+)?(\w+)\s+(\w+)\s*(?:=\s*([^;]+))?;/g;for(const m of members(text,entry.index).matchAll(pattern)){const [_,attrs,access,readonly,type,name,initializer]=m;if(access!=='public'&&!/\bSerializeField\b/.test(attrs)||/\bHideInInspector\b/.test(attrs)||!['bool','string',...numberTypes,...Object.keys(vectorSizes),...Object.keys(enums)].includes(type))continue;if(fields.length>=64)fail('Inspector field budget is 64');const field={name,type,readOnly:!!readonly||/\bReadOnly\b/.test(attrs),title:attrs.match(/(?:Title|Header)\s*\(\s*"([^"]*)"\s*\)/)?.[1]?.slice(0,128)??null,tooltip:attrs.match(/Tooltip\s*\(\s*"([^"]*)"\s*\)/)?.[1]?.slice(0,512)??null,space:/\bSpace\b/.test(attrs)?Math.min(64,Number(attrs.match(/Space\s*\(\s*(\d+)/)?.[1]??8)):0};const range=attrs.match(/Range\s*\(\s*([-+.\d]+)[fFdD]?\s*,\s*([-+.\d]+)[fFdD]?\s*\)/);if(range){field.minimum=Number(range[1]);field.maximum=Number(range[2]);if(field.minimum>field.maximum)fail('Inspector range is reversed');}
 if(enums[type]){field.options=enums[type];field.default=enums[type].find(o=>initializer?.trim().endsWith('.'+o.name))?.value??enums[type][0]?.value??0;}else if(type==='bool')field.default=initializer?.trim()==='true';else if(type==='string'){try{field.default=initializer?.trim().startsWith('"')?JSON.parse(initializer.trim()):'';}catch{field.default='';}}else if(vectorSizes[type]){const args=initializer?.match(/(?:new\s+(?:\w+)?\s*\()?\(([^)]*)\)/)?.[1]?.split(',').map(v=>Number(v.trim().replace(/[fFdD]$/,'')));field.default=args?.length===vectorSizes[type]&&args.every(Number.isFinite)?args:Array(vectorSizes[type]).fill(0);if(['Quat','Quaternion'].includes(type)&&initializer?.trim().endsWith('.Identity'))field.default=[0,0,0,1];if(['Color','Color32'].includes(type)&&initializer?.trim().endsWith('.Black'))field.default=[0,0,0,type==='Color32'?255:1];if(initializer?.trim().endsWith('.One'))field.default=Array(vectorSizes[type]).fill(1);if(initializer?.trim().endsWith('.White'))field.default=type==='Color32'?[255,255,255,255]:[1,1,1,1];if(initializer?.trim().endsWith('.Up'))field.default=[0,1,0];if(initializer?.trim().endsWith('.Right'))field.default=[1,0,0];if(initializer?.trim().endsWith('.Forward'))field.default=[0,0,-1];}else {const n=Number(initializer?.trim().replace(/[fFdD]$/,''));field.default=Number.isFinite(n)?n:0;}if(initializer){const raw=initializer.trim();field.defaultKnown=field.options?field.options.some(o=>raw.endsWith('.'+o.name)):type==='bool'?/^(true|false)$/.test(raw):type==='string'?/^"(?:\\.|[^"\\])*"$/.test(raw):vectorSizes[type]?/^new\s*(?:\w+\s*)?\(\s*[-+.\deEfFdD,\s]+\)$/.test(raw)||/^\w+\.(Zero|One|Identity|White|Black|Up|Right|Forward)$/.test(raw):/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?[fFdD]?$/.test(raw);}fields.push(field);}
 return {path:file.path,className:entry[1],typeName:(namespace?namespace+'.':'')+entry[1],fields};}
export function scriptValue(field,value){const {type}=field;if(type==='bool'){if(typeof value!=='boolean')fail('Expected a boolean');}else if(type==='string'){if(typeof value!=='string'||value.length>4096)fail('Expected a string of at most 4096 characters');}else if(vectorSizes[type]){if(!Array.isArray(value)||value.length!==vectorSizes[type]||value.some(v=>!Number.isFinite(v)||Math.abs(v)>1000000)||type.endsWith('Int')&&value.some(v=>!Number.isInteger(v))||type==='Color32'&&value.some(v=>!Number.isInteger(v)||v<0||v>255))fail('Invalid '+type);}else{if(!Number.isFinite(value)||Math.abs(value)>1000000||['int','uint','long','short','byte'].includes(type)&&!Number.isInteger(value)||type==='uint'&&value<0||type==='byte'&&(value<0||value>255)||type==='short'&&(value<-32768||value>32767)||field.options&&!field.options.some(o=>o.value===value))fail('Invalid '+type);if(field.minimum!==undefined&&value<field.minimum||field.maximum!==undefined&&value>field.maximum)fail('Value outside Inspector range');}return structuredClone(value);}
export function scriptFields(scene,path){projectPath(path);const file=projectFiles(scene).find(f=>f.path===path),meta=file&&scriptMetadata(file);if(!meta)fail('Source must declare a Script or MonoBehaviour class');return meta;}
export function validateScriptComponents(scene){let count=0;for(const entity of scene.entities){const paths=new Set();for(const c of entity.scriptComponents??[]){if(++count>32||paths.has(c.path))fail('Script component budget is 32 total, no duplicates per entity');paths.add(c.path);const meta=scriptFields(scene,c.path);if(!c.values||typeof c.values!=='object'||Array.isArray(c.values))fail('Script fields must be an object');for(const[name,value]of Object.entries(c.values)){const field=meta.fields.find(f=>f.name===name);if(!field)fail('Unknown serialized script field: '+name);scriptValue(field,value);}}}}
export function setScriptComponent(scene,entityId,path,action,values={}){const entity=scene.entities.find(e=>e.id===entityId);if(!entity)fail('Select an entity');const meta=scriptFields(scene,path);entity.scriptComponents??=[];const existing=entity.scriptComponents.find(c=>c.path===path);if(action==='remove'){entity.scriptComponents=entity.scriptComponents.filter(c=>c.path!==path);if(!entity.scriptComponents.length)delete entity.scriptComponents;return;}if(action==='attach'){if(existing)fail('Script is already attached');entity.scriptComponents.push({path,values:Object.fromEntries(meta.fields.filter(f=>f.defaultKnown!==false).map(f=>[f.name,scriptValue(f,f.default)]))});}else if(action==='values'){if(!existing)fail('Attach this script first');for(const[name,value]of Object.entries(values)){const field=meta.fields.find(f=>f.name===name);if(!field||field.readOnly)fail('This field is hidden or read-only');existing.values[name]=scriptValue(field,value);}}else fail('Unknown script component operation');validateScriptComponents(scene);}
export function compileSources(scene,path,source){const files=projectFiles(scene).filter(f=>f.kind==='script');let selected;if(path){selected=files.find(f=>f.path===path);if(!selected)fail('Source file is missing');}else{const meta=scriptMetadata({kind:'script',path:'Scripts/Game.cs',text:source});if(!meta)fail('Source must declare a Script class');const candidate=files.find(f=>scriptMetadata(f)?.typeName===meta.typeName);selected={path:candidate?.path??'Scripts/'+meta.className+'.cs',kind:'script',text:source};if(candidate)candidate.text=source;else files.push(selected);}
 const entries=files.map(f=>({...f,metadata:scriptMetadata(f)}));if(!entries.some(f=>f.path===selected.path&&f.metadata))fail('Selected source is not a Script');if(entries.reduce((n,f)=>n+new TextEncoder().encode(f.text).length,0)>65536)fail('C# source budget is 64 KiB');return {entries,selected};}

export function reconcileScriptComponents(scene){for(const e of scene.entities)for(const c of e.scriptComponents??[]){const meta=scriptFields(scene,c.path);c.values=Object.fromEntries(meta.fields.filter(f=>f.defaultKnown!==false||Object.hasOwn(c.values,f.name)).map(f=>{let value=f.default;try{if(Object.hasOwn(c.values,f.name))value=scriptValue(f,c.values[f.name]);}catch{}return [f.name,value];}));}}
