import {randomUUID,createHash} from 'node:crypto';
import {envelope} from '../../../protocol/src/protocol.ts';
import {validateTest} from '../../../engine/testing/session.mjs';
import {worldTransforms} from '../../../engine/scene/hierarchy.mjs';
import {projectFiles} from '../../../engine/scene/project-files.mjs';
import {scriptMetadata} from '../../../engine/scripting/fields.mjs';
import {toolMap,validate,agentError} from './contracts.mjs';
const fail=message=>{throw agentError('AX_AUTONOMY_0001',message);};
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const digest=value=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
const allowed=new Set(['project.files.edit','scene.entity.update','scene.entities.update','scene.entity.create','scene.entity.delete','scene.primitive.create','scene.script.edit','scene.material.set','scene.light.set','scene.collider.set','scene.rigidBody.set','scene.camera.set','scene.animator.set','scene.sprite2D.set','scene.light2D.set']);

// The daemon owns budgets, isolation and evidence. An external AI may supply a
// structured plan; the included deterministic repair policies never pretend to
// interpret arbitrary natural language or invoke an unconfigured model.
export class AutonomyController {
 constructor({bus,workspace,proposals,bridge}){Object.assign(this,{bus,workspace,proposals,bridge});this.sessions=new Map();this.active=null;}
 result(id){const s=this.sessions.get(id);if(!s)fail('Autonomy session is unavailable');return structuredClone(s.public);}
 async control(data,context){
  if(data.action==='query')return this.result(data.sessionId);
  if(data.action==='cancel'){const s=this.sessions.get(data.sessionId);if(!s)fail('Autonomy session is unavailable');if(s.public.status==='running'){s.cancel=true;s.public.phase='cancelling';}return this.result(data.sessionId);}
  if(data.action!=='run')fail('Unknown autonomy action');if(this.active)fail('One autonomy session may run at a time');this.workspace.check(data);
  if(this.workspace.playing||this.workspace.dirty||this.workspace.activeJob||this.workspace.activeScriptJob||this.proposals.previewId)fail('Save, stop and return to MAIN before starting autonomy');
  const plan=structuredClone(data.plan);if(!plan||JSON.stringify(plan).length>65536||typeof plan.objective!=='string'||!plan.objective.trim()||plan.objective.length>2000)fail('Provide a bounded objective and test criteria');
  if(Object.keys(plan).some(k=>!['objective','suite','actions','repairPolicy','compilerRepairs','maxIterations','maxSeconds'].includes(k)))fail('Unknown plan field');
  plan.suite=validateTest(plan.suite);if(!plan.suite.steps.some(s=>s.assertions?.length))fail('Acceptance needs at least one assertion');
  if(!Array.isArray(plan.actions)||plan.actions.length>24)fail('Plan is limited to 24 actions');
  for(const action of plan.actions){if(!action||Object.keys(action).some(k=>!['tool','arguments'].includes(k))||!allowed.has(action.tool)||action.arguments?.workspaceId||action.arguments?.id||action.arguments?.expectedSceneRevision)fail('Plan actions cannot select authority or invoke this tool');const tool=toolMap.get(action.tool);validate(tool.inputSchema,{id:data.id,expectedSceneRevision:data.expectedSceneRevision,workspaceId:'workspace://00000000-0000-4000-8000-000000000000',...action.arguments});}
  if(!['none','position'].includes(plan.repairPolicy??'none'))fail('Unsupported repair policy');
  if(!Array.isArray(plan.compilerRepairs??[])||(plan.compilerRepairs?.length??0)>8)fail('Compiler repair budget exceeded');for(const patch of plan.compilerRepairs??[]){if(typeof patch.path!=='string'||typeof patch.find!=='string'||!patch.find||patch.find.length>4096||typeof patch.replace!=='string'||patch.replace.length>4096)fail('Invalid exact source patch');}
  const iterations=plan.maxIterations??3,seconds=plan.maxSeconds??300;if(!Number.isInteger(iterations)||iterations<1||iterations>4||!Number.isInteger(seconds)||seconds<10||seconds>600)fail('Invalid autonomy budgets');
  if(this.sessions.size>=8){const oldest=[...this.sessions.values()].find(s=>s.public.status!=='running');if(oldest)this.sessions.delete(oldest.public.id);else fail('Session retention budget exceeded');}
  const id='autonomy://'+randomUUID(),s={plan,cancel:false,deadline:performance.now()+seconds*1000,commands:0,patches:new Set(),sourceId:data.id,sourceRevision:data.expectedSceneRevision,context,public:{id,objective:plan.objective,status:'running',phase:'planning',workspaceId:null,iteration:0,criteria:plan.suite,planHash:digest(plan),limits:{iterations,seconds,commands:64},evidence:[],repairs:[],benchmark:null,changeSet:null}};
  this.sessions.set(id,s);this.active=s;s.flight=new Promise(resolve=>setImmediate(resolve)).then(()=>this.execute(s)).finally(()=>{if(this.active===s)this.active=null;});return this.result(id);
 }
 check(s){if(s.cancel)throw agentError('AX_AUTONOMY_0002','Autonomy cancelled');if(performance.now()>s.deadline)throw agentError('AX_AUTONOMY_0002','Autonomy time budget exhausted');}
 record(s,kind,value){if(s.public.evidence.length>=64)fail('Evidence budget exhausted');const entry={sequence:s.public.evidence.length+1,kind,iteration:s.public.iteration,workspaceId:s.public.workspaceId,...value};if(Buffer.byteLength(JSON.stringify([...s.public.evidence,entry]))>96000)fail('Evidence byte budget exhausted');s.public.evidence.push(entry);}
 async call(s,type,args={},poll=false){this.check(s);if(!poll&&++s.commands>64)fail('Autonomy command budget exhausted');const event=await this.bus.dispatch(envelope('command',{type,data:args},{actor:{kind:'agent',id:'autonomy-loop'},correlationId:s.context?.correlationId,traceId:randomUUID(),causationId:s.context?.causationId}));if(event.kind==='error')throw Object.assign(Error(event.payload.cause),{code:event.payload.code});return event.payload.data;}
 async scope(s){const w=await this.call(s,'scene.get',{id:s.sourceId,workspaceId:s.public.workspaceId},true);return {id:s.sourceId,workspaceId:s.public.workspaceId,expectedSceneRevision:w.sceneRevision};}
 async compile(s){const snapshot=await this.call(s,'scene.get',await this.scope(s),true),scene=snapshot.project.scene,file=projectFiles(scene).find(f=>f.kind==='script'&&scriptMetadata(f));if(!file)return {passed:true,skipped:'No C# sources'};s.public.phase='compiling';let job=(await this.call(s,'script.compile',{...await this.scope(s),path:file.path,mode:'development',attachments:[]})).job;
  while(['queued','running'].includes(job.status)){await sleep(150);job=(await this.call(s,'script.job.get',{id:s.sourceId,workspaceId:s.public.workspaceId,jobId:job.id},true)).job;}
  const passed=job.status==='completed';this.record(s,'compile',{passed,jobId:job.id,sourceHash:job.build?.sourceHash??null,durationMs:job.build?.durationMs??null,diagnostics:(job.error?.diagnostics??[]).slice(0,12).map(d=>({...d,message:String(d.message).slice(0,512)})),error:job.error?.message?.slice(0,1024)??null});return {passed,job};
 }
 async test(s,kind='acceptance'){s.public.phase=kind==='acceptance'?'testing':'benchmarking';const scope=await this.scope(s);if(this.proposals.previewId!==s.public.workspaceId){const w=this.proposals.get(s.public.workspaceId);await this.call(s,'workspace.preview',{workspaceId:w.id,expectedWorkspaceRevision:w.child.revision,playing:false});}
  let expected=await this.scope(s);while(true){this.check(s);const ready=this.bridge.status();if(ready.connected&&ready.projectId===s.sourceId&&ready.workspaceId===s.public.workspaceId&&ready.sceneRevision===expected.expectedSceneRevision&&!ready.playing)break;await sleep(100);}
  const start=performance.now();let job=await this.call(s,'gameTest.control',{...expected,action:'run',suite:s.plan.suite});while(['running','cancelling','paused'].includes(job.status)){await sleep(100);job=await this.call(s,'gameTest.control',{...expected,action:'query'},true);}
  const durationMs=performance.now()-start;this.record(s,kind,{passed:job.status==='completed',sceneRevision:expected.expectedSceneRevision,jobId:job.id,status:job.status,frames:job.frames,durationMs,results:job.results,error:job.error??null});return {job,durationMs};
 }
 async repairCompile(s){for(const patch of s.plan.compilerRepairs??[]){const hash=digest(patch);if(s.patches.has(hash))continue;const snapshot=await this.call(s,'scene.get',await this.scope(s),true),file=projectFiles(snapshot.project.scene).find(f=>f.kind==='script'&&f.path===patch.path);if(!file)continue;const at=file.text.indexOf(patch.find);if(at<0||file.text.indexOf(patch.find,at+patch.find.length)>=0)continue;const text=file.text.slice(0,at)+patch.replace+file.text.slice(at+patch.find.length);await this.call(s,'project.files.edit',{...await this.scope(s),action:'write',path:file.path,text});s.patches.add(hash);s.public.repairs.push({iteration:s.public.iteration,kind:'compiler-exact-patch',path:file.path,beforeHash:digest(file.text),afterHash:digest(text)});return true;}return false;}
 async repairTests(s,job){if(s.plan.repairPolicy!=='position')return false;const assertions=s.plan.suite.steps.flatMap(step=>step.assertions??[]),snapshot=await this.call(s,'scene.get',await this.scope(s),true),world=worldTransforms(snapshot.project.scene.entities),updates=[];for(const[resultIndex,result]of (job.results??[]).entries()){const a=assertions[resultIndex];if(result.passed||a?.kind!=='position'||!Array.isArray(result.actual))continue;const transform=world.get(a.entityId);if(!transform||updates.some(u=>u.entityId===a.entityId))continue;updates.push({entityId:a.entityId,transform:{...transform,position:transform.position.map((v,i)=>v+a.value[i]-result.actual[i])}});}if(!updates.length)return false;await this.call(s,'scene.entities.update',{...await this.scope(s),updates,space:'world'});s.public.repairs.push({iteration:s.public.iteration,kind:'position-error-delta',updates});return true;}
 async returnToSource(s){const w=s.public.workspaceId&&this.proposals.items.get(s.public.workspaceId);if(w&&this.proposals.previewId===w.id){const response=await this.bus.dispatch(envelope('command',{type:'workspace.continue',data:{workspaceId:w.id,expectedWorkspaceRevision:w.child.revision}},{actor:{kind:'agent',id:'autonomy-loop'}}));if(response.kind==='error')throw Object.assign(Error(response.payload.cause),{code:response.payload.code});}}
 async execute(s){try{
  const w=await this.call(s,'workspace.begin',{id:s.sourceId,expectedSceneRevision:s.sourceRevision,name:'Autonomy · '+s.plan.objective.slice(0,110)});s.public.workspaceId=w.id;
  s.public.phase='modifying';for(const action of s.plan.actions)await this.call(s,action.tool,{...await this.scope(s),...action.arguments});
  for(let i=1;i<=s.public.limits.iterations;i++){this.check(s);s.public.iteration=i;const compiled=await this.compile(s);if(!compiled.passed){s.public.phase='diagnosing';this.record(s,'diagnosis',{cause:'compiler-failure',code:compiled.job.error?.code??'AX_SCRIPT_0001'});if(i<s.public.limits.iterations&&await this.repairCompile(s))continue;fail('Compilation failed without an applicable repair');}
   const tested=await this.test(s);if(tested.job.status==='completed'){const samples=[];for(let n=0;n<2;n++){const sample=await this.test(s,'benchmark');if(sample.job.status!=='completed')fail('Verification regressed during fresh-world benchmark');samples.push(sample.durationMs);}s.public.benchmark={samples:2,wallMs:samples,meanWallMs:samples.reduce((a,b)=>a+b,0)/2,framesPerSample:tested.job.frames,meaning:'Measured bridge + fixed-step execution + presentation wall time; not physical GPU performance'};await this.returnToSource(s);const diff=await this.call(s,'workspace.diff',{workspaceId:s.public.workspaceId,limit:1,maxBytes:8192});s.public.changeSet={workspaceId:s.public.workspaceId,revision:diff.workspace.revision,reviewHash:diff.reviewHash,changes:diff.total,acceptance:'Human Review differences and Accept reviewed changes; Save remains explicit'};s.public.status='completed';s.public.phase='ready-for-review';return;}
   s.public.phase='diagnosing';this.record(s,'diagnosis',{cause:'acceptance-failure',failedAssertions:tested.job.results?.filter(r=>!r.passed)??[],error:tested.job.error??null});if(i>=s.public.limits.iterations||!await this.repairTests(s,tested.job))fail('Acceptance failed without an applicable repair');
  }
 }catch(error){s.public.status=s.cancel?'cancelled':'failed';s.public.phase='finished';s.public.error={code:error.code??'AX_AUTONOMY_0001',message:String(error.message).slice(0,1024)};}finally{if(s.public.workspaceId){const child=this.proposals.items.get(s.public.workspaceId)?.child;if(child?.activeScriptJob)child.activeScriptJob.controller.abort();if(child?.activeJob)child.activeJob.controller.abort();const cleanupDeadline=performance.now()+10000;while((child?.activeScriptJob||child?.activeJob)&&performance.now()<cleanupDeadline)await sleep(20);if(s.cancel&&this.proposals.previewId===s.public.workspaceId){try{await this.bus.dispatch(envelope('command',{type:'gameTest.control',data:{...await this.scopeUnchecked(s),action:'cancel'}},{actor:{kind:'agent',id:'autonomy-loop'}}));}catch{}}await this.returnToSource(s).catch(error=>{s.public.cleanupError={code:error.code??'AX_AUTONOMY_0001',message:String(error.message).slice(0,512)};s.public.status='failed';s.public.phase='cleanup-required';});}s.public.commands=s.commands;}
 }
 async scopeUnchecked(s){const w=this.proposals.get(s.public.workspaceId);return {id:s.sourceId,workspaceId:w.id,expectedSceneRevision:w.child.revision};}
 async close(){if(this.active){this.active.cancel=true;await this.active.flight;}}
}
