import {randomUUID} from 'node:crypto';
import {agentError,size} from './contracts.mjs';
// One short-lived editor lease. Capture requests are never satisfied by stale reports.
export class EditorBridge {
 released=new Set();
 release(clientId){if(this.client?.id!==clientId)return false;this.released.add(clientId);if(this.released.size>32)this.released.delete(this.released.values().next().value);this.close();this.client=null;return true;}
 constructor(workspace,onError,{timeoutMs=5000,leaseMs=5000}={}){this.workspace=workspace;this.onError=onError;this.timeoutMs=timeoutMs;this.leaseMs=leaseMs;this.client=null;this.pending=null;this.pendingDiagnostic=null;this.pendingAnimation=null;this.pendingAudio=null;this.pendingProfiler=null;this.pendingTest=null;this.pendingReplay=null;}
 status(){const live=this.client&&Date.now()-this.client.at<this.leaseMs;return {connected:!!live,...(live?{...this.client.status,clientId:this.client.id}:{})};}
 sync(data){
  if(!data||typeof data.clientId!=='string'||!/^[0-9a-f-]{36}$/.test(data.clientId)||size(data)>850000)throw agentError('AX_AGENT_0001','Invalid editor report');
  if(this.released.has(data.clientId))throw agentError('AX_AGENT_0002','Editor lease was released');
  if(this.client&&this.client.id!==data.clientId&&Date.now()-this.client.at<this.leaseMs)throw agentError('AX_AGENT_0002','Another editor owns the renderer lease');
  const s=data.status??{};
  if(size(s)>65536)throw agentError('AX_AGENT_0001','Editor status exceeds limit');
  this.client={id:data.clientId,at:Date.now(),status:{replay:s.replay&&size(s.replay)<=2048?structuredClone(s.replay):null,gameTest:s.gameTest&&size(s.gameTest)<=16384?structuredClone(s.gameTest):null,profiler:s.profiler&&size(s.profiler)<=2048?structuredClone(s.profiler):null,workspaceId:s.workspaceId??null,sceneRevision:s.sceneRevision??null,projectId:s.projectId??null,frame:s.frame??null,traceId:s.traceId??null,view:s.view??null,renderer:s.renderer??null,playing:!!s.playing,audioFault:typeof s.audioFault==='string'?s.audioFault.slice(0,2048):null,audio:s.audio&&size(s.audio)<=32768?structuredClone(s.audio):null,animationFault:typeof s.animationFault==='string'?s.animationFault.slice(0,2048):null,animation:Array.isArray(s.animation)&&size(s.animation)<=32768?structuredClone(s.animation):[],rendering:s.rendering&&typeof s.rendering==='object'&&size(s.rendering)<=16384?structuredClone(s.rendering):null,physics:s.physics??null,generation:s.generation??null,fault:typeof s.fault==='string'?s.fault.slice(0,2048):null}};
  if(data.diagnostic&&this.pendingDiagnostic&&this.pendingDiagnostic.clientId===data.clientId&&data.diagnostic.requestId===this.pendingDiagnostic.id){
   const p=this.pendingDiagnostic,v=data.diagnostic.value;clearTimeout(p.timer);this.pendingDiagnostic=null;
   if(s.projectId!==p.args.id||s.sceneRevision!==p.args.expectedSceneRevision||(s.workspaceId??null)!==(p.args.workspaceId??null))p.reject(agentError('AX_SCENE_0002','Diagnostic revision is stale'));
   else if(!v||!['explained','inconclusive','unavailable'].includes(v.status)||!Array.isArray(v.nodes)||v.nodes.length>24||size(v)>16384||v.status!=='unavailable'&&(v.sceneRevision!==p.args.expectedSceneRevision||v.projectId!==p.args.id||(v.workspaceId??null)!==(p.args.workspaceId??null)))p.reject(agentError('AX_AGENT_0001','Invalid diagnostic evidence'));
   else p.resolve(v);
  }
  for(const error of (Array.isArray(data.errors)?data.errors:[]).slice(0,16))this.onError({code:typeof error.code==='string'?error.code.slice(0,64):'AX_EDITOR_0001',cause:String(error.cause??'Editor failure').slice(0,2048),subsystem:'editor',traceId:error.traceId??null});
  if(data.capture&&this.pending&&this.pending.clientId===data.clientId&&data.capture.requestId===this.pending.id){
   const p=this.pending,c=data.capture;clearTimeout(p.timer);this.pending=null;
   try{
    if(c.error)throw agentError('AX_AGENT_0002',String(c.error).slice(0,512));
    const v=c.value;
    if((this.workspace.workspaceId??null)!==(p.args.workspaceId??null)||v?.workspaceId!== (p.args.workspaceId??null)||this.workspace.project?.id!==p.args.id||this.workspace.revision!==p.args.expectedSceneRevision||v?.sceneRevision!==p.args.expectedSceneRevision||v?.projectId!==p.args.id)throw agentError('AX_SCENE_0002','Capture revision is stale');
    if(v?.width!==p.args.width||v?.height!==p.args.height||typeof v?.base64!=='string'||v.base64.length>700000||!/^iVBORw0KGgo[A-Za-z0-9+/=]+$/.test(v.base64)||size(v.semantic)>16384)throw agentError('AX_AGENT_0001','Invalid capture payload');
    const png=Buffer.from(v.base64,'base64');if(png.length>512*1024||png.length<24||png.readUInt32BE(16)!==v.width||png.readUInt32BE(20)!==v.height)throw agentError('AX_AGENT_0001','Invalid PNG dimensions');
    p.resolve(v);
   }catch(error){p.reject(error);}
  }
  if(data.animation&&this.pendingAnimation&&this.pendingAnimation.clientId===data.clientId&&data.animation.requestId===this.pendingAnimation.id){const p=this.pendingAnimation;clearTimeout(p.timer);this.pendingAnimation=null;if(s.projectId!==p.args.id||s.sceneRevision!==p.args.expectedSceneRevision||(s.workspaceId??null)!==(p.args.workspaceId??null))p.reject(agentError('AX_SCENE_0002','Animation revision changed'));else if(data.animation.error)p.reject(agentError('AX_AGENT_0002',String(data.animation.error).slice(0,512)));else if(size(data.animation.value)>16384)p.reject(agentError('AX_AGENT_0001','Animation response exceeds bound'));else p.resolve(data.animation.value);}
  if(data.audio&&this.pendingAudio&&this.pendingAudio.clientId===data.clientId&&data.audio.requestId===this.pendingAudio.id){const p=this.pendingAudio;clearTimeout(p.timer);this.pendingAudio=null;if(s.projectId!==p.args.id||s.sceneRevision!==p.args.expectedSceneRevision||(s.workspaceId??null)!==(p.args.workspaceId??null))p.reject(agentError('AX_SCENE_0002','Audio revision changed'));else if(data.audio.error)p.reject(agentError('AX_AGENT_0002',String(data.audio.error).slice(0,512)));else if(size(data.audio.value)>16384)p.reject(agentError('AX_AGENT_0001','Audio response exceeds bound'));else p.resolve(data.audio.value);}
  if(data.profiler&&this.pendingProfiler&&this.pendingProfiler.clientId===data.clientId&&data.profiler.requestId===this.pendingProfiler.id){const p=this.pendingProfiler,v=data.profiler.value;clearTimeout(p.timer);this.pendingProfiler=null;
   if(s.projectId!==p.args.id||s.sceneRevision!==p.args.expectedSceneRevision||(s.workspaceId??null)!==(p.args.workspaceId??null)||s.generation!==p.generation)p.reject(agentError('AX_SCENE_0002','Profiler session changed'));
   else if(data.profiler.error)p.reject(agentError('AX_AGENT_0002',String(data.profiler.error).slice(0,512)));
   else if(!v||!['observed','explained','inconclusive','unavailable'].includes(v.status)||size(v)>16384||v.projectId!==p.args.id||v.sceneRevision!==p.args.expectedSceneRevision||(v.workspaceId??null)!==(p.args.workspaceId??null)||v.generation!==p.generation)p.reject(agentError('AX_AGENT_0001','Invalid profiler evidence'));
   else p.resolve(v);
  }
  if(data.gameTest&&this.pendingTest&&this.pendingTest.clientId===data.clientId&&data.gameTest.requestId===this.pendingTest.id){const p=this.pendingTest;clearTimeout(p.timer);this.pendingTest=null;if(this.workspace.project?.id!==p.args.id||this.workspace.revision!==p.args.expectedSceneRevision||(this.workspace.workspaceId??null)!==(p.args.workspaceId??null)||s.projectId!==p.args.id||s.sceneRevision!==p.args.expectedSceneRevision)p.reject(agentError('AX_SCENE_0002','Test revision changed'));else if(data.gameTest.error)p.reject(agentError('AX_TEST_0001',String(data.gameTest.error).slice(0,1024)));else if(!data.gameTest.value||size(data.gameTest.value)>32768||!['idle','running','paused','cancelling','cancelled','failed','completed'].includes(data.gameTest.value.status))p.reject(agentError('AX_TEST_0001','Invalid test evidence'));else p.resolve(data.gameTest.value);}
  if(data.replay&&this.pendingReplay&&this.pendingReplay.clientId===data.clientId&&data.replay.requestId===this.pendingReplay.id){const p=this.pendingReplay;clearTimeout(p.timer);this.pendingReplay=null;if(this.workspace.project?.id!==p.args.id||this.workspace.revision!==p.args.expectedSceneRevision||(this.workspace.workspaceId??null)!==(p.args.workspaceId??null)||s.projectId!==p.args.id||s.sceneRevision!==p.args.expectedSceneRevision)p.reject(agentError('AX_SCENE_0002','Test revision changed'));else if(data.replay.error)p.reject(agentError('AX_REPLAY_0001',String(data.replay.error).slice(0,1024)));else if(!data.replay.value||size(data.replay.value)>262144||!['idle','running','paused','cancelling','cancelled','failed','completed'].includes(data.replay.value.status))p.reject(agentError('AX_REPLAY_0001','Invalid test evidence'));else p.resolve(data.replay.value);}
  const snapshot=(data.workspaceId??null)!==(this.workspace.workspaceId??null)||data.sceneRevision!==this.workspace.revision?this.workspace.snapshot():null;
  return {snapshot,replay:this.pendingReplay?.clientId===data.clientId?{requestId:this.pendingReplay.id,...this.pendingReplay.args}:null,gameTest:this.pendingTest?.clientId===data.clientId?{requestId:this.pendingTest.id,...this.pendingTest.args}:null,profiler:this.pendingProfiler?.clientId===data.clientId?{requestId:this.pendingProfiler.id,...this.pendingProfiler.args}:null,audio:this.pendingAudio?.clientId===data.clientId?{requestId:this.pendingAudio.id,...this.pendingAudio.args}:null,animation:this.pendingAnimation?.clientId===data.clientId?{requestId:this.pendingAnimation.id,...this.pendingAnimation.args}:null,capture:this.pending?.clientId===data.clientId?{requestId:this.pending.id,...this.pending.args}:null,diagnostic:this.pendingDiagnostic?.clientId===data.clientId?{requestId:this.pendingDiagnostic.id,...this.pendingDiagnostic.args}:null};
 }
 capture(args){
  const status=this.status();
  if((status.workspaceId??null)!==(args.workspaceId??null)||!status.connected||status.renderer!=='webgpu'||status.projectId!==args.id||status.sceneRevision!==args.expectedSceneRevision)throw agentError('AX_AGENT_0002','A ready WebGPU editor at this scene revision is required');
  if(this.pending)throw agentError('AX_AGENT_0002','Capture already in progress');
  return new Promise((resolve,reject)=>{const pending={id:randomUUID(),clientId:this.client.id,args:{width:640,height:360,maxEntities:16,...args},resolve,reject};pending.timer=setTimeout(()=>{if(this.pending===pending)this.pending=null;reject(agentError('AX_AGENT_0002','Editor capture timed out'));},this.timeoutMs);this.pending=pending;});
 }
 explain(args){const status=this.status();if(!status.connected||status.projectId!==args.id||status.sceneRevision!==args.expectedSceneRevision||(status.workspaceId??null)!==(args.workspaceId??null))return {status:'unavailable',code:'AX_CAUSAL_0001',message:'A live editor at this project/workspace revision is required',nodes:[],edges:[]};if(this.pendingDiagnostic)throw agentError('AX_AGENT_0002','Diagnostic request already in progress');return new Promise((resolve,reject)=>{const p={id:randomUUID(),clientId:this.client.id,args,resolve,reject};p.timer=setTimeout(()=>{if(this.pendingDiagnostic===p)this.pendingDiagnostic=null;resolve({status:'unavailable',code:'AX_CAUSAL_0001',message:'Editor diagnostic request timed out',nodes:[],edges:[]});},this.timeoutMs);this.pendingDiagnostic=p;});}
 animation(args){const s=this.status();if(!s.connected||!s.playing||s.projectId!==args.id||s.sceneRevision!==args.expectedSceneRevision||(s.workspaceId??null)!==(args.workspaceId??null))throw agentError('AX_AGENT_0002','Live Play editor at the requested revision is required');if(this.pendingAnimation)throw agentError('AX_AGENT_0002','Animation control already pending');return new Promise((resolve,reject)=>{const p={id:randomUUID(),clientId:this.client.id,args,resolve,reject};p.timer=setTimeout(()=>{if(this.pendingAnimation===p)this.pendingAnimation=null;reject(agentError('AX_AGENT_0002','Animation control timed out'));},this.timeoutMs);this.pendingAnimation=p;});}
 audio(args){const s=this.status();if(!s.connected||!s.playing||s.projectId!==args.id||s.sceneRevision!==args.expectedSceneRevision||(s.workspaceId??null)!==(args.workspaceId??null))throw agentError('AX_AGENT_0002','Live Play editor at the requested revision is required');if(this.pendingAudio)throw agentError('AX_AGENT_0002','Audio control already pending');return new Promise((resolve,reject)=>{const p={id:randomUUID(),clientId:this.client.id,args,resolve,reject};p.timer=setTimeout(()=>{if(this.pendingAudio===p)this.pendingAudio=null;reject(agentError('AX_AGENT_0002','Audio control timed out'));},this.timeoutMs);this.pendingAudio=p;});}
 profiler(args){const s=this.status();if(!s.connected||s.projectId!==args.id||s.sceneRevision!==args.expectedSceneRevision||(s.workspaceId??null)!==(args.workspaceId??null))return {status:'unavailable',projectId:args.id,sceneRevision:args.expectedSceneRevision,workspaceId:args.workspaceId??null,message:'A live editor at this revision is required',items:[]};if(this.pendingProfiler)throw agentError('AX_AGENT_0002','Profiler query already pending');return new Promise((resolve,reject)=>{const p={id:randomUUID(),clientId:this.client.id,generation:s.generation,args,resolve,reject};p.timer=setTimeout(()=>{if(this.pendingProfiler===p)this.pendingProfiler=null;reject(agentError('AX_AGENT_0002','Profiler query timed out'));},this.timeoutMs);this.pendingProfiler=p;});}
 gameTest(args){const s=this.status();if(!s.connected||s.projectId!==args.id||s.sceneRevision!==args.expectedSceneRevision||(s.workspaceId??null)!==(args.workspaceId??null))throw agentError('AX_TEST_0001','Live editor at the requested revision required');if(this.pendingTest)throw agentError('AX_TEST_0001','Test request pending');return new Promise((resolve,reject)=>{const p={id:randomUUID(),clientId:this.client.id,args,resolve,reject};p.timer=setTimeout(()=>{if(this.pendingTest===p)this.pendingTest=null;reject(agentError('AX_TEST_0002','Test request timed out'));},this.timeoutMs);this.pendingTest=p;});}
 replay(args){const s=this.status();if(!s.connected||s.projectId!==args.id||s.sceneRevision!==args.expectedSceneRevision||(s.workspaceId??null)!==(args.workspaceId??null))throw agentError('AX_REPLAY_0001','Live editor at the requested revision required');if(this.pendingReplay)throw agentError('AX_REPLAY_0001','Test request pending');return new Promise((resolve,reject)=>{const p={id:randomUUID(),clientId:this.client.id,args,resolve,reject};p.timer=setTimeout(()=>{if(this.pendingReplay===p)this.pendingReplay=null;reject(agentError('AX_REPLAY_0002','Test request timed out'));},this.timeoutMs);this.pendingReplay=p;});}
 close(){if(this.pendingTest){clearTimeout(this.pendingTest.timer);this.pendingTest.reject(agentError('AX_TEST_0002','Editor bridge closed'));this.pendingTest=null;}if(this.pendingReplay){clearTimeout(this.pendingReplay.timer);this.pendingReplay.reject(agentError('AX_REPLAY_0002','Editor bridge closed'));this.pendingReplay=null;}if(this.pendingProfiler){clearTimeout(this.pendingProfiler.timer);this.pendingProfiler.reject(agentError('AX_AGENT_0002','Editor bridge closed'));this.pendingProfiler=null;}if(this.pendingAudio){clearTimeout(this.pendingAudio.timer);this.pendingAudio.reject(agentError('AX_AGENT_0002','Editor bridge closed'));this.pendingAudio=null;}if(this.pendingAnimation){clearTimeout(this.pendingAnimation.timer);this.pendingAnimation.reject(agentError('AX_AGENT_0002','Editor bridge closed'));this.pendingAnimation=null;}if(this.pending){clearTimeout(this.pending.timer);this.pending.reject(agentError('AX_AGENT_0002','Editor bridge closed'));this.pending=null;}if(this.pendingDiagnostic){clearTimeout(this.pendingDiagnostic.timer);this.pendingDiagnostic.reject(agentError('AX_AGENT_0002','Editor bridge closed'));this.pendingDiagnostic=null;}}
}
