import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join} from 'node:path';
import {SceneWorkspace} from '../daemon/bootstrap/scene-workspace.mjs';
import {ProjectStore} from '../daemon/bootstrap/project-store.mjs';
import {ProposalManager} from '../daemon/bootstrap/workspaces/manager.mjs';
import {AgentService} from '../daemon/bootstrap/agent/service.mjs';
import {CommandBus} from '../daemon/bootstrap/command-bus.mjs';
import {envelope} from '../protocol/src/protocol.ts';
import {GameTestSession} from '../engine/testing/session.mjs';
async function fixture(t){const root=await mkdtemp(join(tmpdir(),'axiom-autonomy-'));t.after(()=>rm(root,{recursive:true,force:true}));const main=new SceneWorkspace(new ProjectStore(root));await main.run('project.create',{name:'Autonomy'});await main.run('scene.entity.create',{id:main.project.id,expectedSceneRevision:main.revision,name:'Target'});await main.run('scene.save',{id:main.project.id,expectedSceneRevision:main.revision});const proposals=new ProposalManager(main);await proposals.initialize();const bus=new CommandBus({projects:main});let runtime=null;const session=new GameTestSession({async begin(){runtime=structuredClone(proposals.active.project.scene);},async step(){},async state(){return {entities:runtime.entities,contacts:[],animation:[]};},async end(){runtime=null;}});const bridge={status:()=>({connected:true,projectId:proposals.active.project.id,workspaceId:proposals.previewId,sceneRevision:proposals.active.revision,playing:false}),gameTest:async args=>session.control(args)};bus.agentService=new AgentService({workspace:main,bus,bridge});bus.agentService.proposals=proposals;const call=async(type,data,actor='agent')=>{const r=await bus.dispatch(envelope('command',{type,data},{actor:{kind:actor,id:'test'}}));if(r.kind==='error')throw Object.assign(Error(r.payload.cause),{code:r.payload.code});return r.payload.data;};return {main,proposals,bus,call,entityId:main.project.scene.entities[0].id,path:join(root,main.store.filename(main.project.id))};}
const plan=(f,extra={})=>({objective:'Put the target at x=3 and prove it without changing MAIN',suite:{name:'Target position',steps:[{frames:0,assertions:[{kind:'position',entityId:f.entityId,value:[3,0,0]}]}]},actions:[],repairPolicy:'position',maxIterations:3,maxSeconds:10,...extra});
const start=(f,p)=>f.call('autonomy.control',{action:'run',id:f.main.project.id,expectedSceneRevision:f.main.revision,plan:p});
async function finish(f,id){await f.bus.agentService.autonomy.active?.flight;return f.call('autonomy.control',{action:'query',sessionId:id});}
test('autonomy observes failure, repairs, retests and benchmarks an isolated change set requiring human review',async t=>{const f=await fixture(t),before=JSON.stringify(f.main.project.scene),disk=await readFile(f.path);const receipt=await start(f,plan(f)),result=await finish(f,receipt.id);assert.equal(result.status,'completed');assert.equal(result.iteration,2);assert.equal(result.evidence.filter(e=>e.kind==='acceptance')[0].passed,false);assert.equal(result.evidence.filter(e=>e.kind==='acceptance')[1].passed,true);assert.equal(result.benchmark.samples,2);assert.ok(result.benchmark.wallMs.every(n=>n>0));assert.equal(result.repairs[0].kind,'position-error-delta');assert.equal(JSON.stringify(f.main.project.scene),before);assert.deepEqual(await readFile(f.path),disk);assert.equal(f.proposals.previewId,null);const w=f.proposals.get(result.workspaceId);assert.deepEqual(w.child.project.scene.entities[0].transform.position,[3,0,0]);await assert.rejects(f.call('workspace.accept',{workspaceId:w.id,expectedWorkspaceRevision:w.child.revision,reviewHash:result.changeSet.reviewHash}),/human/);await f.call('workspace.accept',{workspaceId:w.id,expectedWorkspaceRevision:w.child.revision,reviewHash:result.changeSet.reviewHash},'human');assert.equal(f.main.dirty,true);await f.main.run('scene.undo',{id:f.main.project.id,expectedSceneRevision:f.main.revision});assert.equal(JSON.stringify(f.main.project.scene),before);});
test('autonomy rejects unbounded goals, authority overrides, absent assertions and source publication tools',async t=>{const f=await fixture(t);for(const p of [plan(f,{maxIterations:5}),plan(f,{actions:[{tool:'scene.save',arguments:{}}]}),plan(f,{actions:[{tool:'scene.entity.update',arguments:{id:f.main.project.id,entityId:f.entityId}}]}),plan(f,{suite:{name:'No checks',steps:[{frames:1}]}}),plan(f,{shell:'unsafe'})])await assert.rejects(start(f,p));assert.equal(f.proposals.items.size,0);});
test('an exhausted loop retains failed evidence, clears preview and never marks the proposal verified',async t=>{const f=await fixture(t),receipt=await start(f,plan(f,{maxIterations:1})),result=await finish(f,receipt.id);assert.equal(result.status,'failed');assert.equal(result.changeSet,null);assert.ok(result.evidence.some(e=>e.kind==='diagnosis'));assert.equal(f.proposals.previewId,null);assert.deepEqual(f.main.project.scene.entities[0].transform.position,[0,0,0]);});
test('cancellation and a second run respect the single active loop and retain unchanged MAIN',async t=>{const f=await fixture(t),receipt=await start(f,plan(f));await assert.rejects(start(f,plan(f)),/one autonomy|One autonomy/);await f.call('autonomy.control',{action:'cancel',sessionId:receipt.id});const result=await finish(f,receipt.id);assert.equal(result.status,'cancelled');assert.equal(f.proposals.previewId,null);assert.equal(f.main.dirty,false);});
