import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {ProjectStore} from '../daemon/bootstrap/project-store.mjs';
import {SceneWorkspace} from '../daemon/bootstrap/scene-workspace.mjs';
import {activeGameCamera,cameraRotation,legacyDirectionalUniforms} from '../engine/scene/camera.mjs';
import {listenerPose} from '../engine/audio/plan.mjs';
const transform=(position=[0,0,0])=>({position,rotation:[0,0,0,1],scale:[1,1,1]});
async function workspace(t){const root=await mkdtemp(join(tmpdir(),'axiom-camera-'));t.after(()=>rm(root,{recursive:true,force:true}));return new SceneWorkspace(new ProjectStore(root));}
for(const dimension of [2,3])test(`${dimension}D starter persists an editable Camera, listener, explicit light and object`,async t=>{const w=await workspace(t);let s=await w.run('project.create',{name:'Starter',dimension});assert.equal(s.dirty,false);assert.equal(s.project.scene.entities.length,3);assert.equal(s.project.scene.cameraMode,'entities');assert.equal(s.project.scene.camera,undefined);const camera=s.project.scene.entities.find(e=>e.camera);assert.equal(camera.camera.projection,dimension===2?'orthographic':'perspective');assert.equal(camera.audioListener.enabled,true);assert.equal(activeGameCamera(s.project.scene).entityId,camera.id);assert.ok(s.project.scene.entities.some(e=>dimension===2?e.light2D:e.light));assert.ok(s.project.scene.entities.some(e=>e.renderable));if(dimension===3)assert.deepEqual(s.project.scene.rendering.environment,[0,0,0]);const stored=await w.store.run('project.open',{id:s.project.id});assert.deepEqual(stored.project,s.project);
 const args=extra=>({id:w.project.id,expectedSceneRevision:w.revision,...extra});await w.run('scene.example.create',args({example:'Camera'}));const next=w.project.scene.entities.at(-1);assert.equal(w.project.scene.entities.filter(e=>e.camera?.active).length,1);assert.equal(w.project.scene.entities.find(e=>e.id===camera.id).audioListener.enabled,false);await w.run('scene.camera.set',args({entityId:camera.id,value:{...camera.camera,active:true}}));assert.equal(activeGameCamera(w.project.scene).entityId,camera.id);await w.run('scene.component.remove',args({entityId:camera.id,component:'Camera'}));assert.equal(activeGameCamera(w.project.scene),null);await w.run('scene.undo',args());assert.equal(activeGameCamera(w.project.scene).entityId,camera.id);assert.equal(next.camera.projection,dimension===2?'orthographic':'perspective');});
test('camera and audio listener follow parent position and camera rotation, independent of scale',()=>{const parent={id:'parent',transform:transform([3,4,5])},camera={id:'camera',parentId:'parent',transform:{...transform([0,0,6]),rotation:cameraRotation([0,0,6],[1,0,6]),scale:[2,2,2]},camera:{active:true,projection:'perspective',fov:60,orthoHeight:6},audioListener:{enabled:true}};const scene={cameraMode:'entities',entities:[parent,camera]};const c=activeGameCamera(scene),a=listenerPose(scene);assert.deepEqual(c.position,[3,4,11]);assert.ok(Math.abs(c.target[0]-4)<1e-6);assert.deepEqual(a.position,c.position);assert.ok(Math.abs(a.forward[0]-1)<1e-6);});
test('legacy lighting uniforms contain only authored directional lights and rotate their direction',()=>{assert.equal(legacyDirectionalUniforms({entities:[]}).count,0);const e={id:'light',transform:{...transform(),rotation:cameraRotation([0,0,1],[1,0,1])},light:{kind:'directional',direction:[0,0,-1],color:[1,.5,.25],intensity:2}};const l=legacyDirectionalUniforms({entities:[e]});assert.equal(l.count,1);assert.ok(Math.abs(l.data[0]-1)<1e-6);assert.equal(l.data[7],2);});

test('Create 2D Objects produces compatible alpha sprites inside a production 2D starter',async t=>{const w=await workspace(t);await w.run('project.create',{name:'2D geometry',dimension:2});for(const shape of ['square','disc','capsule','triangle']){await w.run('scene.primitive.create',{id:w.project.id,expectedSceneRevision:w.revision,dimension:2,shape});const e=w.project.scene.entities.at(-1);assert.equal(e.renderable.kind,'sprite');assert.equal(e.sprite2D.lit,true);assert.equal(w.project.scene.entities.some(e=>e.renderable?.kind==='mesh'),false);}});
