import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';
import {readSessionToken} from '../apps/editor/src/session-token.mjs';import {openEditor} from '../daemon/bootstrap/open-editor.mjs';import {FrameProfiler} from '../apps/editor/src/frame-profiler.mjs';import {dockDefaults} from '../apps/editor/src/dock-layout.mjs';
import {SceneWorkspace} from '../daemon/bootstrap/scene-workspace.mjs';import {ProjectStore} from '../daemon/bootstrap/project-store.mjs';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
test('token survives reload, remains per tab, and new bootstrap replaces it',()=>{const values=new Map(),storage={getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)},history={replaceState(...args){assert.equal(args[2],'/');}},location={hash:'#token=first',pathname:'/',search:''};assert.equal(readSessionToken(location,storage,history),'first');location.hash='';assert.equal(readSessionToken(location,storage,history),'first');assert.equal(readSessionToken(location,{getItem:()=>null},history),null);location.hash='#token=second';assert.equal(readSessionToken(location,storage,history),'second');assert.equal(readSessionToken(location,{setItem(){throw Error('disabled');}},history),'second');});
test('browser launcher uses platform executables and never invokes a shell',async()=>{for(const [platform,command]of [['win32','rundll32.exe'],['darwin','open'],['linux','xdg-open']]){const url='http://127.0.0.1:4317/#token=test';assert.equal(await openEditor(url,{platform,launch(cmd,args,options){assert.equal(cmd,command);assert.equal(args.at(-1),url);assert.equal(options.shell,false);const child=new EventEmitter();queueMicrotask(()=>child.emit('exit',0));return child;}}),true);}assert.equal(await openEditor('http://127.0.0.1:4317/',{launch(){const child=new EventEmitter();queueMicrotask(()=>child.emit('error',Error('missing')));return child;}}),false);assert.throws(()=>openEditor('https://example.com'),/local/);});
const lease={projectId:'test',workspaceId:null,sceneRevision:2,generation:4};
function populated(){const p=new FrameProfiler();p.reset(lease);for(let i=0;i<12;i++){const f=p.begin(i*200,'trace'+i,{view:'game',playing:true,route:'legacy'});p.scope(f,'worker.dispatch',0,i===11?140:1,'worker');p.finish(f,i*200+(i===11?141:2));}return p;}
test('Stop/reset archives exact immutable frames and preserves spike explanation',()=>{const p=populated(),sequence=p.history().items.at(-1).frameSequence,expected=p.explainFrameSpike({frameSequence:sequence});p.reset({...lease,sceneRevision:3,generation:5});assert.equal(p.history().retained,0);const capture=p.captures()[0],reader=FrameProfiler.fromCapture(JSON.parse(JSON.stringify(capture)));assert.deepEqual(reader.explainFrameSpike({frameSequence:sequence}),expected);capture.records[0].elapsedMs=10000;assert.notEqual(p.captures()[0].records[0].elapsedMs,10000);assert.equal(p.attachGpuTiming(sequence,1,[],4),false);});
test('capture archive is bounded to eight sessions and rejects altered provenance',()=>{const p=populated();for(let i=0;i<12;i++){p.reset({...lease,generation:i});const f=p.begin(0,'trace',{view:'game',playing:true,route:'legacy'});p.finish(f,1);}assert.equal(p.captures().length,8);const c=p.capture();c.records[0].generation=99;assert.throws(()=>FrameProfiler.fromCapture(c),/Invalid/);const c2=populated().capture();c2.records[0].elapsedMs=-1;assert.throws(()=>FrameProfiler.fromCapture(c2),/Invalid/);});
test('dock placement saves/reopens without changing authored scene or undo history',async t=>{const root=await mkdtemp(join(tmpdir(),'axiom-docks-'));t.after(()=>rm(root,{recursive:true,force:true}));const store=new ProjectStore(root),w=new SceneWorkspace(store);await w.run('project.create',{name:'Dock demo'});const args=data=>({id:w.project.id,expectedSceneRevision:w.revision,...data});await w.run('scene.entity.create',args({name:'Unsaved'}));const before=JSON.stringify(w.project.scene),revision=w.revision,history=w.past.length;const value={leftWidth:220,rightWidth:290,bottomHeight:250,docks:{...dockDefaults,inspector:'left',profiler:'top'}};await w.run('project.editor.update',args({value}));assert.equal(JSON.stringify(w.project.scene),before);assert.equal(w.revision,revision);assert.equal(w.past.length,history);const disk=(await store.run('project.open',{id:w.project.id})).project;assert.deepEqual(disk.editor,value);assert.equal(disk.scene.entities.length,0);await assert.rejects(w.run('project.editor.update',args({value:{...value,docks:{...value.docks,profiler:'invalid'}}})),/Invalid/);});

import {EditorBridge} from '../daemon/bootstrap/agent/editor-bridge.mjs';
test('reload release frees the renderer lease and rejects late reports from the old tab',async()=>{const w={project:{id:'p'},revision:1,workspaceId:null,snapshot:()=>({})},b=new EditorBridge(w,()=>{});const old={clientId:'11111111-1111-4111-8111-111111111111',sceneRevision:1,status:{projectId:'p',sceneRevision:1,generation:1,renderer:'null'}};b.sync(old);const pending=b.profiler({id:'p',expectedSceneRevision:1});assert.equal(b.release('22222222-2222-4222-8222-222222222222'),false);assert.equal(b.status().connected,true);assert.equal(b.release(old.clientId),true);await assert.rejects(pending,/closed/);assert.equal(b.status().connected,false);b.sync({...old,clientId:'22222222-2222-4222-8222-222222222222'});assert.throws(()=>b.sync(old),/released/);assert.equal(b.status().clientId,'22222222-2222-4222-8222-222222222222');b.close();});
