import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {primitiveGlb} from '../engine/scene/primitives.mjs';import {orderEntities,groupTransforms,updateTransforms,hierarchyRows,rangeSelection} from '../engine/scene/editor-operations.mjs';import {worldTransforms} from '../engine/scene/hierarchy.mjs';import {axisQuaternion} from '../engine/renderer/render-math.mjs';import {SceneWorkspace} from '../daemon/bootstrap/scene-workspace.mjs';import {ProjectStore} from '../daemon/bootstrap/project-store.mjs';
const e=(id,x=0)=>({id:`entity://00000000-0000-4000-8000-${String(id).padStart(12,'0')}`,name:'Entity '+id,transform:{position:[x,0,0],rotation:[0,0,0,1],scale:[1,1,1]}});
const near=(a,b)=>a.forEach((v,i)=>assert.ok(Math.abs(v-b[i])<1e-6));
test('every closed primitive triangle points outward including sphere/capsule poles',()=>{for(const shape of ['cube','sphere','cylinder','capsule','pyramid']){const glb=primitiveGlb(3,shape),len=glb.readUInt32LE(12),doc=JSON.parse(glb.subarray(20,20+len)),start=28+len;const positions=doc.accessors[0];for(let i=0;i<positions.count;i+=3){const center=[0,0,0],normal=[0,0,0];for(let v=0;v<3;v++)for(let j=0;j<3;j++){center[j]+=glb.readFloatLE(start+(i+v)*12+j*4)/3;normal[j]+=glb.readFloatLE(start+doc.bufferViews[1].byteOffset+(i+v)*12+j*4)/3;}assert.ok(center.reduce((sum,v,j)=>sum+v*normal[j],0)>0,shape+' inward triangle '+i);}}});
test('sibling insertion and root drop retain world transforms and chosen source order',()=>{const a=e(1,4),b=e(2,1),c=e(3,2),d=e(4,3);b.parentId=a.id;const source=[a,b,c,d],before=worldTransforms(source);const result=orderEntities(source,[b.id,d.id],null,c.id);assert.deepEqual(result.map(e=>e.id),[a.id,b.id,d.id,c.id]);assert.equal(result[1].parentId,undefined);near(worldTransforms(result).get(b.id).position,before.get(b.id).position);assert.throws(()=>orderEntities(source,[a.id],b.id),/descendants/);assert.throws(()=>orderEntities(source,[d.id],null,b.id),/insertion/);});
test('batch group move/rotate/scale works with selected parent and child without double transform',()=>{const a=e(1),b=e(2,2),c=e(3,5);b.parentId=a.id;const source=[a,b,c];const moved=updateTransforms(source,groupTransforms(source,[a.id,b.id,c.id],[0,0,0],{position:[3,1,0]}),'world');near(worldTransforms(moved).get(b.id).position,[5,1,0]);near(worldTransforms(moved).get(c.id).position,[8,1,0]);const rotated=updateTransforms(source,groupTransforms(source,[a.id,b.id,c.id],[0,0,0],{rotation:axisQuaternion([0,0,1],Math.PI/2)}),'world');near(worldTransforms(rotated).get(b.id).position,[0,2,0]);near(worldTransforms(rotated).get(c.id).position,[0,5,0]);const scaled=updateTransforms(source,groupTransforms(source,[a.id,b.id,c.id],[0,0,0],{scale:[2,2,2]}),'world');near(worldTransforms(scaled).get(b.id).position,[4,0,0]);near(worldTransforms(scaled).get(c.id).position,[10,0,0]);assert.throws(()=>updateTransforms(source,[{entityId:a.id,transform:a.transform},{entityId:'missing',transform:a.transform}]),/exists/);});
test('Shift range follows visible preorder and skips collapsed children',()=>{const a=e(1),b=e(2),c=e(3),d=e(4);b.parentId=a.id;near(rangeSelection(hierarchyRows([a,b,c,d],new Set([a.id])),a.id,d.id).map(id=>[a.id,c.id,d.id].indexOf(id)),[0,1,2]);assert.deepEqual(rangeSelection(hierarchyRows([a,b,c,d]),d.id,b.id),[b.id,c.id,d.id]);});
test('layout persists without publishing dirty scene; atomic batch changes undo/save/reopen',async t=>{const root=await mkdtemp(join(tmpdir(),'axiom-layout-'));t.after(()=>rm(root,{recursive:true,force:true}));const store=new ProjectStore(root),w=new SceneWorkspace(store);await w.run('project.create',{name:'Layout'});const args=data=>({id:w.project.id,expectedSceneRevision:w.revision,...data});await w.run('scene.entity.create',args({name:'Unsaved entity'}));const count=w.past.length,layout={leftWidth:280,rightWidth:340,bottomHeight:260};await w.run('project.editor.update',args({value:layout}));const disk=(await store.run('project.open',{id:w.project.id})).project;assert.deepEqual(disk.editor,layout);assert.equal(disk.scene.entities.length,0);assert.equal(w.project.scene.entities.length,1);assert.equal(w.dirty,true);assert.equal(w.past.length,count);await assert.rejects(w.run('project.editor.update',args({value:{...layout,leftWidth:0}})),/Invalid/);await w.run('scene.entity.create',args({name:'Second'}));const ids=w.project.scene.entities.map(e=>e.id),before=structuredClone(w.project.scene);await w.run('scene.entities.update',args({updates:w.project.scene.entities.map(e=>({entityId:e.id,transform:{...e.transform,position:[3,2,1]}}))}));await w.run('scene.undo',args());assert.deepEqual(w.project.scene,before);await w.run('scene.redo',args());await w.run('scene.entities.delete',args({entityIds:ids}));assert.equal(w.project.scene.entities.length,0);await w.run('scene.undo',args());await w.run('scene.save',args());assert.deepEqual((await store.run('project.open',{id:w.project.id})).project.editor,layout);});

import {primitiveGlb as legacyGlb} from './fixtures/legacy-primitives.mjs';import {decodeAsset} from '../engine/assets/import.mjs';
test('existing M9.1 sphere/capsule immutable sources are repaired during derived import',()=>{for(const shape of ['sphere','capsule']){const bytes=legacyGlb(3,shape),original=Buffer.from(bytes),resource=decodeAsset(bytes);assert.deepEqual(bytes,original);assert.match(resource.warnings.at(-1),/Corrected/);for(const p of resource.primitives)for(let i=0;i<p.vertices.length;i+=8)assert.ok(p.vertices.slice(i,i+3).reduce((sum,v,j)=>sum+v*p.vertices[i+3+j],0)>0);}});

import {readFile} from 'node:fs/promises';
test('editor IDs remain unique after moving Inspector components and menus',async()=>{const html=await readFile(new URL('../apps/editor/index.html',import.meta.url),'utf8'),ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);assert.ok(html.indexOf('id="entity-form"')<html.indexOf('id="add-component"'));});
