import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {GameTestSession,validateTest,assertRuntime} from '../engine/testing/session.mjs';import {createM14Demos} from '../demos/create-m14-projects.mjs';import {SceneWorkspace} from '../daemon/bootstrap/scene-workspace.mjs';import {ProjectStore} from '../daemon/bootstrap/project-store.mjs';
const id='entity://11111111-1111-4111-8111-111111111111',other='entity://22222222-2222-4222-8222-222222222222';
function rig(){let x=0,ended=0,steps=0;const session=new GameTestSession({async begin(){x=0;},async step({delta,keys}){steps++;if(keys.includes('ArrowRight'))x+=delta*2;},state:async()=>({entities:[{id,transform:{position:[x,0,0],rotation:[0,0,0,1]}}],contacts:[{a:id,b:other,trigger:true}],animation:[{entityId:id,state:'Walk'}],pixels:{'5,5':[6,9,14,255]}}),async end(){ended++;}});return {session,end:()=>ended,steps:()=>steps};}
const suite={name:'fixed input',steps:[{frames:30,keys:['ArrowRight'],assertions:[{kind:'position',entityId:id,value:[1,0,0],tolerance:.001},{kind:'collision',entityId:id,otherId:other,trigger:true},{kind:'animation',entityId:id,state:'Walk'},{kind:'pixel',x:5,y:5,rgba:[6,9,14,255]}]}]};
test('fixed delta/input produces identical assertions and restores the adapter after every run',async()=>{const r=rig();r.session.control({action:'run',suite});await r.session.flight;const a=r.session.result();assert.equal(a.status,'completed');assert.equal(a.frames,30);assert.ok(a.results.every(i=>i.passed));r.session.control({action:'run',suite});await r.session.flight;assert.deepEqual(r.session.result().results,a.results);assert.equal(r.end(),2);});
test('manual frame step pauses without extra simulation and ends explicitly',async()=>{const r=rig();r.session.control({action:'begin',suite});await r.session.flight;assert.equal(r.steps(),0);assert.equal(r.session.result().status,'paused');r.session.control({action:'step',step:suite.steps[0]});await r.session.flight;assert.equal(r.steps(),30);assert.equal(r.session.result().status,'paused');r.session.control({action:'finish'});await r.session.flight;assert.equal(r.end(),1);});
test('known failing assertions and Null pixels are honest failures, never fabricated passes',async()=>{const r=rig();r.session.control({action:'run',suite:{name:'known failure',steps:[{frames:0,assertions:[{kind:'entityCount',count:99}]}]}});await r.session.flight;assert.equal(r.session.result().status,'failed');assert.equal(r.end(),1);const v=assertRuntime({kind:'pixel',x:1,y:1,rgba:[0,0,0,255]},{pixels:null});assert.equal(v.passed,false);assert.match(v.reason,/Null/);});
test('schema, required assertion fields, total budgets and concurrent sessions reject invalid plans',async()=>{const r=rig();assert.throws(()=>validateTest({...suite,eval:'code'}),/Invalid/);assert.throws(()=>r.session.control({action:'run',suite:{name:'budget',steps:Array.from({length:6},()=>({frames:120}))}}),/budget/);assert.throws(()=>r.session.control({action:'run',suite:{name:'bad',steps:[{frames:1,assertions:[{kind:'position'}]}]}}),/Assertion/);r.session.control({action:'begin',suite});assert.throws(()=>r.session.control({action:'run',suite}),/active/);await r.session.flight;r.session.control({action:'cancel'});await r.session.flight;assert.equal(r.end(),1);assert.equal(r.session.result().status,'cancelled');});
test('cancel and runtime failure always release simulated input/runtime',async()=>{let release=0,entered;const hold=new Promise(r=>entered=r);const session=new GameTestSession({begin:async()=>{},step:()=>hold,state:async()=>({entities:[],contacts:[],animation:[]}),end:async()=>{release++;}});session.control({action:'run',suite:{name:'cancel',steps:[{frames:10}]}});await new Promise(r=>setTimeout(r,1));session.control({action:'cancel'});entered();await session.flight;assert.equal(session.result().status,'cancelled');assert.equal(release,1);const broken=new GameTestSession({begin:async()=>{throw Error('stale generation');},end:async()=>{release++;}});broken.control({action:'run',suite});await broken.flight;assert.equal(broken.result().status,'failed');assert.equal(release,2);});
test('M14 demo suites persist through canonical editor settings and preserve existing projects',async t=>{const root=await mkdtemp(join(tmpdir(),'axiom-m14-demos-'));t.after(()=>rm(root,{recursive:true,force:true}));const w=new SceneWorkspace(new ProjectStore(root));await w.run('project.create',{name:'Keep'});const demos=await createM14Demos(root);assert.equal((await w.store.run('project.list',{})).projects.length,3);for(const d of demos){const p=(await w.store.run('project.open',{id:d.id})).project;assert.equal(p.editor.gameTests.length,3);p.editor.gameTests.forEach(s=>validateTest(s));assert.equal(p.scene.entities.length,d.floorId?2:1);} });
import {EditorBridge} from '../daemon/bootstrap/agent/editor-bridge.mjs';
test('public test bridge is revision scoped and releases pending controls on disconnect',async()=>{const w={project:{id:'p'},revision:3,workspaceId:null,snapshot:()=>({})},b=new EditorBridge(w,()=>{}),clientId='33333333-3333-4333-8333-333333333333',status={projectId:'p',sceneRevision:3,generation:1,renderer:'null'};b.sync({clientId,sceneRevision:3,status});const p=b.gameTest({id:'p',expectedSceneRevision:3,action:'query'}),request=b.sync({clientId,sceneRevision:3,status}).gameTest;assert.equal(request.action,'query');b.sync({clientId,sceneRevision:3,status,gameTest:{requestId:request.requestId,value:{status:'paused',frames:30}}});assert.equal((await p).frames,30);assert.throws(()=>b.gameTest({id:'p',expectedSceneRevision:2,action:'query'}),/revision/);const pending=b.gameTest({id:'p',expectedSceneRevision:3,action:'cancel'});b.release(clientId);await assert.rejects(pending,/closed/);});
test('quick-create modular examples are atomic/undoable and unavailable assets fail without mutation',async t=>{const root=await mkdtemp(join(tmpdir(),'axiom-examples-'));t.after(()=>rm(root,{recursive:true,force:true}));const w=new SceneWorkspace(new ProjectStore(root));await w.run('project.create',{name:'Examples'});const args=example=>({id:w.project.id,expectedSceneRevision:w.revision,example});await assert.rejects(w.run('scene.example.create',args('Audio Source')),/PCM WAV/);assert.equal(w.project.scene.entities.length,0);await w.run('scene.example.create',args('Point Light'));assert.equal(w.project.scene.entities[0].light.kind,'point');assert.ok(w.project.scene.rendering);await w.run('scene.undo',{id:w.project.id,expectedSceneRevision:w.revision});assert.equal(w.project.scene.entities.length,0);await w.run('scene.example.create',args('UI Button'));assert.equal(w.project.scene.entities[0].ui2D.action,'togglePause');assert.ok(w.project.scene.twoD);});
