import {applyRuntimeEdit} from '../engine/scene/runtime-edit.mjs';
import {activeGameCamera,legacyDirectionalUniforms} from '../engine/scene/camera.mjs';
import {ReplaySession,replayError} from '../engine/replay/session.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {webcrypto} from 'node:crypto';
import {GameTestSession,testError} from '../engine/testing/session.mjs';
import {parallelView} from '../apps/editor/src/parallel-view.mjs';
import {createAudioSession} from '../apps/editor/src/audio-session.mjs';
import {createGpuProfiler} from '../apps/editor/src/gpu-profiler.mjs';
import {FrameProfiler} from '../apps/editor/src/frame-profiler.mjs';
import {loadKernel,scenePrimitives} from '../engine/wasm/host.mjs';
import {worldScene} from '../engine/scene/hierarchy.mjs';
import {cameraMatrix,matrixMultiply,modelMatrix,clipVisible,collapsedGeometry} from '../apps/editor/src/view-math.mjs';
import {DecisionEvidence} from '../apps/editor/src/causal-diagnostics.mjs';
const bytes=await readFile(new URL('../target/wasm32-unknown-unknown/release/axiom_wasm.wasm',import.meta.url));
const source=(await readFile(new URL('../apps/editor/src/scene-renderer.mjs',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'').replace('export async function createSceneRenderer','async function createSceneRenderer');
const entity='entity://11111111-1111-4111-8111-111111111111',floor='entity://22222222-2222-4222-8222-222222222222',id='project://33333333-3333-4333-8333-333333333333';
async function rig(){const callbacks=[],errors=[];const context=vm.createContext({applyRuntimeEdit,activeGameCamera,legacyDirectionalUniforms,ReplaySession,replayError,GameTestSession,testError,parallelView,createAudioSession,createGpuProfiler,FrameProfiler,loadKernel,scenePrimitives,worldScene,cameraMatrix,matrixMultiply,modelMatrix,clipVisible,collapsedGeometry,DecisionEvidence,crypto:webcrypto,performance,structuredClone,TextEncoder,setTimeout,clearTimeout,addEventListener(){},removeEventListener(){},requestAnimationFrame(fn){callbacks.push(fn);return callbacks.length;},cancelAnimationFrame(){}});vm.runInContext(source,context);const renderer=await context.createSceneRenderer({canvas:{dataset:{},width:960,height:540,addEventListener(){},removeEventListener(){}},stateElement:{},traceOutput:{},bytes,gpu:null,forceNull:true,loadAsset:async()=>{},reportError:e=>errors.push(e.message)});const transform=p=>({position:p,rotation:[0,0,0,1],scale:[1,1,1]}),collider={dimension:3,shape:'box',halfExtents:[.5,.5,.5],trigger:false,layer:1,mask:4294967295};const snapshot={project:{id,name:'Runtime tests',scene:{entities:[{id:entity,name:'Cube',transform:transform([0,2,0]),collider,rigidBody:{mass:1,velocity:[0,0,0],angularVelocity:[0,0,0],restitution:0,friction:.5,gravityScale:1}},{id:floor,name:'Floor',transform:transform([0,-1,0]),collider:{...collider,halfExtents:[3,.5,3]}}],camera:{position:[0,0,6],target:[0,0,0],projection:'perspective',fov:60,orthoHeight:6}}},sceneRevision:1,workspaceId:null,playing:false};await renderer.setSnapshot(snapshot);return {renderer,snapshot,callbacks,errors};}
async function until(renderer,status){const end=Date.now()+5000;while(Date.now()<end){const s=renderer.testStatus();if(status.includes(s.status))return s;await new Promise(r=>setTimeout(r,1));}throw Error(JSON.stringify(renderer.testStatus()));}
const suite={name:'Real Rust contact',steps:[{frames:120,assertions:[{kind:'collision',entityId:entity,otherId:floor,expected:true},{kind:'entityCount',count:2}]}]};
test('isolated renderer stepping runs real Wasm physics, suspends RAF and restores authored transforms',async()=>{const r=await rig();try{const original=JSON.stringify(r.snapshot),args={id,expectedSceneRevision:1};r.renderer.gameTestControl({...args,action:'begin',suite});await until(r.renderer,['paused']);await r.callbacks.shift()(100);assert.equal(r.renderer.testStatus().frames,0);r.renderer.gameTestControl({...args,action:'step',step:suite.steps[0]});const paused=await until(r.renderer,['paused','failed']);assert.equal(paused.status,'paused',JSON.stringify(paused));assert.equal(paused.frames,120);assert.ok(paused.results.every(a=>a.passed));assert.ok(r.renderer.interaction().scene.entities[0].transform.position[1]<1);r.renderer.gameTestControl({...args,action:'finish'});assert.equal((await until(r.renderer,['completed','failed'])).status,'completed');assert.equal(r.renderer.interaction().scene.entities[0].transform.position[1],2);assert.equal(JSON.stringify(r.snapshot),original);assert.deepEqual(r.errors,[]);}finally{r.renderer.dispose();}});
test('an external snapshot cancels a paused test without restoring obsolete project state',async()=>{const r=await rig();try{r.renderer.gameTestControl({id,expectedSceneRevision:1,action:'begin',suite});await until(r.renderer,['paused']);const next=structuredClone(r.snapshot);next.sceneRevision=2;next.project.scene.entities[0].transform.position=[7,8,9];await r.renderer.setSnapshot(next);assert.equal((await until(r.renderer,['cancelled'])).status,'cancelled');assert.deepEqual(Array.from(r.renderer.interaction().scene.entities[0].transform.position),[7,8,9]);assert.equal(r.renderer.status().sceneRevision,2);assert.equal(r.renderer.status().playing,false);r.renderer.gameTestControl({id,expectedSceneRevision:2,action:'run',suite:{name:'Next revision',steps:[{frames:1,assertions:[{kind:'entityCount',count:2}]}]}});assert.equal((await until(r.renderer,['completed','failed'])).status,'completed');assert.deepEqual(r.errors,[]);}finally{r.renderer.dispose();}});
test('real Wasm replay reconstructs frame ranges and verifies physics checkpoints without authoring changes',async()=>{const r=await rig();const args={id,expectedSceneRevision:1};async function done(){const end=Date.now()+5000;while(Date.now()<end){const s=r.renderer.replayStatus();if(['completed','failed','cancelled'].includes(s.status))return s;await new Promise(r=>setTimeout(r,1));}throw Error('Replay timeout');}try{r.renderer.replayControl({...args,action:'record',seed:42,suite:{name:'Recorded fall',steps:[{frames:120}]}});let result=await done();assert.equal(result.status,'completed',JSON.stringify(result));assert.deepEqual(Array.from(result.recording.checkpoints),[0,60,120]);r.renderer.replayControl({...args,action:'replay',from:60,to:120});result=await done();assert.equal(result.status,'completed',JSON.stringify(result));assert.equal(result.verifiedCheckpoints,3);assert.ok(result.diagnostics.length);assert.deepEqual(Array.from(r.renderer.interaction().scene.entities[0].transform.position),[0,2,0]);assert.deepEqual(r.errors,[]);}finally{r.renderer.dispose();}});

test('ordinary Play runtime edits update real Wasm without changing authored snapshots and reset on Stop',async()=>{const r=await rig();try{const playing=structuredClone(r.snapshot);playing.playing=true;playing.sceneRevision=2;await r.renderer.setSnapshot(playing);await r.renderer.editRuntime({type:'scene.entity.update',data:{entityId:entity,transform:{position:[3,4,0]}}});assert.deepEqual(Array.from(r.renderer.interaction().scene.entities[0].transform.position),[3,4,0]);assert.deepEqual(playing.project.scene.entities[0].transform.position,[0,2,0]);await assert.rejects(r.renderer.editRuntime({type:'scene.entity.delete',data:{entityId:entity}}),/Unsupported/);await r.renderer.setSnapshot(r.snapshot);assert.deepEqual(Array.from(r.renderer.interaction().scene.entities[0].transform.position),[0,2,0]);await assert.rejects(r.renderer.editRuntime({type:'scene.entity.update',data:{entityId:entity,name:'x'}}),/ordinary Play/);}finally{r.renderer.dispose();}});

test('saving source revisions during Play preserves the runtime generation and archives profiler provenance',async()=>{const r=await rig();try{const playing=structuredClone(r.snapshot);playing.playing=true;playing.sceneRevision=2;await r.renderer.setSnapshot(playing);await r.callbacks.shift()(100);const before=r.renderer.status();await r.renderer.editRuntime({type:'scene.entity.update',data:{entityId:entity,transform:{position:[3,4,0]}}});const saved=structuredClone(playing);saved.sceneRevision=3;saved.project.scene.projectFiles=[{kind:'script',path:'Scripts/New.cs',text:'// saved source'}];await r.renderer.setSnapshot(saved);assert.equal(r.renderer.status().generation,before.generation);assert.deepEqual(Array.from(r.renderer.interaction().scene.entities[0].transform.position),[3,4,0]);await r.callbacks.shift()(120);assert.equal(r.renderer.status().profiler.sceneRevision,3);const captures=r.renderer.profilerCaptures();assert.ok(captures.some(c=>c.lease.sceneRevision===2));for(const c of captures)FrameProfiler.fromCapture(c);}finally{r.renderer.dispose();}});
