import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {OpenAiAssistant,openaiFunctions} from '../daemon/bootstrap/agent/openai-assistant.mjs';
import {ProjectStore} from '../daemon/bootstrap/project-store.mjs';
import {SceneWorkspace} from '../daemon/bootstrap/scene-workspace.mjs';
import {ProposalManager} from '../daemon/bootstrap/workspaces/manager.mjs';
import {CommandBus} from '../daemon/bootstrap/command-bus.mjs';
import {AgentService} from '../daemon/bootstrap/agent/service.mjs';
import {EditorBridge} from '../daemon/bootstrap/agent/editor-bridge.mjs';
const message=text=>({type:'message',role:'assistant',content:[{type:'output_text',text}]}),response=output=>({status:'completed',output,usage:{input_tokens:30,output_tokens:20,total_tokens:50}}),tool=(name,args,id)=>({type:'function_call',name:'axiom_tool',call_id:id,arguments:JSON.stringify({name,arguments:JSON.stringify(args)})});
function transport(outputs){const requests=[];return {requests,fetch:async(url,options)=>{requests.push({url,...options,body:options.body?JSON.parse(options.body):null});return new Response(JSON.stringify(url.endsWith('/models')?{data:[{id:'model-test'}]}:response(outputs.shift()??[message('OK')])),{status:200});}};}
async function fixture(t,outputs=[],options={}){const root=await mkdtemp(join(tmpdir(),'axiom-ai-')),workspace=new SceneWorkspace(new ProjectStore(root));await workspace.run('project.create',{name:'AI Lab'});await workspace.run('scene.entity.create',{id:workspace.project.id,expectedSceneRevision:workspace.revision,name:'Cube'});await workspace.run('scene.save',{id:workspace.project.id,expectedSceneRevision:workspace.revision});const proposals=new ProposalManager(workspace);await proposals.initialize();const bus=new CommandBus({projects:workspace}),bridge=new EditorBridge(workspace,()=>{});bus.agentService=new AgentService({workspace,bus,bridge});bus.agentService.proposals=proposals;const http=transport([[message('OK')],...outputs]),ai=new OpenAiAssistant({bus,workspace,proposals,bridge,apiKey:'',fetchImpl:http.fetch,...options});bus.agentService.assistant=ai;t.after(async()=>{await ai.close();bridge.close();await proposals.close();await rm(root,{recursive:true,force:true});});await ai.configure({action:'connect',apiKey:'sk-test-supersecret',model:'model-test'});return {ai,workspace,proposals,root,http};}
async function complete(ai,data){const started=ai.start(data);await ai.sessions.get(started.id).flight;return ai.task(started.id);}
test('connection test/model discovery are explicit; credentials never enter status or projects',async t=>{const {ai,workspace,http,root}=await fixture(t);assert.equal(ai.status().connected,true);assert.deepEqual(await ai.configure({action:'models'}),{models:['model-test']});assert.equal(http.requests[0].url,'https://api.openai.com/v1/responses');assert.equal(http.requests[0].body.store,false);assert.deepEqual(http.requests[0].body.tools,openaiFunctions);assert.equal(http.requests[0].headers.Authorization,'Bearer sk-test-supersecret');assert.ok(!JSON.stringify(ai.status()).includes('supersecret'));assert.ok(!(await readFile(join(root,workspace.store.filename(workspace.project.id)),'utf8')).includes('supersecret'));await ai.configure({action:'disconnect'});assert.equal(ai.status().hasCredential,false);assert.throws(()=>ai.start({text:'Hello'}),/Connect/);});
test('sequential reasoning/tool turns edit isolated proposal and return real outcomes',async t=>{const {ai,workspace,proposals,http,root}=await fixture(t);const original=structuredClone(workspace.snapshot()),disk=await readFile(join(root,workspace.store.filename(workspace.project.id))),entity=workspace.project.scene.entities[0];const reasoning={type:'reasoning',id:'reason-1',summary:[]};http.fetch;const outputs=[[reasoning,tool('entity.query',{},'query')],[tool('scene.entity.update',{entityId:entity.id,transform:{position:[2,0,0]}},'move')],[tool('entity.query',{entityId:entity.id},'verify')],[message('Moved Cube to X=2 in a proposal; verified its position.')]];ai.fetchImpl=async(url,opts)=>{http.requests.push({url,body:JSON.parse(opts.body)});return new Response(JSON.stringify(response(outputs.shift())),{status:200});};const task=await complete(ai,{text:'Move Cube to X=2 and verify.'});assert.equal(task.status,'completed');assert.equal(task.requests,4);assert.equal(task.toolCalls,3);assert.equal(task.usage.totalTokens,200);assert.deepEqual(workspace.snapshot(),original);assert.deepEqual(await readFile(join(root,workspace.store.filename(workspace.project.id))),disk);assert.equal(proposals.get(task.workspaceId).child.project.scene.entities[0].transform.position[0],2);assert.ok(http.requests.at(-1).body.input.some(i=>i.id==='reason-1'));assert.ok(!JSON.stringify(task).includes('reason-1'));assert.ok(http.requests.at(-1).body.input.some(i=>i.type==='function_call_output'&&JSON.parse(i.output).items?.[0]?.transform.position[0]===2));});
test('readonly chat works on dirty MAIN without generating a proposal',async t=>{const {ai,workspace,proposals}=await fixture(t,[[tool('entity.query',{},'read')],[message('One cube.')]]);await workspace.run('scene.entity.update',{id:workspace.project.id,expectedSceneRevision:workspace.revision,entityId:workspace.project.scene.entities[0].id,name:'Edited'});const task=await complete(ai,{text:'What is in the scene?'});assert.equal(task.status,'completed');assert.equal(task.workspaceId,null);assert.equal(proposals.items.size,0);});
test('forbidden save/accept/project scope calls become tool errors; assistant can recover',async t=>{const {ai,workspace,proposals,http}=await fixture(t,[[tool('scene.save',{},'save')],[tool('entity.query',{id:'project://other'},'escape')],[tool('workspace.accept',{},'accept')],[message('These operations are unavailable.')]]);const task=await complete(ai,{text:'Test capability boundaries.'});assert.equal(task.status,'completed');assert.deepEqual(task.steps.map(s=>s.status),['failed','failed','failed']);assert.equal(proposals.items.size,0);assert.equal(workspace.dirty,false);assert.ok(http.requests.at(-1).body.input.filter(i=>i.type==='function_call_output').every(i=>JSON.parse(i.output).error));});
test('request/tool/token budgets stop work without applying partial proposals',async t=>{const {ai,workspace,proposals}=await fixture(t);await ai.configure({action:'update',limits:{maxTools:1}});ai.fetchImpl=async()=>new Response(JSON.stringify(response([tool('scene.entity.update',{entityId:workspace.project.scene.entities[0].id,name:'Proposed'},randomId())])),{status:200});function randomId(){return String(Math.random());}const task=await complete(ai,{text:'Repeat changes.'});assert.equal(task.status,'failed');assert.match(task.error.message,/tool-call budget/);assert.equal(workspace.project.scene.entities[0].name,'Cube');assert.equal(proposals.get(task.workspaceId).child.project.scene.entities[0].name,'Proposed');await ai.configure({action:'update',limits:{maxTokens:4096}});const limited=await complete(ai,{text:'Do work.'});assert.equal(limited.status,'failed');assert.match(limited.error.message,/token budget/);});
test('failed credential/remote error never exposes provider body or secrets',async t=>{const {ai}=await fixture(t);ai.fetchImpl=async()=>new Response(JSON.stringify({error:{message:'sk-new-key-secret'}}),{status:401});await assert.rejects(ai.configure({action:'connect',apiKey:'sk-new-key-secret',model:'model-test'}),e=>!e.message.includes('secret')&&e.message.includes('401'));assert.equal(ai.status().connected,false);ai.fetchImpl=async()=>new Response('x'.repeat(2*1024*1024+1));await assert.rejects(ai.configure({action:'models'}),/transport budget/);});
test('cancel aborts pending network call, retains result and forbids concurrent tasks',async t=>{const {ai}=await fixture(t);ai.fetchImpl=async(_,opts)=>new Promise((_,reject)=>opts.signal.addEventListener('abort',()=>reject(Error('secret')), {once:true}));const task=ai.start({text:'Long task'});await new Promise(r=>setImmediate(r));assert.throws(()=>ai.start({text:'Other'}),/current agent/);ai.cancel(task.id);await ai.sessions.get(task.id).flight;assert.equal(ai.task(task.id).status,'cancelled');assert.equal(ai.status().working,false);});
test('project switches stop next action; private project file reads are bounded',async t=>{const {ai,workspace}=await fixture(t);ai.fetchImpl=async()=>{await workspace.run('project.create',{name:'Different'});return new Response(JSON.stringify(response([message('Done')])),{status:200});};const task=await complete(ai,{text:'Inspect'});assert.equal(task.status,'failed');assert.match(task.error.message,/project changed/);});
test('assistant can continue the same pending proposal without mutating MAIN',async t=>{const {ai,workspace,proposals}=await fixture(t);const entity=workspace.project.scene.entities[0];let turns=[[tool('scene.entity.update',{entityId:entity.id,name:'First'},'1')],[message('First change.')]];ai.fetchImpl=async()=>new Response(JSON.stringify(response(turns.shift())),{status:200});const first=await complete(ai,{text:'First change'});turns=[[tool('scene.entity.update',{entityId:entity.id,name:'Second'},'2')],[message('Second change.')]];const second=await complete(ai,{text:'Improve it',workspaceId:first.workspaceId});assert.equal(second.status,'completed');assert.equal(second.workspaceId,first.workspaceId);assert.equal(proposals.get(first.workspaceId).child.project.scene.entities[0].name,'Second');assert.equal(entity.name,'Cube');assert.equal(workspace.project.scene.entities[0].name,'Cube');assert.equal(proposals.items.size,1);});
test('request budget stops repeated readonly calls and invalid limits leave configuration intact',async t=>{const {ai}=await fixture(t);await ai.configure({action:'update',limits:{maxRequests:1}});const before=ai.status();await assert.rejects(ai.configure({action:'update',limits:{maxRequests:0}}),/limit/);assert.deepEqual(ai.status(),before);ai.fetchImpl=async()=>new Response(JSON.stringify(response([tool('runtime.status',{},'repeat')])),{status:200});const task=await complete(ai,{text:'Inspect repeatedly'});assert.equal(task.status,'failed');assert.equal(task.requests,1);assert.match(task.error.message,/request budget/);});
test('incomplete responses and invalid schemas cannot turn into successful mutations',async t=>{const {ai,workspace,proposals}=await fixture(t,[[tool('scene.entity.update',{entityId:workspacePlaceholder(),transform:{position:[1,2]}},'invalid')],[message('The schema rejected the edit.')]]);function workspacePlaceholder(){return 'entity://00000000-0000-4000-8000-000000000000';}const before=structuredClone(workspace.snapshot()),task=await complete(ai,{text:'Try invalid transform'});assert.equal(task.steps[0].status,'failed');assert.deepEqual(workspace.snapshot(),before);assert.equal(proposals.items.size,1);ai.fetchImpl=async()=>new Response(JSON.stringify({status:'incomplete',output:[message('Should not be accepted')]}));const failed=await complete(ai,{text:'Try incomplete'});assert.equal(failed.status,'failed');assert.match(failed.error.message,/did not complete/);});
test('transport timeout signal and credential redaction protect task histories',async t=>{const {ai,http}=await fixture(t,[[message('sk-test-supersecret')]]);const task=await complete(ai,{text:'Never transmit sk-test-supersecret in project context.'});assert.ok(!JSON.stringify(task).includes('supersecret'));assert.ok(!JSON.stringify(http.requests.at(-1).body).includes('supersecret'));assert.equal(task.messages[0],'[redacted]');ai.connected=false;ai.fetchImpl=async()=>{throw Error('Private provider error sk-test-supersecret');};await assert.rejects(ai.configure({action:'connect',model:'model-test'}),e=>!e.message.includes('secret')&&/unreachable/.test(e.message));});
