import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {SceneWorkspace} from '../daemon/bootstrap/scene-workspace.mjs';import {ProjectStore} from '../daemon/bootstrap/project-store.mjs';import {validateProject} from '../protocol/src/project-document.mjs';import {applyScriptOperations} from '../engine/scripting/operations.mjs';
test('physics components validate, undo and persist through authoring',async t=>{
 const root=await mkdtemp(join(tmpdir(),'axiom-physics-'));t.after(()=>rm(root,{recursive:true,force:true}));const w=new SceneWorkspace(new ProjectStore(root));await w.run('project.create',{name:'Physics'});const args=()=>({id:w.project.id,expectedSceneRevision:w.revision});await w.run('scene.entity.create',{...args(),name:'Ball'});const entityId=w.project.scene.entities[0].id;
 await w.run('scene.collider.set',{...args(),entityId,value:{dimension:2,shape:'sphere',halfExtents:[0.5,0.5,0.5],trigger:false,layer:1,mask:0xffffffff}});await w.run('scene.rigidBody.set',{...args(),entityId,value:{mass:1,velocity:[0,0,0],restitution:0.2,friction:0.5,gravityScale:1}});await w.run('scene.save',args());const saved=await w.store.run('project.open',{id:w.project.id});assert.deepEqual(saved.project.scene,w.project.scene);
 for(const [field,value]of [['trigger','yes'],['mask',4294967296]]){const bad=structuredClone(w.project);bad.scene.entities[0].collider[field]=value;assert.throws(()=>validateProject(bad),/Invalid/);}
 await w.run('scene.component.remove',{...args(),entityId,component:'Collider'});assert.equal(w.project.scene.entities[0].rigidBody,undefined);await w.run('scene.save',args());assert.equal((await w.store.run('project.open',{id:w.project.id})).project.scene.entities[0].collider,undefined);await w.run('scene.undo',args());assert.ok(w.project.scene.entities[0].rigidBody);
 const result=applyScriptOperations(w.project.scene,{generation:1,operations:[{kind:'velocity',id:entityId,position:[2,3,0]}]},1);assert.deepEqual(result.velocities.get(entityId),[2,3,0]);assert.deepEqual(w.project.scene.entities[0].rigidBody.velocity,[0,0,0]);assert.throws(()=>applyScriptOperations(w.project.scene,{generation:1,operations:[{kind:'velocity',id:entityId,position:[10001,0,0]}]},1),/invalid/);
});
