import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {renderPlan,visibleBounds,materialDefaults,renderingDefaults} from '../engine/renderer/render-plan.mjs';import {cameraMatrix,modelMatrix,matrixMultiply} from '../engine/renderer/render-math.mjs';import {createM9Demos} from '../demos/create-m9-projects.mjs';import {ProjectStore} from '../daemon/bootstrap/project-store.mjs';import {SceneWorkspace} from '../daemon/bootstrap/scene-workspace.mjs';import {scenePrimitives} from '../engine/wasm/host.mjs';import {validateProject} from '../protocol/src/project-document.mjs';
const camera={position:[0,0,10],target:[0,0,0],projection:'perspective',fov:60},transform={position:[0,0,0],rotation:[0,0,0,1],scale:[1,1,1]},vertices=new Float32Array([-1,-1,0,0,0,1,0,0,1,-1,0,0,0,1,1,0,0,1,0,0,0,1,.5,1]);
const assetId='asset://'+ 'a'.repeat(64),id='entity://00000000-0000-4000-8000-000000000001';
function fixture(){const scene={entities:[{id,transform,renderable:{kind:'mesh',assetId},material:{...materialDefaults}}],rendering:{...renderingDefaults},assets:[]};return {scene,draws:[{entityId:id,assetId,vertices,transform,primitiveIndex:0}]};}
test('CPU admission rejects each clip plane and retains near-plane crossings',()=>{const b={minimum:[-1,-1,-1],maximum:[1,1,1]},vp=cameraMatrix(camera,16/9);assert.equal(visibleBounds(b,vp),true);for(const p of [[100,0,0],[-100,0,0],[0,100,0],[0,-100,0],[0,0,20],[0,0,-11000]])assert.equal(visibleBounds(b,matrixMultiply(vp,modelMatrix({...transform,position:p}))),false);assert.equal(visibleBounds(b,matrixMultiply(vp,modelMatrix({...transform,position:[0,0,9.5]}))),true);});
test('instancing batches opaque geometry, sorts transparency and preserves material overrides',()=>{const {scene,draws}=fixture();for(let i=1;i<20;i++){scene.entities.push({...scene.entities[0],id:id+i,material:{...materialDefaults},transform:{...transform,position:[i%3,0,0]}});draws.push({...draws[0],entityId:id+i});}const p=renderPlan(scene,draws,camera,16/9);assert.equal(p.batches.length,1);assert.equal(p.batches[0].count,20);scene.entities[0].material.alphaMode='blend';assert.equal(renderPlan(scene,draws,camera,16/9).batches.length,2);});
test('LOD switches actual geometry and reports missing assets without fabricating evidence',()=>{const {scene,draws}=fixture(),lowId='asset://'+ 'b'.repeat(64);scene.entities[0].lod={levels:[{assetId:lowId,distance:5}]};const assets=new Map([[lowId,{primitives:[{vertices:Array.from(vertices).slice(0,24)}]}]]);const p=renderPlan(scene,draws,camera,1,assets);assert.equal(p.items[0].assetId,lowId);assert.equal(p.stats.lodInstances,1);assert.equal(p.items[0].vertices.length,24);const missing=renderPlan(scene,draws,camera,1);assert.equal(missing.stats.lodInstances,0);assert.equal(missing.fallbacks.length,1);assert.equal(missing.stats.pixels,'unproven');});
test('constrained tier and Null choose explicit bounded fallbacks',()=>{const {scene,draws}=fixture();scene.rendering.tier='low';for(let i=0;i<10;i++)scene.entities.push({id:'light'+i,transform,light:{kind:'point',direction:[0,-1,0],color:[1,1,1],range:5,intensity:20,innerAngle:15,outerAngle:30,shadow:true}});const p=renderPlan(scene,draws,camera,1,new Map(),{gpuCulling:false});assert.equal(p.stats.lights,8);assert.equal(p.settings.culling,'cpu');assert.equal(p.settings.bloom,0);assert.equal(p.shadowIndex,-1);assert.equal(p.fallbacks.length,4);});
test('editable M9 demos validate, preserve projects, mutate/undo/save/reopen material and LOD contracts',async()=>{const root=await mkdtemp(join(tmpdir(),'axiom-m9-unit-'));try{const demos=await createM9Demos(root),store=new ProjectStore(root),w=new SceneWorkspace(store);assert.equal(demos.length,2);for(const demo of demos){await w.run('project.open',{id:demo.id});validateProject(w.project);const assets=new Map();for(const a of w.project.scene.assets)assets.set(a.id,await w.pipeline.resource(w.project.id,w.project.scene,a.id));const draws=scenePrimitives(w.project.scene,assets),p=renderPlan(w.project.scene,draws,w.project.scene.camera,16/9,assets);assert.ok(p.stats.instances>15);if(demo===demos[1]){assert.ok(p.batches.length<=3);assert.ok(p.stats.culled>=24);assert.equal(p.stats.lodInstances,1);}const entity=w.project.scene.entities.find(e=>e.renderable),old=structuredClone(entity.material),args=extra=>({id:w.project.id,expectedSceneRevision:w.revision,...extra});await w.run('scene.material.set',args({entityId:entity.id,value:{...old,metallic:1}}));await w.run('scene.undo',args());assert.deepEqual(w.project.scene.entities.find(e=>e.id===entity.id).material,old);await assert.rejects(w.run('scene.material.set',args({entityId:entity.id,value:{...old,roughness:0}})),/Invalid project/);await w.run('scene.component.remove',args({entityId:entity.id,component:'Material'}));await w.run('scene.save',args());await w.run('project.close',args());await w.run('project.open',{id:demo.id});assert.equal(w.project.scene.entities.find(e=>e.id===entity.id).material,undefined);await w.run('project.close',args());}assert.equal((await store.run('project.list',{})).projects.length,2);}finally{await rm(root,{recursive:true,force:true});}});
