import test from 'node:test';import assert from 'node:assert/strict';
import {ReplaySession,validateRecording} from '../engine/replay/session.mjs';
const scope={id:'project://11111111-1111-4111-8111-111111111111',sceneRevision:1};
function rig({diverge=false}={}){let pos=0,frames=0,restored=0;const adapter={scope:()=>scope,begin:async()=>{pos=0;frames=0;},step:async({keys})=>{pos+=keys.includes('ArrowRight')?1:0;frames++;await new Promise(r=>setTimeout(r,0));},snapshot:()=>({entities:[{id:'entity://11111111-1111-4111-8111-111111111111',transform:{position:[pos+(diverge?restored:0),0,0],rotation:[0,0,0,1],scale:[1,1,1]}}],animation:[],time:frames/60}),diagnostic:()=>({observed:pos}),end:async()=>{restored++;}};return new ReplaySession(adapter);}
async function done(r){while(r.flight)await r.flight;return r.result();}
const suite={name:'Recorded arrows',steps:[{frames:60,keys:['ArrowRight']},{frames:60,keys:['ArrowLeft']}]};
test('recorded inputs/checkpoints roundtrip and range diagnostics preserve original provenance',async()=>{const r=rig();r.control({action:'record',suite,seed:42});assert.equal((await done(r)).status,'completed');const recording=r.control({action:'export'}).recording;assert.equal(validateRecording(JSON.stringify(recording)).inputs.length,120);r.control({action:'clear'});r.control({action:'import',recordingJson:JSON.stringify(recording)});r.control({action:'replay',from:60,to:120});const out=await done(r);assert.equal(out.status,'completed');assert.equal(out.verifiedCheckpoints,3);assert.equal(out.checkpoint,60);assert.ok(out.diagnostics.every(d=>d.recordingId===recording.id&&d.sourceRevision===1));});
test('checkpoint divergence fails rather than claiming deterministic replay',async()=>{const r=rig({diverge:true});r.control({action:'record',suite,seed:0});await done(r);r.control({action:'replay',from:0,to:120});const out=await done(r);assert.equal(out.status,'failed');assert.match(out.error,/Checkpoint divergence/);});
test('cancellation finishes cleanup and cannot publish a partial recording',async()=>{const r=rig();r.control({action:'record',suite,seed:1});r.control({action:'cancel'});const out=await done(r);assert.equal(out.status,'cancelled');assert.equal(out.recording,null);assert.throws(()=>r.control({action:'export'}));});
test('record budgets, seed, range and import validation reject malformed work',async()=>{const r=rig();assert.throws(()=>r.control({action:'record',suite,seed:-1}));assert.throws(()=>r.control({action:'record',suite:{name:'Big',steps:Array.from({length:6},()=>({frames:120}))},seed:0}));assert.throws(()=>validateRecording('{}'));r.control({action:'record',suite,seed:0});await done(r);assert.throws(()=>r.control({action:'replay',from:121,to:122}));const recording=r.control({action:'export'}).recording;recording.scope.sceneRevision=99;assert.throws(()=>r.control({action:'import',recordingJson:JSON.stringify(recording)}),/revision/);});
import {EditorBridge} from '../daemon/bootstrap/agent/editor-bridge.mjs';
import {toolMap,validate} from '../daemon/bootstrap/agent/contracts.mjs';
test('public replay bridge scopes revisions and rejects pending work on disconnect',async()=>{const w={project:{id:scope.id},revision:1,workspaceId:null,snapshot:()=>({})},b=new EditorBridge(w,()=>{}),clientId='33333333-3333-4333-8333-333333333333',status={projectId:scope.id,sceneRevision:1,renderer:'null'};b.sync({clientId,sceneRevision:1,status});const p=b.replay({...scope,expectedSceneRevision:1,action:'query'});const request=b.sync({clientId,sceneRevision:1,status}).replay;b.sync({clientId,sceneRevision:1,status,replay:{requestId:request.requestId,value:{status:'completed',frames:60}}});assert.equal((await p).frames,60);assert.throws(()=>b.replay({id:scope.id,expectedSceneRevision:99,action:'query'}));const pending=b.replay({id:scope.id,expectedSceneRevision:1,action:'cancel'});b.release(clientId);await assert.rejects(pending,/closed/);});
test('public project settings validate plain master documents and assistant instructions alongside existing settings',()=>{const schema=toolMap.get('project.editor.update').inputSchema,args={id:scope.id,expectedSceneRevision:1,value:{leftWidth:220,rightWidth:290,bottomHeight:260,masterDocument:{name:'master.md',text:'# Plain project brief'},assistantInstructions:'Preserve MAIN'}};validate(schema,args);assert.throws(()=>validate(schema,{...args,value:{...args.value,masterDocument:{name:'master.md',text:'x'.repeat(32769)}}}));assert.throws(()=>validate(schema,{...args,value:{...args.value,apiKey:'secret'}}));});

test('recording schema accepts canonical SHA-256 asset identifiers in resource scope',async()=>{const r=rig();r.adapter.scope=()=>({...scope,resources:[{id:'asset://'+'a'.repeat(64),buildKey:'b'.repeat(64)}]});r.control({action:'record',suite,seed:42});await done(r);const recorded=r.control({action:'export'}).recording;assert.deepEqual(validateRecording(JSON.stringify(recorded)).scope.resources,recorded.scope.resources);});
