import {twoDLimits} from './two-d-plan.mjs';
const shader=`
struct Lighting {ambient:vec4f, lights:array<vec4f,32>};
@group(0) @binding(0) var<uniform> lighting:Lighting;
@group(1) @binding(0) var sampler0:sampler;
@group(1) @binding(1) var texture0:texture_2d<f32>;
struct Out{@builtin(position) position:vec4f,@location(0) uv:vec2f,@location(1) color:vec4f,@location(2) world:vec2f,@location(3) lit:f32};
@vertex fn vs(@location(0) p:vec4f,@location(1) uv:vec2f,@location(2) color:vec4f,@location(3) world:vec2f,@location(4) lit:f32)->Out{var o:Out;o.position=p;o.uv=uv;o.color=color;o.world=world;o.lit=lit;return o;}
@fragment fn fs(i:Out)->@location(0) vec4f{let base=textureSample(texture0,sampler0,i.uv)*i.color;var color=vec3f(1);if(i.lit>0.5){color=lighting.ambient.xyz;for(var n=0u;n<u32(lighting.ambient.w);n++){let p=lighting.lights[n*2u];let c=lighting.lights[n*2u+1u];let a=max(0.0,1.0-distance(i.world,p.xy)/p.z);color+=c.xyz*c.w*a*a;}}return vec4f(base.rgb*color*base.a,base.a);}
`;
export async function createTwoDGPU({device,format,width,height,textureFor}){
 const module=device.createShaderModule({code:shader,label:'axiom-2d'}),errors=(await module.getCompilationInfo()).messages.filter(m=>m.type==='error');if(errors.length)throw Error(errors.map(m=>m.message).join('; '));
 const pipeline=await device.createRenderPipelineAsync({layout:'auto',vertex:{module,entryPoint:'vs',buffers:[{arrayStride:52,attributes:[{shaderLocation:0,offset:0,format:'float32x4'},{shaderLocation:1,offset:16,format:'float32x2'},{shaderLocation:2,offset:24,format:'float32x4'},{shaderLocation:3,offset:40,format:'float32x2'},{shaderLocation:4,offset:48,format:'float32'}]}]},fragment:{module,entryPoint:'fs',targets:[{format,blend:{color:{srcFactor:'one',dstFactor:'one-minus-src-alpha',operation:'add'},alpha:{srcFactor:'one',dstFactor:'one-minus-src-alpha',operation:'add'}}}]},primitive:{topology:'triangle-list',cullMode:'none'}});
 const vertex=device.createBuffer({size:twoDLimits.vertexBytes,usage:GPUBufferUsage.VERTEX|GPUBufferUsage.COPY_DST}),uniform=device.createBuffer({size:528,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST}),lighting=device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:uniform}}]}),nearest=device.createSampler({magFilter:'nearest',minFilter:'nearest'}),linear=device.createSampler({magFilter:'linear',minFilter:'linear'});let bindings=new Map();
 async function prepare(urls){bindings.clear();for(const url of new Set([...urls,null])){const texture=await textureFor(url);bindings.set(url??'white',[linear,nearest].map(s=>device.createBindGroup({layout:pipeline.getBindGroupLayout(1),entries:[{binding:0,resource:s},{binding:1,resource:texture.createView()}]})));}}
 function render(plan,target){const values=new Float32Array(132);values.set([...plan.settings.ambient,plan.lights.length]);plan.lights.forEach((l,i)=>{values.set([...l.position,l.radius,0,...l.color,l.intensity],4+i*8);});device.queue.writeBuffer(uniform,0,values);if(plan.vertices.length)device.queue.writeBuffer(vertex,0,plan.vertices);const encoder=device.createCommandEncoder({label:'axiom-2d-batches'}),pass=encoder.beginRenderPass({colorAttachments:[{view:target,clearValue:{r:plan.settings.background[0],g:plan.settings.background[1],b:plan.settings.background[2],a:1},loadOp:'clear',storeOp:'store'}]});pass.setViewport(...plan.pixel.viewport,0,1);pass.setScissorRect(...plan.pixel.viewport);pass.setPipeline(pipeline);pass.setBindGroup(0,lighting);pass.setVertexBuffer(0,vertex);for(const batch of plan.batches){const bind=bindings.get(batch.key);if(!bind)throw Error('AX_ASSET_0001: 2D texture not prepared');pass.setBindGroup(1,bind[plan.pixel.pixel?1:0]);pass.draw(batch.count,1,batch.first);}pass.end();device.queue.submit([encoder.finish()]);return {...plan.stats,submitted:plan.batches.length,textureBindings:bindings.size,backend:'webgpu'};}
 return {prepare,render,dispose(){vertex.destroy();uniform.destroy();bindings.clear();}};
}
