import {cameraMatrix,modelMatrix,matrixMultiply,transform} from './render-math.mjs';
export const twoDDefaults=Object.freeze({ambient:[.3,.3,.35],background:[.025,.035,.055],pixelPerfect:true,pixelsPerUnit:32,referenceHeight:180});
export const component2DDefaults=Object.freeze({sprite2D:{columns:1,rows:1,frame:0,size:[1,1],tint:[1,1,1,1],order:0,lit:true,flipX:false,flipY:false},spriteAnimation:{frames:[0],fps:8,loop:true,autoplay:true},tilemap:{columns:1,rows:1,width:8,height:4,tileSize:1,cells:Array(32).fill(-1),order:-10,lit:true},light2D:{color:[1,.7,.3],intensity:2,radius:4},particles2D:{capacity:64,rate:20,lifetime:2,speed:2,spread:90,gravity:-2,size:.12,color:[1,.5,.1,1],seed:7,order:20},ui2D:{kind:'button',rect:[.82,.04,.14,.07],color:[.15,.5,.8,.9],order:0,action:'togglePause'}});
export const twoDLimits=Object.freeze({quads:8192,batches:1024,vertexBytes:8192*6*13*4});
export function pixelCamera(camera,settings,width,height,view){
 const c=structuredClone(camera),pixel=settings.pixelPerfect&&view==='game';
 if(pixel){const snap=v=>Math.round(v*settings.pixelsPerUnit)/settings.pixelsPerUnit;const delta=c.position.map((v,i)=>i<2?snap(v)-v:0);c.position=c.position.map((v,i)=>v+delta[i]);c.target=c.target.map((v,i)=>v+delta[i]);c.orthoHeight=settings.referenceHeight/settings.pixelsPerUnit;}
 const scale=pixel?Math.max(1,Math.floor(height/settings.referenceHeight)):1;
 const renderHeight=pixel?Math.min(height,settings.referenceHeight*scale):height;
 if(pixel)c.orthoHeight=renderHeight/(settings.pixelsPerUnit*scale);
 const renderWidth=pixel?Math.floor(width/scale)*scale:width;
 return {camera:c,viewport:[Math.floor((width-renderWidth)/2),Math.floor((height-renderHeight)/2),renderWidth,renderHeight],scale,pixel,nearest:!!settings.pixelPerfect};
}
export function uiHit(scene,x,y,viewport){const [left,top,w,h]=viewport;const u=(x-left)/w,v=(y-top)/h;if(u<0||v<0||u>1||v>1)return null;return scene.entities.filter(e=>e.ui2D?.kind==='button').map((e,i)=>({e,i})).sort((a,b)=>b.e.ui2D.order-a.e.ui2D.order||b.i-a.i).find(({e})=>{const r=e.ui2D.rect;return u>=r[0]&&v>=r[1]&&u<=r[0]+r[2]&&v<=r[1]+r[3];})?.e??null;}
export function twoDPlan(scene,assets,camera,width,height,{view='game',time=0,kernel,paused=false}={}){
 const settings={...twoDDefaults,...scene.twoD},pixel=pixelCamera(camera,settings,width,height,view),vp=cameraMatrix(pixel.camera,pixel.viewport[2]/pixel.viewport[3]),quads=[],lights=[],animations=[];let sequence=0,tiles=0,particles=0;
 function quad(entity,texture,points,uv,color,order,lit,ui=false){if(quads.length>=twoDLimits.quads)throw Error('AX_RENDERER_0005: 2D quad budget exceeded');const model=modelMatrix(entity.transform);const world=points.map(p=>transform(model,p).slice(0,3));const clip=ui?points.map(p=>[p[0],p[1],0,1]):world.map(p=>transform(vp,p));const visible=ui||![v=>v[0]<-v[3],v=>v[0]>v[3],v=>v[1]<-v[3],v=>v[1]>v[3],v=>v[2]<0,v=>v[2]>v[3]].some(out=>clip.every(out));quads.push({entityId:entity.id,texture,points,world,clip,uv,color,order,lit:lit&&!ui,ui,sequence:sequence++,visible,model,mvp:matrixMultiply(vp,model)});}
 function atlas(entity,asset,columns,rows,frame,cx,cy,w,h,color,order,lit,flipX=false,flipY=false){if(!asset)return;const x=frame%columns/columns,y=Math.floor(frame/columns)/rows;let u=[x,x+1/columns],v=[y+1/rows,y];if(flipX)u.reverse();if(flipY)v.reverse();quad(entity,asset.dataUrl,[[cx-w/2,cy-h/2,0],[cx+w/2,cy-h/2,0],[cx+w/2,cy+h/2,0],[cx-w/2,cy+h/2,0]],[[u[0],v[0]],[u[1],v[0]],[u[1],v[1]],[u[0],v[1]]],color,order,lit);}
 for(const e of scene.entities){
  if(e.light2D)lights.push({...e.light2D,position:e.transform.position.slice(0,2)});
  if(e.renderable?.kind==='sprite'){const a=assets.get(e.renderable.assetId);if(a){const s=e.sprite2D??{...component2DDefaults.sprite2D,size:[2*a.width/a.height,2],lit:false};let frame=s.frame;if(e.spriteAnimation){const animation=e.spriteAnimation,index=animation.autoplay&&time>0?kernel.animationFrame(time,animation):0;frame=animation.autoplay&&time>0?animation.frames[index]:s.frame;animations.push({entityId:e.id,frame,playing:animation.autoplay&&time>0&&!paused&&(animation.loop||time*animation.fps<animation.frames.length),loop:animation.loop});}atlas(e,a,s.columns,s.rows,frame,0,0,...s.size,s.tint,s.order,s.lit,s.flipX,s.flipY);}}
  if(e.tilemap){const t=e.tilemap,a=assets.get(t.assetId);for(let i=0;i<t.cells.length;i++)if(t.cells[i]>=0){tiles++;atlas(e,a,t.columns,t.rows,t.cells[i],(i%t.width+.5)*t.tileSize,(t.height-Math.floor(i/t.width)-.5)*t.tileSize,t.tileSize,t.tileSize,[1,1,1,1],t.order,t.lit);}}
  if(e.particles2D&&time>0){const p=e.particles2D;for(let i=0;i<p.capacity;i++){const sample=kernel.particle(time,i,p);if(!sample.every(Number.isFinite))continue;particles++;quad(e,null,[[sample[0]-p.size/2,sample[1]-p.size/2,0],[sample[0]+p.size/2,sample[1]-p.size/2,0],[sample[0]+p.size/2,sample[1]+p.size/2,0],[sample[0]-p.size/2,sample[1]+p.size/2,0]],[[0,1],[1,1],[1,0],[0,0]],[...p.color.slice(0,3),p.color[3]*sample[2]],p.order,false);}}
  if(e.ui2D&&view==='game'){const u=e.ui2D,[x,y,w,h]=u.rect,color=paused&&u.action==='togglePause'?[.85,.35,.15,u.color[3]]:u.color;quad(e,null,[[x*2-1,1-(y+h)*2,0],[(x+w)*2-1,1-(y+h)*2,0],[(x+w)*2-1,1-y*2,0],[x*2-1,1-y*2,0]],[[0,1],[1,1],[1,0],[0,0]],color,u.order,false,true);}
 }
 quads.sort((a,b)=>Number(a.ui)-Number(b.ui)||a.order-b.order||a.sequence-b.sequence);
 const batches=[],vertices=[],items=[];
 for(const q of quads){if(!q.visible)continue;const key=q.texture??'white';let b=batches.at(-1);if(!b||b.key!==key){if(batches.length>=twoDLimits.batches)throw Error('AX_RENDERER_0005: 2D batch budget exceeded');b={key,texture:q.texture,first:vertices.length/13,count:0};batches.push(b);}const raw=[];for(const i of [0,1,2,0,2,3]){vertices.push(...q.clip[i],...q.uv[i],...q.color,...q.world[i].slice(0,2),q.lit?1:0);raw.push(...q.points[i],0,0,1,...q.uv[i]);b.count++;}if(!q.ui)items.push({entityId:q.entityId,model:q.model,mvp:q.mvp,vertices:new Float32Array(raw)});}
 return {settings,pixel,lights:lights.slice(0,16),batches,vertices:new Float32Array(vertices),items,stats:{mode:'2d',quads:quads.length,visible:quads.filter(q=>q.visible).length,culled:quads.filter(q=>!q.visible).length,batches:batches.length,tiles,particles,lights:lights.length,animations:animations.slice(0,32),omittedAnimations:Math.max(0,animations.length-32),time,paused,viewport:pixel.viewport,pixelScale:pixel.scale,pixelPerfect:pixel.pixel,vertexBytes:vertices.length*4,vertexCapacityBytes:twoDLimits.vertexBytes,pixels:'unproven'}};
}
