import {modelMatrix,matrixMultiply,transform,quaternionMultiply} from '../renderer/render-math.mjs';
export const identityTransform=()=>({position:[0,0,0],rotation:[0,0,0,1],scale:[1,1,1]});
export const inverseQuaternion=q=>{const n=q.reduce((s,v)=>s+v*v,0);return [-q[0]/n,-q[1]/n,-q[2]/n,q[3]/n];};
export function inverseMatrix(m){const a=Array.from({length:4},(_,r)=>Array.from({length:8},(_,c)=>c<4?m[c*4+r]:Number(c-4===r)));for(let i=0;i<4;i++){let k=i;for(let r=i+1;r<4;r++)if(Math.abs(a[r][i])>Math.abs(a[k][i]))k=r;if(Math.abs(a[k][i])<1e-10)throw Error('AX_SCENE_0001: Cannot parent through a zero scale');[a[i],a[k]]=[a[k],a[i]];const d=a[i][i];a[i]=a[i].map(v=>v/d);for(let r=0;r<4;r++)if(r!==i){const f=a[r][i];a[r]=a[r].map((v,c)=>v-f*a[i][c]);}}return Array.from({length:16},(_,i)=>a[i%4][4+Math.floor(i/4)]);}
export function decompose(m){const scale=[0,1,2].map(i=>Math.hypot(m[i*4],m[i*4+1],m[i*4+2]));if(scale.some(s=>s<1e-10))throw Error('AX_SCENE_0001: Cannot decompose zero scale');const det=m[0]*(m[5]*m[10]-m[6]*m[9])-m[4]*(m[1]*m[10]-m[2]*m[9])+m[8]*(m[1]*m[6]-m[2]*m[5]);if(det<0)scale[0]*=-1;const r=m.map((v,i)=>i<12?v/scale[Math.floor(i/4)]:v),trace=r[0]+r[5]+r[10];let q;
 if(trace>0){const s=Math.sqrt(trace+1)*2;q=[(r[6]-r[9])/s,(r[8]-r[2])/s,(r[1]-r[4])/s,s/4];}else{let i=0;if(r[5]>r[0])i=1;if(r[10]>r[i*5])i=2;const j=(i+1)%3,k=(i+2)%3,s=Math.sqrt(1+r[i*5]-r[j*5]-r[k*5])*2;q=[0,0,0,0];q[i]=s/4;q[j]=(r[j*4+i]+r[i*4+j])/s;q[k]=(r[k*4+i]+r[i*4+k])/s;q[3]=(r[j*4+k]-r[k*4+j])/s;}
 const t={position:m.slice(12,15),rotation:q.map(v=>v/Math.hypot(...q)),scale};if(modelMatrix(t).some((v,i)=>Math.abs(v-m[i])>1e-5*Math.max(1,Math.abs(m[i]))))throw Error('AX_SCENE_0001: This parent scale and rotation would introduce shear; use uniform parent scale');return t;
}
export function worldTransforms(entities){const map=new Map(entities.map(e=>[e.id,e])),result=new Map(),visiting=new Set();function visit(id){if(result.has(id))return result.get(id);const e=map.get(id);if(!e||visiting.has(id))throw Error('AX_SCENE_0001: Missing parent or hierarchy cycle');visiting.add(id);const local={...e.transform,rotation:e.transform.rotation.map(v=>v/Math.hypot(...e.transform.rotation))};const t=e.parentId?decompose(matrixMultiply(modelMatrix(visit(e.parentId)),modelMatrix(local))):local;visiting.delete(id);result.set(id,t);return t;}for(const e of entities)visit(e.id);return result;}
export function worldScene(scene){const transforms=worldTransforms(scene.entities);return {...scene,entities:scene.entities.map(e=>{const item={...e,transform:transforms.get(e.id)};delete item.parentId;return item;})};}
export function localTransform(entities,id,world){const e=entities.find(e=>e.id===id);if(!e?.parentId)return world;const parent=worldTransforms(entities).get(e.parentId);return decompose(matrixMultiply(inverseMatrix(modelMatrix(parent)),modelMatrix(world)));}
export function reparent(entities,ids,parentId){const world=worldTransforms(entities),chosen=new Set(ids);if(!ids.length||ids.some(id=>!world.has(id))||(parentId&&!world.has(parentId)))throw Error('AX_SCENE_0001: Invalid selection or parent');const roots=ids.filter(id=>{let p=entities.find(e=>e.id===id)?.parentId;while(p){if(chosen.has(p))return false;p=entities.find(e=>e.id===p)?.parentId;}return true;});for(const id of roots){let p=parentId;while(p){if(p===id)throw Error('AX_SCENE_0001: Cannot parent an entity to itself or its descendants');p=entities.find(e=>e.id===p)?.parentId;}}
 const result=structuredClone(entities);for(const id of roots){const e=result.find(e=>e.id===id);if(parentId){e.parentId=parentId;e.transform=decompose(matrixMultiply(inverseMatrix(modelMatrix(world.get(parentId))),modelMatrix(world.get(id))));}else{delete e.parentId;e.transform=world.get(id);}}worldTransforms(result);return result;
}
export const rotatedDirection=(q,d)=>transform(modelMatrix({position:[0,0,0],rotation:q,scale:[1,1,1]}),d,0).slice(0,3);
export {quaternionMultiply};
