// Built-in geometry is saved as ordinary imported GLB assets, not a renderer bypass.
export const primitiveNames={3:['cube','sphere','cylinder','capsule','pyramid'],2:['square','disc','capsule','triangle']};
export function primitiveGlb(dimension,shape){if(!primitiveNames[dimension]?.includes(shape))throw Error('AX_SCENE_0001: Unknown primitive');const positions=[],normals=[];
 const triangle=(a,b,c)=>{const u=b.map((v,i)=>v-a[i]),v=c.map((v,i)=>v-a[i]),n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],length=Math.hypot(...n);if(length<1e-10)return;for(const p of [a,b,c]){positions.push(...p);normals.push(...n.map(x=>x/length));}};
 if(dimension===2){let outline;if(shape==='square')outline=[[-.5,-.5,0],[.5,-.5,0],[.5,.5,0],[-.5,.5,0]];if(shape==='triangle')outline=[[-.5,-.5,0],[.5,-.5,0],[0,.5,0]];if(shape==='disc')outline=Array.from({length:48},(_,i)=>{const a=i*Math.PI/24;return [.5*Math.cos(a),.5*Math.sin(a),0];});if(shape==='capsule')outline=Array.from({length:48},(_,i)=>{const a=i*Math.PI/24;return [.25*Math.cos(a),.25*Math.sin(a)+(.25*Math.sign(Math.sin(a))),0];});for(let i=0;i<outline.length;i++)triangle([0,0,0],outline[i],outline[(i+1)%outline.length]);}
 else if(shape==='cube'||shape==='pyramid'){const p=[[-.5,-.5,-.5],[.5,-.5,-.5],[.5,-.5,.5],[-.5,-.5,.5],[-.5,.5,-.5],[.5,.5,-.5],[.5,.5,.5],[-.5,.5,.5],[0,.5,0]];const faces=shape==='cube'?[[0,1,2,3],[4,7,6,5],[0,4,5,1],[1,5,6,2],[2,6,7,3],[3,7,4,0]]:[[0,1,2,3],[0,8,1],[1,8,2],[2,8,3],[3,8,0]];for(const f of faces)for(let i=1;i<f.length-1;i++)triangle(p[f[0]],p[f[i]],p[f[i+1]]);}
 else{const segments=32,rings=shape==='cylinder'?1:24;const point=(x,y)=>{const a=x/segments*Math.PI*2;if(shape==='cylinder')return [.5*Math.cos(a),y-.5,.5*Math.sin(a)];const t=y/rings*Math.PI,r=shape==='capsule'?.25:.5;return [r*Math.sin(t)*Math.cos(a),r*Math.cos(t)+(shape==='capsule'?.25*Math.sign(Math.cos(t)):0),r*Math.sin(t)*Math.sin(a)];};for(let y=0;y<rings;y++)for(let x=0;x<segments;x++){triangle(point(x,y),point(x,y+1),point(x+1,y+1));triangle(point(x,y),point(x+1,y+1),point(x+1,y));}if(shape==='cylinder')for(let x=0;x<segments;x++){triangle([0,.5,0],point(x+1,1),point(x,1));triangle([0,-.5,0],point(x,0),point(x+1,0));}}
 const count=positions.length/3,bin=Buffer.alloc((positions.length+normals.length)*4);[...positions,...normals].forEach((v,i)=>bin.writeFloatLE(v,i*4));const doc={asset:{version:'2.0'},scene:0,scenes:[{nodes:[0]}],nodes:[{mesh:0}],meshes:[{primitives:[{attributes:{POSITION:0,NORMAL:1},material:0}]}],materials:[{doubleSided:dimension===2}],buffers:[{byteLength:bin.length}],bufferViews:[{buffer:0,byteOffset:0,byteLength:positions.length*4},{buffer:0,byteOffset:positions.length*4,byteLength:normals.length*4}],accessors:[{bufferView:0,componentType:5126,count,type:'VEC3'},{bufferView:1,componentType:5126,count,type:'VEC3'}]};const raw=Buffer.from(JSON.stringify(doc)),json=Buffer.alloc(Math.ceil(raw.length/4)*4,32);raw.copy(json);const out=Buffer.alloc(28+json.length+bin.length);out.writeUInt32LE(0x46546c67,0);out.writeUInt32LE(2,4);out.writeUInt32LE(out.length,8);out.writeUInt32LE(json.length,12);out.writeUInt32LE(0x4e4f534a,16);json.copy(out,20);const offset=20+json.length;out.writeUInt32LE(bin.length,offset);out.writeUInt32LE(0x004e4942,offset+4);bin.copy(out,offset+8);return out;
}
