import schema from '../../protocol/schema/project-document.schema.json' with {type:'json'};
import {scriptFields,scriptValue} from '../scripting/fields.mjs';
const fail=message=>{throw Object.assign(Error(message),{code:'AX_SCENE_0001'});};
const entitySchema=schema.properties.scene.properties.entities.items;
const components={camera:'camera',material:'material',light:'light',lod:'lod',collider:'collider',rigidBody:'rigidBody',sprite2D:'sprite2D',spriteAnimation:'spriteAnimation',tilemap:'tilemap',light2D:'light2D',particles2D:'particles2D',ui2D:'ui2D',audioSource:'audioSource',audioListener:'audioListener',animator:'animator'};
export const runtimeEditableTypes=['scene.entity.update','scene.entities.update','scene.script.edit',...Object.keys(components).map(k=>'scene.'+k+'.set')];
function check(value,rule,path='value',depth=0){if(depth>24)fail('Runtime value nesting exceeds limit');if(rule.type==='object'){if(!value||typeof value!=='object'||Array.isArray(value))fail('Invalid '+path);for(const key of Object.keys(value))if(['__proto__','constructor','prototype'].includes(key)||rule.additionalProperties===false&&!Object.hasOwn(rule.properties??{},key))fail('Invalid '+path+'.'+key);for(const key of rule.required??[])if(!Object.hasOwn(value,key))fail('Missing '+path+'.'+key);for(const[key,v]of Object.entries(value))if(rule.properties?.[key])check(v,rule.properties[key],path+'.'+key,depth+1);}else if(rule.type==='array'){if(!Array.isArray(value)||value.length<(rule.minItems??0)||value.length>(rule.maxItems??Infinity))fail('Invalid '+path);for(const v of value)check(v,rule.items,path,depth+1);}else if(rule.type==='number'||rule.type==='integer'){if(!Number.isFinite(value)||rule.type==='integer'&&!Number.isSafeInteger(value)||value<(rule.minimum??-Infinity)||value>(rule.maximum??Infinity))fail('Invalid '+path);}else if(rule.type==='boolean'&&typeof value!=='boolean')fail('Invalid '+path);else if(rule.type==='string'&&(typeof value!=='string'||value.length<(rule.minLength??0)||value.length>(rule.maxLength??4096)||rule.pattern&&!new RegExp(rule.pattern).test(value)))fail('Invalid '+path);if(rule.enum&&!rule.enum.includes(value)||Object.hasOwn(rule,'const')&&value!==rule.const)fail('Invalid '+path);}
// Runtime-only edits never enter authoring history, assets, files or source revisions.
export function applyRuntimeEdit(scene,{type,data}) {
 if(!runtimeEditableTypes.includes(type)||JSON.stringify(data).length>32768)fail('Unsupported runtime edit');const next=structuredClone(scene);
 const find=id=>{const e=next.entities.find(e=>e.id===id);if(!e)fail('Runtime entity is missing');return e;};
 if(type==='scene.script.edit'){if(data.action!=='values')fail('Script structure cannot change during Play');const e=find(data.entityId),c=e.scriptComponents?.find(c=>c.path===data.path);if(!c)fail('Script is not attached');const meta=scriptFields(next,data.path);for(const[name,value]of Object.entries(data.values??{})){const field=meta.fields.find(f=>f.name===name);if(!field||field.readOnly)fail('Field is hidden or readonly');c.values[name]=scriptValue(field,value);}}
 else if(type==='scene.entity.update'||type==='scene.entities.update'){
  const updates=type==='scene.entities.update'?data.updates:[data];if(!Array.isArray(updates)||updates.length>256)fail('Runtime selection budget exceeded');for(const update of updates){const e=find(update.entityId);if(update.name!==undefined)e.name=update.name;if(update.transform)e.transform={...e.transform,...structuredClone(update.transform)};check(e,entitySchema);}
 }else{const key=components[type.split('.')[1]],e=find(data.entityId);if(!e[key])fail('Attach components before Play');check(data.value,entitySchema.properties[key]);e[key]=structuredClone(data.value);if(key==='camera'&&e.camera.active)for(const other of next.entities)if(other.id!==e.id&&other.camera)other.camera.active=false;}
 for(const e of next.entities)check(e,entitySchema);return next;
}
