// Project documents stay separate from daemon-only model credentials.
export function mountAiMenu({document,getSnapshot,save,reportError}){
 if(!document.defaultView)return ()=>{};
 const menu=document.createElement('details');menu.id='ai-menu';menu.innerHTML='<summary>AI</summary><div class="menu-popup"></div>';document.querySelector('#settings-menu').before(menu);
 const body=menu.querySelector('.menu-popup');
 const add=(id,label,html)=>{const d=document.createElement('details');d.id=id;d.innerHTML='<summary></summary><div class="submenu"></div>';d.querySelector('summary').textContent=label;d.querySelector('div').innerHTML=html;body.append(d);return d.querySelector('div');};
 const config=document.createElement('button');config.id='ai-assistant-config';config.textContent='Config AI assistant';body.append(config);
 const dialog=document.createElement('dialog');dialog.id='ai-config-dialog';dialog.setAttribute('aria-labelledby','ai-config-title');dialog.innerHTML='<header><h2 id="ai-config-title">Config AI assistant</h2><button id="ai-config-close" class="icon-button" aria-label="Close AI configuration"><img src="/icons/close.svg" width="18" height="18" alt=""></button></header><div class="ai-config-body"><form id="ai-config-form"><p>Connect an OpenAI API account. Connection test makes one small billable request. The key stays in daemon memory; restart requires reconnecting or OPENAI_API_KEY in the daemon environment.</p><label>API key<input id="ai-api-key" type="password" maxlength="512" autocomplete="off" placeholder="Enter key or use daemon credential"></label><label>Model<div class="ai-model-picker"><select id="ai-model" aria-label="AI model"><option value="">Select a compatible model</option></select><button id="ai-models" class="icon-button" type="button" aria-label="Reload available models" title="Reload available models"><svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true"><path d="M20 8a8 8 0 1 0 0 8M20 3v5h-5" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></button></div></label><div class="ai-limit-grid"><label>Requests / task<input id="ai-maxRequests" type="number" min="1" max="32" value="12"></label><label>Tool calls / task<input id="ai-maxTools" type="number" min="1" max="96" value="48"></label><label>Token budget / task<input id="ai-maxTokens" type="number" min="4096" max="500000" value="100000"></label><label>Output tokens / request<input id="ai-maxOutputTokens" type="number" min="512" max="16384" value="4096"></label><label>Seconds / task<input id="ai-maxSeconds" type="number" min="10" max="600" value="300"></label></div><p>Token budget conservatively reserves input bytes plus maximum output. Actual provider usage is shown with each task; this is not an account-wide spending limit.</p><div class="actions"><button id="ai-connect-test" type="submit">Connect and test</button><button id="ai-limits-save" type="button">Update limits</button><button id="ai-disconnect" type="button">Disconnect</button></div><p id="ai-config-status" role="status"></p></form><label>Assistant instructions<textarea id="ai-instructions" rows="4" maxlength="4000" placeholder="Project goals and working constraints"></textarea></label><button id="ai-instructions-save">Save instructions</button></div>';document.body.append(dialog);
 const planned=(id,label)=>{const b=document.createElement('button');b.id=id;b.textContent=label;b.disabled=true;body.append(b);};
 planned('ai-master-create','Project Master Document (planned)');
 const talk=document.createElement('button');talk.id='ai-talk';talk.textContent='Talk to AI assistant';talk.disabled=true;body.append(talk);
 const proposals=add('ai-proposals','AI proposal','<p>Review an isolated proposal before accepting changes into MAIN.</p>');const old=document.querySelector('#menu-section-4');if(old){for(const n of [...old.children].filter(n=>n.tagName!=='SUMMARY'))proposals.append(n);old.remove();}
 planned('ai-master-talk','Talk to AI Master (Advanced) (planned)');
 const master=document.createElement('details');master.id='project-master-menu';master.innerHTML='<summary>Project Master Document</summary><div class="submenu"><label>Load document · UTF-8 Markdown, text or JSON · max 32 KiB<input id="project-master-file" type="file" accept=".md,.txt,.json,text/plain,text/markdown,application/json"></label><p id="project-master-status" role="status"></p><label>Document text<textarea id="project-master-text" rows="12" maxlength="32768"></textarea></label><button id="project-master-save">Save document</button><button id="project-master-remove">Remove document</button><p id="ai-operation-status" role="status"></p></div>';document.querySelector('#settings-menu .menu-popup').prepend(master);
 const q=id=>document.querySelector('#'+id);let masterKey=null,instructionsKey=null,filename='project-master.md';
 const status=message=>{q('ai-operation-status').textContent=message;};
 const commit=async value=>{try{if(!getSnapshot()?.project)throw Error('Open a project first');if(await save(value)===false)throw Error('Project settings were not saved');status('Project settings saved');}catch(e){status(e.message);reportError(e);}};
 q('ai-instructions-save').addEventListener('click',()=>commit({assistantInstructions:q('ai-instructions').value}));
 q('project-master-file').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>32768||!/\.(md|txt|json)$/i.test(file.name))throw Error('Use a UTF-8 .md, .txt or .json file up to 32 KiB');const text=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer());filename=file.name;q('project-master-text').value=text;await commit({masterDocument:{name:filename,text}});}catch(error){status(error.message);reportError(error);}finally{e.target.value='';}});
 q('project-master-save').addEventListener('click',()=>commit({masterDocument:{name:filename,text:q('project-master-text').value}}));
 q('project-master-remove').addEventListener('click',()=>{filename='project-master.md';q('project-master-text').value='';void commit({masterDocument:{name:filename,text:''}});});
 function refresh(){const s=getSnapshot(),editor=s?.project?.editor??{},nextMaster=JSON.stringify([s?.project?.id,editor.masterDocument]),nextInstructions=JSON.stringify([s?.project?.id,editor.assistantInstructions]);if(nextMaster!==masterKey){masterKey=nextMaster;filename=editor.masterDocument?.name??'project-master.md';q('project-master-text').value=editor.masterDocument?.text??'';q('project-master-status').textContent=editor.masterDocument?.text?'Loaded: '+filename:'No project master document loaded';}if(nextInstructions!==instructionsKey){instructionsKey=nextInstructions;q('ai-instructions').value=editor.assistantInstructions??'';}}
 refresh();const timer=setInterval(refresh,300);return ()=>{clearInterval(timer);dialog.remove();};
}
