// The existing AI transport is external MCP. Never fabricate a connected/chat
// state or embed credentials in project documents, exports or browser storage.
export function mountAiMenu({document,getSnapshot,save,reportError}){
 if(!document.defaultView)return ()=>{};
 const menu=document.createElement('details');menu.id='ai-menu';menu.innerHTML='<summary>AI</summary><div class="menu-popup"></div>';document.querySelector('#settings-menu').before(menu);
 const body=menu.querySelector('.menu-popup');
 const add=(id,label,html)=>{const d=document.createElement('details');d.id=id;d.innerHTML='<summary></summary><div class="submenu"></div>';d.querySelector('summary').textContent=label;d.querySelector('div').innerHTML=html;body.append(d);return d.querySelector('div');};
 add('ai-connect','Connect AI model','<p>Connect your AI client through Axiom’s existing MCP server. Model selection and credentials belong to that client.</p><pre>npm.cmd run mcp</pre><p>Configure the client to launch Node with daemon/mcp/stdio.mjs from this project folder. Start the editor for rendering and runtime tools.</p>');
 add('ai-assistant-config','Config AI assistant','<label>Assistant instructions<textarea id="ai-instructions" rows="6" maxlength="4000" placeholder="Project goals and working constraints"></textarea></label><button id="ai-instructions-save">Save instructions</button><p>Stored with this project for external AI context. This does not enable an integrated model connection.</p>');
 add('ai-master-create','Assisted Project Master Document Creation','<p>Create an editable project brief to discuss with your connected AI client.</p><label>Game concept<input id="ai-concept" maxlength="256"></label><label>Goals and constraints<textarea id="ai-goals" rows="4" maxlength="4000"></textarea></label><button id="ai-master-draft">Create brief template</button><p>The template is assembled locally; no AI generation is claimed.</p>');
 add('ai-talk','Talk to AI assistant','<p>Conversation currently takes place in your connected MCP AI client. Export the project context below to include the master document and assistant instructions.</p><button id="ai-context-export">Export AI context</button><p>Integrated editor chat is not implemented yet.</p>');
 const proposals=add('ai-proposals','AI proposal','<p>Review an isolated proposal before accepting changes into MAIN.</p>');const old=document.querySelector('#menu-section-4');if(old){for(const n of [...old.children].filter(n=>n.tagName!=='SUMMARY'))proposals.append(n);old.remove();}
 add('ai-master-talk','Talk to AI master (advanced)','<p>Use the connected MCP client for architecture and project-wide planning. The master document provides context; proposals still require review. There is no privileged bypass of MAIN/workspace boundaries.</p>');
 const master=document.createElement('details');master.id='project-master-menu';master.innerHTML='<summary>Project Master Document</summary><div class="submenu"><label>Load document · UTF-8 Markdown, text or JSON · max 32 KiB<input id="project-master-file" type="file" accept=".md,.txt,.json,text/plain,text/markdown,application/json"></label><p id="project-master-status" role="status"></p><label>Document text<textarea id="project-master-text" rows="12" maxlength="32768"></textarea></label><button id="project-master-save">Save document</button><button id="project-master-remove">Remove document</button><p id="ai-operation-status" role="status"></p></div>';document.querySelector('#settings-menu .menu-popup').prepend(master);
 const q=id=>document.querySelector('#'+id);let key=null,filename='project-master.md';
 const status=message=>{q('ai-operation-status').textContent=message;};
 const commit=async value=>{try{if(!getSnapshot()?.project)throw Error('Open a project first');if(await save(value)===false)throw Error('Project settings were not saved');status('Project settings saved');}catch(e){status(e.message);reportError(e);}};
 q('ai-instructions-save').addEventListener('click',()=>commit({assistantInstructions:q('ai-instructions').value}));
 q('project-master-file').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>32768||!/\.(md|txt|json)$/i.test(file.name))throw Error('Use a UTF-8 .md, .txt or .json file up to 32 KiB');const text=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer());filename=file.name;q('project-master-text').value=text;await commit({masterDocument:{name:filename,text}});}catch(error){status(error.message);reportError(error);}finally{e.target.value='';}});
 q('project-master-save').addEventListener('click',()=>commit({masterDocument:{name:filename,text:q('project-master-text').value}}));
 q('project-master-remove').addEventListener('click',()=>{filename='project-master.md';q('project-master-text').value='';void commit({masterDocument:{name:filename,text:''}});});
 q('ai-master-draft').addEventListener('click',()=>{filename='project-master.md';q('project-master-text').value='# Project Master Document\n\n## Concept\n'+q('ai-concept').value+'\n\n## Goals and constraints\n'+q('ai-goals').value+'\n\n## Gameplay\n\n## Scenes and assets\n\n## Acceptance criteria\n\n## Milestones\n';menu.open=false;document.querySelector('#settings-menu').open=true;master.open=true;status('Brief template created. Review it and choose Save document.');});
 q('ai-context-export').addEventListener('click',()=>{const s=getSnapshot();if(!s?.project){status('Open a project first');return;}const text=JSON.stringify({project:s.project.name,projectId:s.project.id,sceneRevision:s.sceneRevision,assistantInstructions:s.project.editor?.assistantInstructions??'',masterDocument:s.project.editor?.masterDocument??null},null,2);const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='axiom-ai-context.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 function refresh(){const s=getSnapshot(),editor=s?.project?.editor??{},next=JSON.stringify([s?.project?.id,editor.masterDocument,editor.assistantInstructions]);if(next===key)return;key=next;filename=editor.masterDocument?.name??'project-master.md';q('project-master-text').value=editor.masterDocument?.text??'';q('ai-instructions').value=editor.assistantInstructions??'';q('project-master-status').textContent=editor.masterDocument?.text?'Loaded: '+filename:'No project master document loaded';}
 refresh();const timer=setInterval(refresh,300);return ()=>clearInterval(timer);
}
