export function mountAnimationEditor({document,act,run,mutation,getState,getSelection,getRenderer}){
 const root=document.querySelector('#animation-component');let signature=null;
 const field=(parent,name,value,choices)=>{const label=document.createElement('label');label.textContent=name;const input=document.createElement(choices?'select':'input');input.name=name;if(choices){for(const v of choices){const o=document.createElement('option');o.value=o.textContent=v;input.append(o);}input.value=value;}else if(typeof value==='boolean'){input.type='checkbox';input.checked=value;}else{input.type=typeof value==='number'?'number':'text';input.step='any';input.value=String(value);}label.append(input);parent.append(label);return input;};
 const button=(parent,text,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=text;b.addEventListener('click',fn);parent.append(b);return b;};
 function draw(){if(!root)return;const state=getState(),e=state.project?.scene.entities.find(e=>e.id===getSelection()),key=JSON.stringify([state.project?.id,state.sceneRevision,e?.id,state.playing]);if(signature===key)return;signature=key;root.replaceChildren();root.hidden=!e?.animator;if(!e?.animator)return;
  const title=document.createElement('h3');title.textContent='Animator';root.append(title);const a=structuredClone(e.animator),form=document.createElement('form');root.append(form);const top={};for(const name of ['initialState','speed','autoplay'])top[name]=field(form,name,a[name],name==='initialState'?a.states.map(s=>s.name):null);
  const collections={};for(const key of ['states','parameters','transitions']){const section=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent=key;section.append(legend);form.append(section);const rows=[];collections[key]=rows;
   function row(value){const box=document.createElement('div');box.className='animation-row';const inputs={};for(const [name,v]of Object.entries(value))inputs[name]=field(box,name,v,name==='comparison'?['gt','lt','eq']:null);button(box,'Remove',()=>{box.remove();rows.splice(rows.indexOf(inputs),1);});rows.push(inputs);section.append(box);}
   for(const v of a[key])row(v);button(section,'Add '+key.slice(0,-1),()=>row(key==='states'?{name:'New state',clip:a.states[0].clip,loop:true,speed:1}:key==='parameters'?{name:'Parameter',value:0}:{source:a.states[0].name,target:a.states.at(-1).name,parameter:'',comparison:'gt',threshold:0,duration:.3}));
  }
  const apply=document.createElement('button');apply.type='submit';apply.textContent='Apply Animator';form.append(apply);form.addEventListener('submit',event=>{event.preventDefault();void act(()=>{const read=i=>i.type==='checkbox'?i.checked:i.type==='number'?Number(i.value):i.value;const value={};for(const [k,i]of Object.entries(top))value[k]=read(i);for(const [k,rows]of Object.entries(collections))value[k]=rows.map(row=>Object.fromEntries(Object.entries(row).map(([k,i])=>[k,read(i)])));return run('scene.animator.set',mutation({entityId:e.id,value}));});});
  button(root,'Remove Animator',()=>act(()=>run('scene.component.remove',mutation({entityId:e.id,component:'Animator'}))));for(const input of form.querySelectorAll('input,select,button'))input.disabled=state.playing;
  const runtime=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent='Runtime controls · Play only';runtime.append(legend);root.append(runtime);
  function control(args){return act(()=>getRenderer()?.animationControl({...mutation({entityId:e.id}),...args}));}
  button(runtime,'Pause Animator',()=>control({action:'pause'}));button(runtime,'Resume Animator',()=>control({action:'resume'}));const target=field(runtime,'Runtime state',a.initialState,a.states.map(s=>s.name)),duration=field(runtime,'Crossfade seconds',.5);button(runtime,'Transition now',()=>control({action:'state',name:target.value,duration:Number(duration.value)}));for(const p of a.parameters){const input=field(runtime,p.name,p.value);button(runtime,'Set '+p.name,()=>control({action:'parameter',name:p.name,value:Number(input.value)}));}
  for(const b of runtime.querySelectorAll('button,input,select'))b.disabled=!state.playing;const output=document.createElement('pre');output.dataset.animationStatus='true';root.append(output);
 }
 const timer=setInterval(()=>{const output=root?.querySelector('[data-animation-status]');if(output){const s=getRenderer()?.status(),value=s?.animation?.find(a=>a.entityId===getSelection());output.textContent=JSON.stringify(value?{frame:s.frame,generation:s.generation,...value}:{status:'Waiting for matching frame'},null,2);}},300);timer.unref?.();globalThis.addEventListener?.('pagehide',()=>clearInterval(timer),{once:true});
 async function add(name,e){if(name!=='Animator')return false;if(e.animator)throw Error('Animator already attached');if(e.renderable?.kind!=='mesh')throw Error('Import and attach an animated GLB first');const result=await run('asset.get',{id:getState().project.id,assetId:e.renderable.assetId,...(getState().workspaceId?{workspaceId:getState().workspaceId}:{})});const clip=result.asset?.animation?.clips[0];if(!clip)throw Error('This asset has no supported animation clips');await run('scene.animator.set',mutation({entityId:e.id,value:{initialState:'Default',speed:1,autoplay:true,states:[{name:'Default',clip:clip.name,loop:true,speed:1}],parameters:[],transitions:[]}}));return true;}
 return {draw,add};
}
