import {audioDefaults,sourceDefaults} from '../../../engine/audio/plan.mjs';
export function mountAudioEditor({document,act,run,mutation,getState,getSelection,getRenderer}){
 const root=document.querySelector('#audio-component'),mixer=document.querySelector('#audio-settings');let key=null;
 function field(parent,name,value,options){const l=document.createElement('label');l.textContent=name;const i=document.createElement(options?'select':'input');i.name=name;if(options){for(const [v,label]of options){const o=document.createElement('option');o.value=v;o.textContent=label;i.append(o);}i.value=value;}else if(typeof value==='boolean'){i.type='checkbox';i.checked=value;}else{i.type=typeof value==='number'?'number':'text';i.step='any';i.value=value;}l.append(i);parent.append(l);return i;}
 const read=i=>i.type==='checkbox'?i.checked:i.type==='number'?Number(i.value):i.value;
 function button(parent,label,fn){const b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('click',()=>void act(fn));parent.append(b);return b;}
 function form(parent,title,value,send,choices={}){const section=document.createElement('section'),h=document.createElement('h3');h.textContent=title;section.append(h);parent.append(section);const f=document.createElement('form'),fields={};section.append(f);for(const [k,v]of Object.entries(value))fields[k]=field(f,k,v,choices[k]);const apply=document.createElement('button');apply.type='submit';apply.textContent='Apply '+title;f.append(apply);f.addEventListener('submit',event=>{event.preventDefault();void act(()=>send(Object.fromEntries(Object.entries(fields).map(([k,i])=>[k,read(i)]))));});for(const i of f.querySelectorAll('input,select,button'))i.disabled=!!getState().workspaceId||(parent===mixer&&getState().playing);return section;}
 function draw(){if(!root)return;const s=getState(),e=s.project?.scene.entities.find(e=>e.id===getSelection()),signature=JSON.stringify([s.project?.id,s.sceneRevision,s.playing,e?.id]);if(key===signature)return;key=signature;root.replaceChildren();root.hidden=!e?.audioSource&&!e?.audioListener;mixer?.replaceChildren();const settings=structuredClone(s.project?.scene.audio??audioDefaults);
  if(mixer&&s.project){const master=form(mixer,'Audio mixer',{masterVolume:settings.masterVolume},v=>run('scene.audio.update',mutation({value:{...settings,...v}})));for(const b of settings.buses){form(mixer,'Bus '+b.name,b,value=>run('scene.audio.update',mutation({value:{...settings,buses:settings.buses.map(x=>x.name===b.name?value:x)}})));button(mixer,'Remove bus '+b.name,()=>run('scene.audio.update',mutation({value:{...settings,buses:settings.buses.filter(x=>x.name!==b.name)}}))).disabled=s.playing;}button(master,'Add bus',()=>run('scene.audio.update',mutation({value:{...settings,buses:[...settings.buses,{name:'Bus '+(settings.buses.length+1),volume:1,muted:false,lowpassHz:20000}]}}))).disabled=s.playing;button(master,'Enable browser audio',()=>getRenderer()?.unlockAudio());const runtime=document.createElement('fieldset');mixer.append(runtime);const mv=field(runtime,'Runtime master volume',settings.masterVolume);button(runtime,'Set master volume',()=>getRenderer()?.audioControl(mutation({action:'masterVolume',value:Number(mv.value)})));for(const b of settings.buses){const v=field(runtime,'Runtime '+b.name+' volume',b.volume);button(runtime,'Set bus '+b.name,()=>getRenderer()?.audioControl(mutation({action:'busVolume',name:b.name,value:Number(v.value)})));button(runtime,'Mute bus '+b.name,()=>getRenderer()?.audioControl(mutation({action:'busMute',name:b.name,value:1})));button(runtime,'Unmute bus '+b.name,()=>getRenderer()?.audioControl(mutation({action:'busMute',name:b.name,value:0})));}for(const i of runtime.querySelectorAll('button,input'))i.disabled=!s.playing;}
  if(e?.audioSource){const assets=(s.project.scene.assets??[]).filter(a=>a.kind==='audio'),section=form(root,'AudioSource',e.audioSource,value=>run('scene.audioSource.set',mutation({entityId:e.id,value})),{assetId:assets.map(a=>[a.id,a.name]),bus:settings.buses.map(b=>[b.name,b.name])});button(section,'Remove AudioSource',()=>run('scene.component.remove',mutation({entityId:e.id,component:'AudioSource'}))).disabled=s.playing;const runtime=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent='Audio runtime · Play only';runtime.append(legend);root.append(runtime);for(const action of ['play','pause','resume','stop'])button(runtime,action+' audio',()=>getRenderer()?.audioControl(mutation({entityId:e.id,action}))).disabled=!s.playing;const volume=field(runtime,'Runtime volume',e.audioSource.volume);volume.disabled=!s.playing;button(runtime,'Set runtime volume',()=>getRenderer()?.audioControl(mutation({entityId:e.id,action:'volume',value:Number(volume.value)}))).disabled=!s.playing;const output=document.createElement('pre');output.dataset.audioStatus='true';root.append(output);}
  if(e?.audioListener){const section=form(root,'AudioListener',e.audioListener,value=>run('scene.audioListener.set',mutation({entityId:e.id,value})));button(section,'Remove AudioListener',()=>run('scene.component.remove',mutation({entityId:e.id,component:'AudioListener'}))).disabled=s.playing;}
 }
 const timer=setInterval(()=>{const out=root?.querySelector('[data-audio-status]');if(out){const f=getRenderer()?.status(),a=f?.audio;out.textContent=JSON.stringify({frame:f?.frame,backend:a?.backend,context:a?.contextState,source:a?.sources?.find(i=>i.entityId===getSelection())},null,2);}},300);timer.unref?.();globalThis.addEventListener?.('pagehide',()=>clearInterval(timer),{once:true});
 async function add(name,e){if(!['AudioSource','AudioListener'].includes(name))return false;if(e[name==='AudioSource'?'audioSource':'audioListener'])throw Error(name+' already attached');if(name==='AudioListener'){await run('scene.audioListener.set',mutation({entityId:e.id,value:{enabled:true}}));return true;}const asset=getState().project.scene.assets?.find(a=>a.kind==='audio');if(!asset)throw Error('Import a WAV audio asset first');await run('scene.audioSource.set',mutation({entityId:e.id,value:{...sourceDefaults,assetId:asset.id,bus:(getState().project.scene.audio??audioDefaults).buses[0].name}}));return true;}
 return {draw,add,names:['AudioSource','AudioListener']};
}
