import {audioDefaults,listenerPose,attenuation} from '../../../engine/audio/plan.mjs';
const error=message=>{throw Error('AX_AUDIO_0001: '+message);};
export function createAudioSession({read,forceNull=false,contextFactory=()=>new AudioContext(),workletFactory=(c,o)=>new AudioWorkletNode(c,'axiom-pcm',o)}){
 let context=null,master=null,compressor=null,analyser=null,meter=null,channelMeters=[],channelNodes=[],buses=new Map(),items=new Map(),cache=new Map(),scene={entities:[]},settings=structuredClone(audioDefaults),generation=0,active=false,game=false,globalPaused=false,loaded=false,metadataMap=new Map(),fault=null,worklet=null,disposed=false,reads=0;
 function ensure(){if(context||forceNull||disposed)return;try{context=contextFactory();master=context.createGain();master.gain.value=0;compressor=context.createDynamicsCompressor();analyser=context.createAnalyser();analyser.fftSize=256;meter=new Float32Array(256);master.connect(compressor);compressor.connect(analyser);analyser.connect(context.destination);const split=context.createChannelSplitter(2),silent=context.createGain();silent.gain.value=0;compressor.connect(split);silent.connect(context.destination);for(let c=0;c<2;c++){const a=context.createAnalyser();a.fftSize=256;split.connect(a,c);a.connect(silent);channelNodes.push(a);channelMeters.push(new Float32Array(256));}}catch(e){fault=e.message;}}
 async function unlock(){if(!items.size)return 'no_sources';ensure();if(context&&context.state!=='running')try{await context.resume();}catch(e){fault=e.message;}return context?.state??(forceNull?'null':'unavailable');}
 function halt(i){if(i.node){try{i.node.stop?.();}catch{}i.node.port?.close();i.node.disconnect();i.node=null;}i.gain?.disconnect();i.panner?.disconnect();i.gain=null;i.panner=null;i.offset=0;i.last=0;i.ended=false;i.streamStatus=null;i.filling=false;}
 function clear(){generation++;for(const i of items.values())halt(i);for(const b of buses.values()){b.gain?.disconnect();b.filter?.disconnect();}items.clear();buses.clear();cache.clear();loaded=false;master?.gain.setValueAtTime(0,context.currentTime);}
 async function configure(value,resources,{playing=false}={}){clear();const ticket=generation;scene=value;metadataMap=resources;settings=structuredClone(value.audio??audioDefaults);active=playing;globalPaused=false;if(value.entities.some(e=>e.audioSource))ensure();
  for(const b of settings.buses){const entry={...b};if(context){entry.gain=context.createGain();entry.filter=context.createBiquadFilter();entry.filter.type='lowpass';entry.gain.connect(entry.filter);entry.filter.connect(master);}buses.set(b.name,entry);}
  let decoded=0;for(const e of value.entities.filter(e=>e.audioSource)){const a=structuredClone(e.audioSource),metadata=resources.get(a.assetId);if(!metadata||metadata.kind!=='audio')error('Missing audio metadata');const i={entityId:e.id,a,metadata,wanted:!!a.autoplay,paused:false,ended:false,offset:0,last:0,node:null,streamStatus:null,error:null};items.set(e.id,i);if(forceNull||!context||a.stream||cache.has(a.assetId))continue;decoded+=metadata.frames*metadata.channels*4;if(decoded>16777216)error('Decoded memory budget exceeded');const buffer=context.createBuffer(metadata.channels,metadata.frames,metadata.sampleRate);for(let offset=0;offset<metadata.frames;offset+=4096){const chunk=await read(a.assetId,offset,4096);reads++;if(ticket!==generation||disposed)return;for(let c=0;c<metadata.channels;c++){const data=buffer.getChannelData(c);for(let n=0;n<chunk.frames;n++)data[offset+n]=chunk.samples[n*metadata.channels+c];}}cache.set(a.assetId,buffer);}
  if(ticket!==generation||disposed)return;if(context&&[...items.values()].some(i=>i.a.stream)){worklet??=context.audioWorklet.addModule(new URL('./audio-worklet.mjs',import.meta.url));await worklet;if(ticket!==generation||disposed)return;}loaded=true;step(scene,{playing:active,view:game?'game':'scene',paused:false});
 }
 function position(i){if(i.a.stream)return (i.streamStatus?.positionFrames??0)/i.metadata.sampleRate;if(!i.node)return i.offset;const v=i.offset+(context.currentTime-i.last)*i.a.playbackRate;return i.a.loop?v%i.metadata.durationSeconds:Math.min(v,i.metadata.durationSeconds);}
 async function fill(i,ticket){if(i.filling||i.node===null||i.error||disposed)return;i.filling=true;const node=i.node;try{const remaining=i.metadata.frames-i.nextFrame;if(remaining<=0&&!i.a.loop)return;if(remaining<=0)i.nextFrame=0;const chunk=await read(i.a.assetId,i.nextFrame,Math.min(4096,i.metadata.frames-i.nextFrame));reads++;if(ticket!==generation||i.node!==node||disposed)return;i.nextFrame+=chunk.frames;const data=Float32Array.from(chunk.samples);node.port.postMessage({chunk:data},[data.buffer]);}catch(e){if(ticket===generation)i.error=e.message;}finally{if(i.node===node)i.filling=false;}}
 function connect(i,node){i.node=node;i.gain=context.createGain();node.connect(i.gain);if(i.a.spatial){i.panner=context.createPanner();i.panner.panningModel='equalpower';i.panner.distanceModel='inverse';i.panner.refDistance=i.a.minDistance;i.panner.maxDistance=i.a.maxDistance;i.panner.rolloffFactor=i.a.rolloff;i.gain.connect(i.panner);i.panner.connect(buses.get(i.a.bus).gain);}else i.gain.connect(buses.get(i.a.bus).gain);}
 function start(i){if(!context||forceNull||i.node||!i.wanted||i.ended||!loaded)return;const ticket=generation;try{if(i.a.stream){const node=workletFactory(context,{numberOfInputs:0,numberOfOutputs:1,outputChannelCount:[2],processorOptions:{channels:i.metadata.channels,sampleRate:i.metadata.sampleRate,frames:i.metadata.frames,loop:i.a.loop,rate:i.a.playbackRate}});connect(i,node);i.nextFrame=0;node.port.onmessage=event=>{if(ticket!==generation||i.node!==node)return;const d=event.data;if(d.need)void fill(i,ticket);if(d.error)i.error=d.error;if(d.positionFrames!==undefined){i.streamStatus=d;i.ended=d.ended;}};void fill(i,ticket);}else{const node=context.createBufferSource();node.buffer=cache.get(i.a.assetId);node.loop=i.a.loop;node.playbackRate.value=i.a.playbackRate;connect(i,node);i.last=context.currentTime;node.onended=()=>{if(i.node===node){i.ended=true;i.offset=i.metadata.durationSeconds;i.node=null;node.disconnect();i.gain?.disconnect();i.panner?.disconnect();}};node.start(0,i.offset);}}catch(e){i.error=e.message;}}
 function step(world,{playing,view,paused=false}){scene=world;active=playing;game=view==='game';globalPaused=paused;if(!context)return status();const audible=active&&game&&!globalPaused&&loaded;master.gain.setValueAtTime(audible?settings.masterVolume:0,context.currentTime);const listener=listenerPose(world),l=context.listener;for(const [name,vec]of [['position',listener.position],['forward',listener.forward],['up',listener.up]])for(let c=0;c<3;c++)l[name+['X','Y','Z'][c]].setValueAtTime(vec[c],context.currentTime);
  for(const b of buses.values()){b.gain.gain.setValueAtTime(b.muted?0:b.volume,context.currentTime);b.filter.frequency.setValueAtTime(b.lowpassHz,context.currentTime);}
  for(const i of items.values()){const e=world.entities.find(e=>e.id===i.entityId);if(!e)continue;const should=audible&&!i.paused&&i.wanted&&!i.ended&&!i.error&&context.state==='running';if(should)start(i);if(i.a.stream&&i.node)i.node.port.postMessage({paused:!should});else if(i.node&&!should){i.offset=position(i);const n=i.node;i.node=null;n.onended=null;try{n.stop();}catch{}n.disconnect();i.gain?.disconnect();i.panner?.disconnect();i.last=0;}
   i.gain?.gain.setValueAtTime(i.a.volume,context.currentTime);if(i.panner)for(let c=0;c<3;c++)i.panner['position'+['X','Y','Z'][c]].setValueAtTime(e.transform.position[c],context.currentTime);
  }return status();}
 function reason(i){const b=buses.get(i.a.bus);return forceNull?'Null audio backend':!context?'Audio backend unavailable':i.error?'Source error: '+i.error:!active?'Play is stopped':!game?'Scene view is silent':globalPaused?'Simulation paused':!loaded?'Audio is loading':context.state!=='running'?'Browser audio activation required':!i.wanted?'Source stopped':i.paused?'Source paused':i.ended?'Nonlooping source completed':settings.masterVolume===0?'Master volume is zero':b?.muted?'Bus muted':b?.volume===0?'Bus volume is zero':i.a.volume===0?'Source volume is zero':i.a.stream&&!i.streamStatus?.queuedFrames?'Stream buffering':null;}
 function status(){let rms=null;if(analyser&&context.state==='running'){analyser.getFloatTimeDomainData(meter);rms=Math.sqrt(meter.reduce((n,v)=>n+v*v,0)/meter.length);}const stereoRms=channelNodes.map((a,c)=>{a.getFloatTimeDomainData(channelMeters[c]);return Math.sqrt(channelMeters[c].reduce((n,v)=>n+v*v,0)/256);});const listener=listenerPose(scene);return {stereoRms,backend:forceNull?'null':context?'webaudio':'unavailable',contextState:context?.state??null,fault,loaded,reads,decodedBytes:[...cache.values()].reduce((n,b)=>n+b.length*b.numberOfChannels*4,0),masterRms:rms,listener,mixer:{masterVolume:settings.masterVolume,limiter:!!compressor,buses:[...buses.values()].map(b=>({name:b.name,volume:b.volume,muted:b.muted,lowpassHz:b.lowpassHz}))},sources:[...items.values()].map(i=>{const e=scene.entities.find(e=>e.id===i.entityId),why=reason(i);return {entityId:i.entityId,assetId:i.a.assetId,bus:i.a.bus,stream:i.a.stream,spatial:i.a.spatial,transportActive:!!i.node&&active&&game&&!globalPaused&&!i.paused&&!i.ended&&context?.state==='running',positionSeconds:position(i),durationSeconds:i.metadata.durationSeconds,volume:i.a.volume,playing:!!i.node&&!why,whyAudioNotPlaying:why,attenuation:attenuation(i.a,e?.transform.position??[0,0,0],listener),queuedFrames:i.streamStatus?.queuedFrames??0,capacityFrames:i.a.stream?16384:0,underruns:i.streamStatus?.underruns??0};})};}
 function reconcile(world){scene=world;for(const [id,i]of items)if(!world.entities.some(e=>e.id===id&&e.audioSource)){halt(i);items.delete(id);}for(const e of world.entities.filter(e=>e.audioSource&&!items.has(e.id))){if(items.size>=32)error('Voice budget exceeded');const a=structuredClone(e.audioSource),metadata=metadataMap.get(a.assetId);if(!metadata)error('Missing spawned audio resource');items.set(e.id,{entityId:e.id,a,metadata,wanted:!!a.autoplay,paused:false,ended:false,offset:0,last:0,node:null,streamStatus:null,error:null});}}
 function control(args){if(!active)error('Play is required');if(args.action==='masterVolume'){if(!Number.isFinite(args.value)||args.value<0||args.value>1)error('Invalid master volume');settings.masterVolume=args.value;}else if(['busVolume','busMute'].includes(args.action)){const b=buses.get(args.name);if(!b||!Number.isFinite(args.value)||args.value<0||args.value>1)error('Invalid bus/value');if(args.action==='busVolume')b.volume=args.value;else b.muted=!!args.value;}else{const i=items.get(args.entityId);if(!i)error('AudioSource required');if(args.action==='play'){halt(i);i.wanted=true;i.paused=false;}else if(args.action==='stop'){halt(i);i.wanted=false;}else if(args.action==='pause')i.paused=true;else if(args.action==='resume'){i.wanted=true;i.paused=false;}else if(args.action==='volume'){if(!Number.isFinite(args.value)||args.value<0||args.value>1)error('Invalid volume');i.a.volume=args.value;}else error('Unknown audio action');}step(scene,{playing:active,view:game?'game':'scene',paused:globalPaused});const observed=status();return {backend:observed.backend,contextState:observed.contextState,mixer:observed.mixer,source:observed.sources.find(i=>i.entityId===args.entityId)??null};}
 return {configure,reconcile,step,status,control,unlock,clear,dispose(){disposed=true;clear();void context?.close();}};
}
