export function mountAutonomyEditor({document,getSnapshot,send,reportError}){
 if(!document.defaultView)return ()=>{};
 const host=document.querySelector('#ai-proposals .submenu'),box=document.createElement('section');box.id='autonomy-panel';box.innerHTML='<h3>Autonomy loop</h3><p>Run a bounded objective in an isolated proposal. Review and accept the result above; MAIN is never accepted automatically.</p><label>Saved objectives<select id="autonomy-plans"></select></label><label>Objective and acceptance plan<textarea id="autonomy-plan" rows="10" spellcheck="false"></textarea></label><div class="actions"><button id="autonomy-run">Run objective</button><button id="autonomy-cancel" disabled>Cancel</button><button id="autonomy-export" disabled>Export evidence</button></div><p id="autonomy-status" role="status">Choose a saved objective or supply a structured plan from your AI client.</p><ol id="autonomy-timeline"></ol><details><summary>Evidence and change set</summary><pre id="autonomy-result"></pre></details>';host.append(box);
 const q=id=>document.querySelector('#autonomy-'+id);let project=null,session=null,result=null,pending=false,stopped=false;
 function selectPlan(){const snapshot=getSnapshot(),plan=snapshot?.project?.editor?.autonomyPlans?.[Number(q('plans').value)];q('plan').value=JSON.stringify(plan??{objective:'Verify entity count',suite:{name:'Count',steps:[{frames:1,assertions:[{kind:'entityCount',count:snapshot?.project?.scene.entities.length??0}]}]},actions:[],repairPolicy:'none',maxIterations:2,maxSeconds:300},null,2);}
 q('plans').addEventListener('change',selectPlan);q('run').addEventListener('click',async()=>{try{const snapshot=getSnapshot();if(!snapshot?.project)throw Error('Open and save a project first');const plan=JSON.parse(q('plan').value);const r=await send('autonomy.control',{action:'run',id:snapshot.project.id,expectedSceneRevision:snapshot.sceneRevision,plan});result=r.payload.data;session=result.id;paint();}catch(error){q('status').textContent=error.message;reportError(error);}});
 q('cancel').addEventListener('click',()=>void send('autonomy.control',{action:'cancel',sessionId:session}).catch(reportError));
 q('export').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='axiom-autonomy-evidence.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 function paint(){const active=result?.status==='running',snapshot=getSnapshot();q('run').disabled=active||!snapshot?.project||snapshot.playing||snapshot.dirty||!!snapshot.workspaceId;q('cancel').disabled=!active;q('export').disabled=!result;q('status').textContent=result?`${result.status} · ${result.phase} · iteration ${result.iteration}${result.error?' · '+result.error.message:''}`:q('status').textContent;q('result').textContent=result?JSON.stringify(result,null,2):'';q('timeline').replaceChildren();for(const e of result?.evidence??[]){const item=document.createElement('li');item.textContent=`Attempt ${e.iteration} · ${e.kind} · ${e.passed===undefined?e.cause:e.passed?'Passed':'Failed'}${e.durationMs!==undefined?' · '+e.durationMs.toFixed(1)+' ms':''}`;q('timeline').append(item);}}
 async function refresh(){if(stopped||pending)return;pending=true;try{const snapshot=getSnapshot();if(snapshot?.project?.id!==project){project=snapshot?.project?.id??null;session=null;result=null;q('plans').replaceChildren();for(const[i,plan]of (snapshot?.project?.editor?.autonomyPlans??[]).entries()){const o=document.createElement('option');o.value=i;o.textContent=plan.objective;q('plans').append(o);}selectPlan();}if(session)result=(await send('autonomy.control',{action:'query',sessionId:session})).payload.data;paint();}catch(error){q('status').textContent=error.message;}finally{pending=false;}}
 const timer=setInterval(()=>void refresh(),500);void refresh();return ()=>{stopped=true;clearInterval(timer);};
}
