import {projectFiles} from '../../../engine/scene/project-files.mjs';
export function mountCodeEditor({document,getState,write,show,persist=async()=>{},onDirty=()=>{},onOpen=()=>{},onSaved=()=>{},reportError}) {
 if(!document.defaultView)return {draw(){},flush:async()=>true,dirty:()=>false,open(){},filesChanged(){}};
 const q=id=>document.querySelector('#'+id),buffers=new Map();let current=null,projectId=null,flight=null;
 const sceneFile=path=>getState().project?projectFiles(getState().project.scene).find(f=>f.path===path):undefined;
 const dirty=()=>[...buffers.values()].some(b=>b.text!==b.saved),readonly=()=>getState().workspaceId;
 function lines(){q('ide-lines').textContent=Array.from({length:(q('ide-code').value.match(/\n/g)?.length??0)+1},(_,i)=>i+1).join('\n');q('ide-lines').scrollTop=q('ide-code').scrollTop;}
 function activate(path){const previous=buffers.get(current);if(previous){previous.start=q('ide-code').selectionStart;previous.end=q('ide-code').selectionEnd;previous.scroll=q('ide-code').scrollTop;}current=path;const b=buffers.get(path);onOpen({...sceneFile(path),path,kind:'script',text:b.text});paint();q('ide-code').focus();q('ide-code').setSelectionRange(b.start??0,b.end??0);q('ide-code').scrollTop=b.scroll??0;}
 function tabs(){const host=q('ide-tabs'),list=q('ide-open-list');if(!document.createElement||!host?.replaceChildren)return;host.replaceChildren();list.replaceChildren();for(const[path,b]of buffers){const name=path.split('/').at(-1).replace(/\.cs$/i,'')+(b.text!==b.saved?'*':'');const tab=document.createElement('div');tab.className='ide-tab'+(path===current?' active':'')+(b.text!==b.saved?' dirty':'');tab.setAttribute('role','tab');tab.setAttribute('aria-selected',String(path===current));const title=document.createElement('button');title.textContent=name;title.title=path;title.addEventListener('click',()=>activate(path));const close=document.createElement('button');close.className='icon-button';close.innerHTML='<img src="/icons/close.svg" alt="">';close.setAttribute('aria-label','Close '+name);close.addEventListener('click',()=>{if(b.text!==b.saved&&!document.defaultView.confirm('Discard unsaved changes in '+path+'?'))return;buffers.delete(path);if(current===path)current=[...buffers.keys()].at(-1)??null;paint();});tab.append(title,close);host.append(tab);const item=document.createElement('button');item.textContent=name;item.title=path;item.addEventListener('click',()=>{q('ide-open-menu').open=false;activate(path);});list.append(item);}}
 function paint(){const b=buffers.get(current),disabled=!b||readonly();q('ide-code').disabled=!!disabled;q('ide-file-save').disabled=disabled||b.text===b.saved;if(q('ide-save-all'))q('ide-save-all').disabled=!!readonly()||!dirty();q('ide-status').textContent=b?current+(b.text!==b.saved?' *':''):'Double-click a C# file in Project to open it';if(q('ide-code').value!==(b?.text??''))q('ide-code').value=b?.text??'';lines();tabs();onDirty(dirty());}
 async function flush(path=null){if(readonly()){if(dirty())throw Error('Leave the proposal preview before saving pending source');return true;}if(flight){await flight;return flush(path);}flight=(async()=>{for(const[key,b]of buffers){if(path&&key!==path||b.text===b.saved)continue;const text=b.text;const ok=await write({action:'write',path:key,text});if(ok!==true)throw Error('Source was not saved; finish the current editor operation and retry');b.saved=text;if(key===current)onOpen({...sceneFile(key),path:key,kind:'script',text});}return true;})().finally(()=>{flight=null;paint();onSaved();});return flight;}
 async function save(all=false){await flush(all?null:current);await persist();}
 async function open(file){if(file.kind!=='script')return;try{if(getState().project?.id!==projectId)draw();if(!buffers.has(file.path))buffers.set(file.path,{text:file.text,saved:file.text});show('ide');activate(file.path);}catch(e){reportError(e);}}
 function draw(){const state=getState();if(state.project?.id!==projectId){buffers.clear();current=null;projectId=state.project?.id;}for(const[path,b]of buffers){const f=sceneFile(path);if(!f){if(b.text===b.saved){buffers.delete(path);if(current===path)current=null;}continue;}if(b.text===b.saved&&f.text!==b.saved){b.text=b.saved=f.text;if(path===current)onOpen(f);}}paint();}
 function filesChanged(data){if(data.action==='move'){for(const[path,b]of [...buffers])if(path===data.path||path.startsWith(data.path+'/')){buffers.delete(path);const next=data.to+path.slice(data.path.length),f=sceneFile(next);buffers.set(next,{...b,text:f?.text??b.text,saved:f?.text??b.saved});if(current===path){current=next;if(f)onOpen(f);}}}draw();}
 q('ide-code').addEventListener('input',()=>{const b=buffers.get(current);if(b){b.text=q('ide-code').value;paint();}});q('ide-code').addEventListener('scroll',lines);
 q('ide-code').addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();const code=q('ide-code');code.setRangeText('    ',code.selectionStart,code.selectionEnd,'end');code.dispatchEvent(new Event('input',{bubbles:true}));}});
 q('ide-file-save').addEventListener('click',()=>void save().catch(reportError));q('ide-save-all')?.addEventListener('click',()=>void save(true).catch(reportError));
 function find(next=false){const code=q('ide-code'),word=q('ide-find').value;if(!word)return;const text=code.value.toLowerCase(),start=next?code.selectionEnd:0;let index=text.indexOf(word.toLowerCase(),start);if(index<0&&next)index=text.indexOf(word.toLowerCase());q('ide-search-status').textContent=index<0?'Not found':'';if(index>=0)code.setSelectionRange(index,index+word.length);}
 q('ide-find').addEventListener('input',()=>find());q('ide-find-next')?.addEventListener('click',()=>find(true));
 function replace(all=false){if(readonly()||!buffers.has(current))return;const code=q('ide-code'),word=q('ide-find').value;if(!word)return;const replacement=q('ide-replace').value;if(all){const escaped=word.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');code.value=code.value.replace(new RegExp(escaped,'gi'),()=>replacement);}else{if(code.value.slice(code.selectionStart,code.selectionEnd).toLowerCase()!==word.toLowerCase())find();if(code.value.slice(code.selectionStart,code.selectionEnd).toLowerCase()===word.toLowerCase())code.setRangeText(replacement,code.selectionStart,code.selectionEnd,'end');}code.dispatchEvent(new Event('input',{bubbles:true}));}
 q('ide-replace-one')?.addEventListener('click',()=>replace());q('ide-replace-all')?.addEventListener('click',()=>replace(true));
 document.addEventListener?.('keydown',e=>{if(!e.target.closest?.('#ide-content')||!(e.ctrlKey||e.metaKey))return;if(e.code==='KeyS'){e.preventDefault();e.stopPropagation();void save(e.shiftKey).catch(reportError);}if(e.code==='KeyF'){e.preventDefault();e.stopPropagation();q('ide-search').hidden=false;q('ide-find').focus();q('ide-find').select();}});
 return {draw,flush,dirty,open,filesChanged,current:()=>current,save};
}
