export const dockDefaults={hierarchy:'left',inspector:'right',project:'bottom',console:'bottom',diagnostics:'bottom',profiler:'bottom',scene:'center',game:'center'};
const positions=['left','right','top','bottom','center'];
// Panels keep their actual DOM nodes and handlers. There is one renderer/lease,
// even when controls live in another same-origin window.
export function createEditorDocument(root) {
  if(!root.defaultView)return root;
  const documents=new Set([root]),listeners=[];
  return new Proxy(root,{get(target,key){
    if(key==='attachWindow')return win=>{documents.add(win.document);for(const [type,fn,options]of listeners)win.document.addEventListener(type,fn,options);return ()=>documents.delete(win.document);};
    if(key==='querySelector')return selector=>{for(const doc of documents){const node=doc.querySelector(selector);if(node)return node;}return null;};
    if(key==='querySelectorAll')return selector=>[...documents].flatMap(doc=>[...doc.querySelectorAll(selector)]);
    if(key==='addEventListener')return (type,fn,options)=>{listeners.push([type,fn,options]);for(const doc of documents)doc.addEventListener(type,fn,options);};
    const value=Reflect.get(target,key,target);return typeof value==='function'?value.bind(target):value;
  }});
}
export function mountDockLayout({document,save,isBusy,onView=()=>{},onParallel=()=>{}}) {
  if(!document.defaultView)return {set(){},value:()=>undefined};
  const workspace=document.querySelector('#editor-workspace'),center=document.querySelector('.center');
  const nodes={hierarchy:document.querySelector('.hierarchy'),inspector:document.querySelector('.inspector'),...Object.fromEntries(['project','console','diagnostics','profiler'].map(id=>[id,document.querySelector('#'+id+'-content')]))};
  const viewTabs={scene:document.querySelector('#scene-tab'),game:document.querySelector('#game-tab')};
  const viewNav=center.querySelector(':scope > .tabs'),viewport=document.querySelector('.viewport'),surface=document.createElement('div');surface.className='dock-viewport-surface';surface.append(viewNav,viewport);
  for(const id of ['scene','game']){const node=document.createElement('section');node.id=id+'-content';const preview=document.createElement('canvas');preview.width=960;preview.height=540;preview.className='parallel-viewport';preview.tabIndex=0;preview.dataset.parallelView=id;preview.setAttribute('aria-label',id+' parallel viewport');node.append(preview);nodes[id]=node;}
  const originalBottom=document.querySelector('.console'),slots={},tabs={},windows=new Map();let layout={...dockDefaults},applying=false;const closed=new Set();const menu=document.createElement('details');menu.id='panels-menu';const summary=document.createElement('summary');summary.textContent='Panels';const popup=document.createElement('div');popup.className='menu-popup';menu.append(summary,popup);document.querySelector('#settings-menu').before(menu);
  workspace.classList.add('docked');
  for(const position of positions){const slot=document.createElement('section');slot.className='dock-slot dock-'+position;slot.dataset.dock=position;const nav=document.createElement('nav');nav.className='tabs dock-tabs';nav.setAttribute('aria-label','Dock '+position+' tabs');const body=document.createElement('div');body.className='dock-body';slot.append(nav,body);workspace.append(slot);slots[position]={slot,nav,body};slot.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('application/axiom-panel')){e.preventDefault();workspace.classList.add('dock-dragging');slot.classList.add('dock-target');}});slot.addEventListener('dragleave',e=>{if(!slot.contains(e.relatedTarget))slot.classList.remove('dock-target');});slot.addEventListener('drop',e=>{const id=e.dataTransfer.getData('application/axiom-panel');if(!(id in nodes)||isBusy())return;e.preventDefault();workspace.classList.remove('dock-dragging');for(const {slot}of Object.values(slots))slot.classList.remove('dock-target');const target=e.target.closest?.('[data-panel]');if(target?.dataset.panel===id)return;place(id,position,target?.dataset.panel,eventBefore(e,target));persist();});}
  const resizer=document.querySelector('#bottom-resizer');slots.bottom.slot.prepend(resizer);
  for(const [id,node]of Object.entries(nodes)){
    const tab=viewTabs[id]??document.querySelector('#'+id+'-tab')??document.createElement('button');tab.id=id+'-tab';if(!tab.textContent)tab.textContent=id==='hierarchy'?'Hierarchy':'Inspector';tab.draggable=true;tab.dataset.panel=id;tab.title='Drag to a dock, or use panel options';tab.addEventListener('dragstart',e=>{e.dataTransfer.setData('application/axiom-panel',id);workspace.classList.add('dock-dragging');});tab.addEventListener('dragend',()=>{workspace.classList.remove('dock-dragging');for(const {slot}of Object.values(slots))slot.classList.remove('dock-target');});tab.addEventListener('click',()=>activate(id));tabs[id]=tab;node.classList.add('dock-panel');
    const controls=document.createElement('div');controls.className='dock-panel-controls';controls.dataset.controls=id;const select=document.createElement('select');select.setAttribute('aria-label','Dock '+id);for(const p of positions){const option=document.createElement('option');option.value=p;option.textContent=p[0].toUpperCase()+p.slice(1);select.append(option);}select.value=layout[id];select.addEventListener('change',()=>{if(isBusy()){select.value=layout[id];return;}place(id,select.value);persist();});const detach=document.createElement('button');detach.innerHTML='<svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true"><path d="M14 3h7v7m0-7L11 13M10 5H5a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-5" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';detach.title='Separate window';detach.setAttribute('aria-label','Separate '+id+' window');detach.dataset.detach=id;detach.addEventListener('click',()=>detachPanel(id));const close=document.createElement('button');close.textContent='×';close.title='Close panel';close.setAttribute('aria-label','Close '+id+' panel');close.dataset.close=id;close.addEventListener('click',()=>{if(isBusy())return;restore(id);closed.add(id);nodes[id].hidden=true;tabs[id].hidden=true;const controls=document.querySelector('[data-controls="'+id+'"]');if(controls)nodes[id].prepend(controls);const remaining=Object.keys(nodes).find(k=>layout[k]===layout[id]&&!closed.has(k)&&!windows.has(k));if(remaining)activate(remaining);paint();persist();});controls.append(select,detach,close);const open=document.createElement('button');open.textContent=tab.textContent;open.dataset.openPanel=id;open.addEventListener('click',()=>{if(isBusy())return;closed.delete(id);tabs[id].hidden=false;activate(id);menu.open=false;paint();persist();});popup.append(open);node.prepend(controls);place(id,layout[id]);
  }
  originalBottom.remove();center.remove();activate('scene');activate('project');
  function activate(id,activateViewport=true){if(closed.has(id))return;if(activateViewport&&(id==='scene'||id==='game')){nodes[id].append(surface);for(const name of ['scene','game'])nodes[name].querySelector('.parallel-viewport').hidden=name===id;onView(id);}const position=layout[id];if(windows.has(id)){nodes[id].hidden=false;windows.get(id).win.focus();return;}for(const other of Object.keys(nodes).filter(k=>layout[k]===position&&!windows.has(k)&&!closed.has(k))){nodes[other].hidden=other!==id;tabs[other]?.classList.toggle('active',other===id);const controls=nodes[other].querySelector('.dock-panel-controls')??slots[position].nav.querySelector('[data-controls="'+other+'"]');if(controls){if(other===id)slots[position].nav.append(controls);else nodes[other].prepend(controls);}}paint();}
  function restore(id){const floating=windows.get(id);if(!floating)return;windows.delete(id);const controls=floating.win.document.querySelector('[data-controls="'+id+'"]');if(controls)nodes[id].prepend(controls);floating.unregister();place(id,layout[id]);if(!floating.win.closed)floating.win.close();}
  function eventBefore(e,target){if(!target)return true;const r=target.getBoundingClientRect();return e.clientX<r.x+r.width/2;}
  function place(id,position,beforeId,before=true){if(!positions.includes(position))return;const previous=layout[id];const panelControls=document.querySelector('[data-controls="'+id+'"]');if(panelControls)nodes[id].prepend(panelControls);const floating=windows.get(id);if(floating){windows.delete(id);const controls=floating.win.document.querySelector('[data-controls="'+id+'"]');if(controls)nodes[id].prepend(controls);floating.unregister();if(!floating.win.closed)floating.win.close();}layout[id]=position;const anchor=beforeId?tabs[beforeId]:null;if(anchor?.parentElement===slots[position].nav)slots[position].nav.insertBefore(tabs[id],before?anchor:anchor.nextSibling);else if(tabs[id].parentElement!==slots[position].nav)slots[position].nav.append(tabs[id]);slots[position].body.append(nodes[id]);document.querySelector('[aria-label="Dock '+id+'"]').value=position;activate(id);if(previous!==position){const remaining=Object.keys(nodes).filter(k=>layout[k]===previous&&!windows.has(k)&&!closed.has(k));if(remaining.length&&!remaining.some(k=>!nodes[k].hidden))activate(remaining[0],false);}paint();}
  function paint(){for(const [position,{slot,body}]of Object.entries(slots))slot.hidden=![...body.children].some(n=>!closed.has(Object.keys(nodes).find(k=>nodes[k]===n)));workspace.classList.toggle('dock-has-center',!slots.center.slot.hidden);workspace.classList.toggle('dock-has-top',!slots.top.slot.hidden);workspace.classList.toggle('dock-has-bottom',!slots.bottom.slot.hidden);workspace.classList.toggle('dock-has-left',!slots.left.slot.hidden);workspace.classList.toggle('dock-has-right',!slots.right.slot.hidden);const primary=surface.closest('.dock-panel')?.id.replace('-content','');const other=['scene','game'].find(id=>id!==primary&&!nodes[id].hidden&&!closed.has(id));onParallel(other?{canvas:nodes[other].querySelector('.parallel-viewport'),view:other}:null);}
  function order(){return positions.flatMap(p=>[...slots[p].nav.querySelectorAll('[data-panel]')].map(n=>n.dataset.panel));}
  function persist(){if(!applying)void save({...layout,order:order(),closed:[...closed]});}
  function detachPanel(id){if(windows.has(id)||isBusy())return;const win=document.defaultView.open('','_blank','popup,width=850,height=650');if(!win){document.querySelector('[data-detach="'+id+'"]').title='Popup blocked · allow and retry';return;}win.document.title='Axiom · '+tabs[id].textContent;const style=win.document.createElement('link');style.rel='stylesheet';style.href=new URL('/styles.css',document.defaultView.location.href).href;win.document.head.append(style);win.document.body.className='detached-editor';for(const type of ['keydown','keyup'])win.addEventListener(type,e=>{if(/^(INPUT|TEXTAREA|SELECT)$/.test(e.target.tagName)||e.target.isContentEditable)return;const forwarded=new document.defaultView.KeyboardEvent(type,{code:e.code,key:e.key,ctrlKey:e.ctrlKey,shiftKey:e.shiftKey,altKey:e.altKey,metaKey:e.metaKey});Object.defineProperty(forwarded,'axiomView',{value:id});document.defaultView.dispatchEvent(forwarded);});win.addEventListener('blur',()=>document.defaultView.dispatchEvent(new Event('blur')));const returnButton=win.document.createElement('button');returnButton.textContent='↙ Return to editor';returnButton.addEventListener('click',()=>restore(id));const header=win.document.createElement('header');header.className='tabs';header.append(returnButton);const controls=document.querySelector('[data-controls="'+id+'"]');header.append(controls);win.document.body.append(header);const unregister=document.attachWindow(win);windows.set(id,{win,unregister});win.document.body.append(nodes[id]);tabs[id].textContent=tabs[id].textContent.replace(/ ↗$/,'')+' ↗';nodes[id].hidden=false;win.addEventListener('pagehide',()=>{tabs[id].textContent=tabs[id].textContent.replace(/ ↗$/,'');restore(id);});const replacement=Object.keys(nodes).find(k=>k!==id&&layout[k]===layout[id]&&!windows.has(k));if(replacement)activate(replacement);paint();}
  document.defaultView.addEventListener('pagehide',()=>{for(const id of [...windows.keys()])restore(id);},{once:true});
  const reset=document.createElement('button');reset.id='dock-reset';reset.textContent='Reset panel layout';reset.addEventListener('click',()=>{if(isBusy())return;closed.clear();for(const id of Object.keys(nodes)){tabs[id].hidden=false;restore(id);place(id,dockDefaults[id]);}for(const id of ['hierarchy','inspector','scene','project'])activate(id);persist();});document.querySelector('#settings-menu .menu-popup').append(reset);
  return {activateView:activate,value:()=>({...layout,order:order(),closed:[...closed]}),set(value){const next={...dockDefaults,...value};if(Object.keys(nodes).every(id=>next[id]===layout[id])&&(!value?.order||JSON.stringify(value.order)===JSON.stringify(order()))&&JSON.stringify(value?.closed??[])===JSON.stringify([...closed]))return;applying=true;for(const id of Object.keys(nodes))if(next[id]!==layout[id])place(id,next[id]);for(const id of value?.order??Object.keys(nodes))if(tabs[id])slots[layout[id]].nav.append(tabs[id]);for(const {nav}of Object.values(slots)){const c=nav.querySelector('.dock-panel-controls');if(c)nav.append(c);}closed.clear();for(const id of value?.closed??[])if(nodes[id])closed.add(id);for(const id of Object.keys(nodes)){tabs[id].hidden=closed.has(id);if(closed.has(id))nodes[id].hidden=true;}for(const position of positions){const remaining=Object.keys(nodes).filter(k=>layout[k]===position&&!closed.has(k)&&!windows.has(k));if(remaining.length&&!remaining.some(k=>!nodes[k].hidden))activate(remaining[0]);}paint();applying=false;}};
}
