// One delegated menu contract covers static menus, dynamic AI branches and contexts.
export function mountEditorMenu(document){
 if(!document.defaultView)return;
 function closeBranches(root){for(const d of root.querySelectorAll('details'))d.open=false;}
 function position(detail){const popup=detail.querySelector(':scope > .submenu,:scope > .menu-popup');if(!popup)return;const win=detail.ownerDocument.defaultView,summary=detail.querySelector(':scope > summary'),anchor=summary.getBoundingClientRect(),nested=popup.classList.contains('submenu');popup.style.position='fixed';popup.style.right='auto';popup.style.maxWidth=Math.max(100,win.innerWidth-16)+'px';popup.style.maxHeight=Math.max(80,win.innerHeight-16)+'px';popup.style.left='0px';popup.style.top='0px';let rect=popup.getBoundingClientRect(),left=nested?anchor.right:anchor.left,top=nested?anchor.top:anchor.bottom;if(nested&&left+rect.width>win.innerWidth-8)left=anchor.left-rect.width;left=Math.max(8,Math.min(left,win.innerWidth-rect.width-8));top=Math.max(8,Math.min(top,win.innerHeight-rect.height-8));popup.style.left=left+'px';popup.style.top=top+'px';popup.style.overflowY=popup.scrollHeight>win.innerHeight-16?'auto':'visible';}
 document.addEventListener('click',event=>{const summary=event.target.closest?.('summary'),detail=summary?.parentElement;if(!detail||detail.tagName!=='DETAILS'||!summary.closest('.menubar,.editor-context'))return;for(const sibling of detail.parentElement.children)if(sibling!==detail&&sibling.tagName==='DETAILS'){sibling.open=false;closeBranches(sibling);}},{capture:true});
 document.addEventListener('toggle',event=>{const detail=event.target;if(detail.tagName!=='DETAILS'||!detail.closest?.('.menubar,.editor-context'))return;if(!detail.open){closeBranches(detail);return;}position(detail);detail.ownerDocument.defaultView.requestAnimationFrame(()=>{if(detail.open)position(detail);});},{capture:true});
 document.defaultView.addEventListener('resize',()=>{for(const d of document.querySelectorAll('.menubar details[open],.editor-context details[open]'))position(d);});
}
