import {scriptMetadata,scriptComponents} from '../../../engine/scripting/fields.mjs';
const componentKeys={Transform:'transform',Script:'script',Camera:'camera',Renderable:'renderable',Material:'material',Light:'light',LOD:'lod',Collider:'collider',RigidBody:'rigidBody',Animator:'animator',AudioSource:'audioSource',AudioListener:'audioListener',Sprite2D:'sprite2D',SpriteAnimation:'spriteAnimation',Tilemap:'tilemap',Light2D:'light2D',Particles2D:'particles2D',UI2D:'ui2D'};
export function mountEditorActions({document,getState,getSelection,select,act,run,mutation,browser,reportError,locate,scriptEditor}){
 if(!document.defaultView)return {draw(){}};
 let clipboard=null,renameTimer=null,context=null,lastClickedEntity=null,lastScope=null;
 const q=id=>document.querySelector('#'+id),editable=()=>!!getState().project&&!getState().playing&&!getState().workspaceId;
 const close=()=>{context?.remove();context=null;};
 async function copy(value){clipboard=value;try{await navigator.clipboard.writeText(JSON.stringify({axiomClipboard:1,...value}));}catch{/* Internal clipboard remains available. */}}
 async function readClipboard(){if(clipboard)return clipboard;try{const text=await navigator.clipboard.readText();if(text.length>196000)return null;const v=JSON.parse(text);if(v.axiomClipboard===1&&['files','entities','component'].includes(v.kind))return v;return null;}catch{return clipboard;}}
 const entity=()=>getState().project?.scene.entities.find(e=>e.id===getSelection().at(-1));
 const filesCopy=()=>copy({kind:'files',projectId:getState().project.id,paths:browser.selection()});
 function entitiesCopy(){const s=getState(),ids=new Set(getSelection());let changed=true;while(changed){changed=false;for(const e of s.project.scene.entities)if(ids.has(e.parentId)&&!ids.has(e.id)){ids.add(e.id);changed=true;}}return copy({kind:'entities',projectId:s.project.id,entities:s.project.scene.entities.filter(e=>ids.has(e.id)),scriptAttachments:s.project.scene.script?.attachments.filter(id=>ids.has(id))??[]});}
 function valid(v,kind){if(!v||v.kind!==kind||!editable())return false;const s=getState();if(kind==='component'&&v.component==='ScriptFile')return v.projectId===s.project.id&&getSelection().length===1&&browser.files().some(f=>f.path===v.value.path);if(kind==='files')return v.projectId===s.project.id&&Array.isArray(v.paths)&&v.paths.length>0&&v.paths.every(p=>browser.files().some(f=>f.path===p));if(kind==='entities')return v.projectId===s.project.id&&Array.isArray(v.entities)&&v.entities.length>0&&v.entities.length<=256;return !!componentKeys[v.component]&&v.value&&getSelection().length===1;}
 async function paste(kind,target,v){v??=await readClipboard();if(!valid(v,kind))return;
  if(kind==='files')return browser.edit({action:'copy',paths:v.paths,to:target??browser.folder()});
  if(kind==='entities')return act(()=>run('scene.entities.paste',mutation({entities:v.entities,scriptAttachments:v.scriptAttachments,...(target?{parentId:target}:{})})));
  const e=entity();if(!e)return;if(v.component==='ScriptFile')return act(async()=>{if(!e.scriptComponents?.some(c=>c.path===v.value.path))await run('scene.script.edit',mutation({entityId:e.id,path:v.value.path,action:'attach'}));await run('scene.script.edit',mutation({entityId:e.id,path:v.value.path,action:'values',values:Object.fromEntries(Object.entries(v.value.values).filter(([name])=>scriptMetadata(browser.files().find(f=>f.path===v.value.path)).fields.some(f=>f.name===name&&!f.readOnly)))}));});return act(()=>run('scene.component.paste',mutation({entityId:e.id,component:v.component,value:v.value})));
 }
 function remove(component){return act(()=>run('scene.component.remove',mutation({entityId:entity()?.id,component})));}
 function renameEntity(id,node){if(!editable())return;clearTimeout(renameTimer);const e=getState().project.scene.entities.find(e=>e.id===id);if(!e)return;const button=node.querySelector('.entity')??node,old=button.textContent,input=document.createElement('input');input.value=e.name;input.maxLength=128;button.textContent='';button.append(input);input.focus();input.select();let done=false;async function finish(cancel=false){if(done)return;done=true;button.textContent=old;const name=input.value.trim();if(!cancel&&name&&name!==e.name)await act(()=>run('scene.entity.update',mutation({entityId:id,name})));}input.addEventListener('keydown',ev=>{ev.stopPropagation();if(ev.key==='Enter'){ev.preventDefault();void finish();}if(ev.key==='Escape')void finish(true);});input.addEventListener('blur',()=>void finish());input.addEventListener('click',ev=>ev.stopPropagation());}
 function item(parent,label,fn,enabled=true){const b=document.createElement('button');b.type='button';b.className='menu-item';b.textContent=label;b.disabled=!enabled;b.addEventListener('click',()=>{close();Promise.resolve().then(fn).catch(reportError);});parent.append(b);return b;}
 async function createFrom(button,parentId){if(button.id==='create-script'){const name=prompt('C# script name','NewScript');if(name)await browser.create('script',browser.folder(),name);return;}const args=button.dataset.shape?{dimension:Number(button.dataset.dimension),shape:button.dataset.shape}:button.dataset.example?{example:button.dataset.example}:{name:'Entity'};const type=button.dataset.shape?'scene.primitive.create':button.dataset.example?'scene.example.create':'scene.entity.create';return act(()=>run(type,mutation({...args,...(parentId?{parentId}:{})})));}
 function createMenu(parent,parentId){const details=document.createElement('details');details.innerHTML='<summary>Create</summary><div class="submenu"></div>';parent.append(details);const body=details.querySelector('div');function walk(source,target){for(const child of source.children){if(child.tagName==='DETAILS'){const d=document.createElement('details');d.innerHTML='<summary></summary><div class="submenu"></div>';d.querySelector('summary').textContent=child.querySelector('summary').textContent;target.append(d);walk(child.querySelector('.submenu'),d.querySelector('div'));}else if(child.tagName==='BUTTON')item(target,child.textContent,()=>createFrom(child,parentId),editable()&&!child.disabled);}}walk(q('create-menu .menu-popup')??document.querySelector('#create-menu .menu-popup'),body);}
 async function menu(event){if(event.target.closest?.('#scene-panel,#game-panel,#scene-content,#game-content,#viewport,.viewport,.parallel-viewport')){event.preventDefault();close();return;}if(event.target.closest?.('input,textarea')?.isContentEditable)return;event.preventDefault();clearTimeout(renameTimer);close();const target=event.target,project=target.closest?.('#project-content'),hierarchy=target.closest?.('#entities'),inspector=target.closest?.('.inspector'),pathNode=target.closest?.('[data-project-path]'),row=target.closest?.('[data-entity-id]'),componentNode=target.closest?.('[data-inspector-component]');
  if(project&&pathNode&&!browser.selection().includes(pathNode.dataset.projectPath))browser.select(pathNode.dataset.projectPath);if(hierarchy&&row&&!getSelection().includes(row.dataset.entityId))select(row.dataset.entityId);
  const v=clipboard;context=document.createElement('div');context.className='editor-context menu-popup';context.setAttribute('role','menu');const host=target.ownerDocument??globalThis.document;host.body.append(context);
  if(project){const path=pathNode?.dataset.projectPath,folder=target.closest?.('#project-files')?(pathNode?.dataset.fileKind==='folder'?path:''):browser.folder();item(context,'New Folder',()=>browser.create('folder',folder),editable());item(context,'New C# Script',()=>browser.create('script',folder),editable());item(context,'Show in Explorer',()=>act(()=>run('project.files.reveal',mutation({...(path||folder?{path:path??folder}:{})}))),editable());item(context,'Copy Path',()=>{clipboard=null;return act(async()=>{const data=await run('project.files.reveal',mutation({...(path||folder?{path:path??folder}:{}),open:false}));await navigator.clipboard.writeText(data.path);});},editable());item(context,'Paste',()=>paste('files',folder,v),valid(v,'files'));item(context,'Refresh',()=>act(()=>run('scene.get')),!!getState().project);if(path){if(pathNode.dataset.fileKind==='script'||pathNode.dataset.fileKind==='folder')item(context,'Open',()=>browser.open(path));item(context,'Delete',()=>browser.deleteSelected(),editable());item(context,'Rename',()=>browser.rename(path,pathNode),editable());item(context,'Copy',filesCopy,!!getState().project);}}
  else if(hierarchy){const id=row?.dataset.entityId;createMenu(context,id);item(context,'Paste',()=>paste('entities',id,v),valid(v,'entities'));if(id){item(context,'Rename',()=>renameEntity(id,q('entities').querySelector('[data-entity-id="'+id+'"]')??row),editable());item(context,'Locate',()=>locate(id));item(context,'Delete',()=>act(()=>run('scene.entities.delete',mutation({entityIds:getSelection()}))),editable());item(context,'Copy',entitiesCopy);}}
  else if(inspector&&target.closest('[data-script-path]')){const path=target.closest('[data-script-path]').dataset.scriptPath,c=scriptComponents(getState().project?.scene,entity()).find(c=>c.path===path);item(context,'Open',()=>scriptEditor.open(path));item(context,'Show in Project',()=>scriptEditor.reveal(path));item(context,'Remove',()=>act(()=>run('scene.script.edit',mutation({entityId:entity().id,path,action:'remove'}))),editable());item(context,'Copy',()=>copy({kind:'component',component:'ScriptFile',value:c,projectId:getState().project.id}));item(context,'Paste values',()=>paste('component',null,v),valid(v,'component')&&v.value.path===path);}
  else if(inspector){const component=componentNode?.dataset.inspectorComponent,e=entity();item(context,'Paste',()=>paste('component',null,v),valid(v,'component')&&!e?.[componentKeys[v?.component]]);if(component){if(component!=='Transform')item(context,'Remove',()=>remove(component),editable());item(context,'Paste values',()=>paste('component',null,v),valid(v,'component')&&v.component===component);item(context,'Copy',()=>copy({kind:'component',component,value:component==='Script'?getState().project.scene.script:e?.[componentKeys[component]],projectId:getState().project.id}),!!(component==='Script'?getState().project.scene.script:e?.[componentKeys[component]]));}}
  else item(context,'…',()=>{},false);
  const rect=context.getBoundingClientRect();context.style.left=Math.max(0,Math.min(event.clientX,host.defaultView.innerWidth-rect.width-8))+'px';context.style.top=Math.max(0,Math.min(event.clientY,host.defaultView.innerHeight-rect.height-8))+'px';
 }
 document.addEventListener('contextmenu',event=>void menu(event).catch(reportError));document.addEventListener('pointerdown',event=>{if(event.target.closest?.('.editor-context'))return;lastScope=event.target.closest?.('#project-content')?'files':event.target.closest?.('#entities')?'entities':event.target.closest?.('.inspector')?'component':null;close();});document.addEventListener('copy',()=>{clipboard=null;});document.addEventListener('cut',()=>{clipboard=null;});
 document.addEventListener('keydown',event=>{if(event.key==='Escape'){lastClickedEntity=null;clearTimeout(renameTimer);close();}if(/^(INPUT|TEXTAREA|SELECT)$/.test(event.target.tagName)||event.target.isContentEditable)return;const bodyFocus=['BODY','HTML'].includes(event.target.tagName),project=event.target.closest?.('#project-content')||bodyFocus&&lastScope==='files',hierarchy=event.target.closest?.('#entities')||bodyFocus&&lastScope==='entities',inspector=event.target.closest?.('.inspector')||bodyFocus&&lastScope==='component';if(!project&&!hierarchy&&!inspector)return;if(event.key==='Backspace'&&project){event.preventDefault();event.stopImmediatePropagation();browser.back();}if(event.key==='Delete'&&project){event.preventDefault();event.stopImmediatePropagation();if(editable())void browser.deleteSelected().catch(reportError);}if((event.ctrlKey||event.metaKey)&&['KeyC','KeyV'].includes(event.code)){event.preventDefault();event.stopImmediatePropagation();if(event.code==='KeyC'){if(project)void filesCopy();else if(hierarchy)void entitiesCopy();}else void paste(project?'files':hierarchy?'entities':'component');}},true);
 q('entities').addEventListener('click',event=>{const row=event.target.closest?.('[data-entity-id]');if(!row||!event.target.closest('.entity')||event.ctrlKey||event.shiftKey||event.target.closest('input'))return;const id=row.dataset.entityId;clearTimeout(renameTimer);if(lastClickedEntity===id)renameTimer=setTimeout(()=>{const current=q('entities').querySelector('[data-entity-id="'+id+'"]');if(current)renameEntity(id,current);},650);lastClickedEntity=id;});q('entities').addEventListener('dblclick',event=>{clearTimeout(renameTimer);const row=event.target.closest?.('[data-entity-id]');if(row)locate(row.dataset.entityId);});
 const labels={'camera-component':'Camera','renderable-component':'Renderable','material-component':'Material','light-component':'Light','lod-component':'LOD','physics-component':'Collider','rigidbody-component':'RigidBody','script-component':'Script','entity-form':'Transform','animation-component':'Animator'};
 function decorate(node,title,component,removeButton){if(node.dataset.decorated)return;node.dataset.decorated='true';node.classList.add('inspector-property');node.dataset.inspectorComponent=component;const heading=node.querySelector(':scope > summary,:scope > h2,:scope > h3')??document.createElement('h3');if(!heading.parentNode){heading.textContent=title;node.prepend(heading);}heading.classList.add('property-heading');if(component==='Transform')return;const x=document.createElement('button');x.type='button';x.className='icon-button property-close';x.innerHTML='<img src="/icons/close.svg" alt="">';x.title='Remove '+title;x.setAttribute('aria-label','Remove '+title);x.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(removeButton)removeButton.click();else void remove(component);});heading.append(x);if(removeButton)removeButton.hidden=true;}
 function draw(){if(!getSelection().includes(lastClickedEntity)){lastClickedEntity=null;clearTimeout(renameTimer);}for(const [id,name]of Object.entries(labels)){const node=q(id);if(node){decorate(node,name,name,node.querySelector('button[id$="-remove"]'));for(const b of node.querySelectorAll('button[id$="-remove"]'))b.hidden=true;}}for(const node of q('two-d-components')?.children??[]){const f=node.querySelector('form[data-component]'),key=f?.dataset.component;if(key)decorate(node,key,key[0].toUpperCase()+key.slice(1),[...node.querySelectorAll('button')].find(b=>b.textContent.startsWith('Remove ')));}for(const node of q('audio-component')?.querySelectorAll(':scope > section')??[]){const title=node.querySelector('h3')?.textContent;if(['AudioSource','AudioListener'].includes(title))decorate(node,title,title,[...node.querySelectorAll('button')].find(b=>b.textContent.startsWith('Remove ')));}
  for(const form of document.querySelectorAll('.inspector form')){if(form.dataset.autoCommit)continue;form.dataset.autoCommit='true';for(const b of form.querySelectorAll('button[type="submit"]'))b.hidden=true;form.addEventListener('change',event=>{if(event.target.matches('input,select,textarea')&&form.checkValidity())form.requestSubmit();});}
  for(const b of document.querySelectorAll('.inspector button'))if(/^(Apply(?: |$)|Remove (?:Animator|AudioSource|AudioListener|Camera|Light|LOD|Material|Collider|RigidBody|Sprite2D|SpriteAnimation|Tilemap|Light2D|Particles2D|UI2D)$|Detach script$)/.test(b.textContent))b.hidden=true;
  for(const x of document.querySelectorAll('.property-close'))x.disabled=!editable();
 }
 q('create-script')?.addEventListener('click',()=>{const name=prompt('C# script name','NewScript');if(name)void browser.create('script',browser.folder(),name).catch(reportError);});
 return {draw};
}
