export function mountInspectorUX({document,getSelection}) {
 if(!document.defaultView)return {draw(){}};
 const collapsed=new Set();let drag=null;
 function draw(){for(const title of document.querySelectorAll('.inspector p')){const values=title.nextElementSibling;if(values?.classList.contains('vector-inputs')&&title.textContent.length<40){const row=document.createElement('div');row.className='inspector-vector-row';title.before(row);row.append(title,values);}}for(const label of document.querySelectorAll('.inspector label[for]')){const input=label.ownerDocument.getElementById(label.htmlFor);if(input&&input.previousElementSibling===label&&!label.parentElement.classList.contains('inspector-row')){const row=document.createElement('div');row.className='inspector-row';label.before(row);row.append(label,input);}}for(const card of document.querySelectorAll('.inspector .inspector-property')){
  const heading=card.querySelector(':scope > .property-heading,:scope > h3,:scope > h2,:scope > summary');if(!heading)continue;heading.classList.add('property-heading');
  const key=getSelection()+':'+(card.dataset.scriptPath??card.dataset.inspectorComponent??card.id??heading.textContent);card.dataset.foldKey=key;
  if(!heading.querySelector('.component-fold')){const button=document.createElement('button');button.type='button';button.className='icon-button component-fold';button.innerHTML='<img src="/icons/open-tabs.svg" alt="">';button.title='Expand or collapse component';button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();if(collapsed.has(card.dataset.foldKey))collapsed.delete(card.dataset.foldKey);else collapsed.add(card.dataset.foldKey);paint(card);});heading.prepend(button);}
  paint(card);
 }
 for(const label of document.querySelectorAll('.inspector label')){if(!label.querySelector('input,select,textarea'))continue;label.classList.add('inspector-row');if(!label.querySelector(':scope > .field-label')){const texts=[...label.childNodes].filter(n=>n.nodeType===3&&n.textContent.trim());if(texts.length){const span=document.createElement('span');span.className='field-label';for(const text of texts)span.append(text);label.prepend(span);}}
  const input=label.querySelector(':scope > input[type="number"]'),name=label.querySelector(':scope > .field-label,:scope > span');if(input&&name){name.classList.add('numeric-label');name.dataset.scrub='true';}
 }
 }
 function paint(card){const folded=collapsed.has(card.dataset.foldKey);card.classList.toggle('component-collapsed',folded);const button=card.querySelector('.component-fold');button?.setAttribute('aria-expanded',String(!folded));if(card.tagName==='DETAILS')card.open=!folded;}
 document.addEventListener('pointerdown',event=>{const name=event.target.closest?.('[data-scrub]');if(!name||event.button!==0)return;const label=name.closest('label'),input=label?.querySelector('input[type="number"]');if(!input||input.disabled||input.readOnly)return;event.preventDefault();input.focus({preventScroll:true});const step=input.step==='any'||!input.step?0.1:Number(input.step);drag={name,input,x:event.clientX,start:Number(input.value)||0,step:Number.isFinite(step)&&step>0?step:.1,at:0};name.setPointerCapture?.(event.pointerId);});
 document.addEventListener('pointermove',event=>{if(!drag)return;const {input,start,x,step}=drag;let value=start+(event.clientX-x)*step*(event.shiftKey ? .1 : 1);if(input.step!=='any'&&Number(input.step)>=1)value=Math.round(value);value=Math.min(input.max?Number(input.max):1000000,Math.max(input.min?Number(input.min):-1000000,value));input.value=String(Number(value.toFixed(5)));if(performance.now()-drag.at>60){drag.at=performance.now();input.dispatchEvent(new Event('change',{bubbles:true}));}});
 const finish=async()=>{if(!drag)return;const input=drag.input,value=input.value;drag=null;let attempts=0;while(document.querySelector('#editor-workspace')?.getAttribute('aria-busy')==='true'&&attempts++<500)await new Promise(r=>setTimeout(r,20));if(input.isConnected){input.value=value;input.dispatchEvent(new Event('change',{bubbles:true}));}};document.addEventListener('pointerup',finish);document.addEventListener('pointercancel',finish);
 return {draw};
}
