import {activeGameCamera,legacyDirectionalUniforms} from '../../../engine/scene/camera.mjs';
import {cameraMatrix,matrixMultiply} from './view-math.mjs';
import {renderPlan} from '../../../engine/renderer/render-plan.mjs';
import {twoDPlan} from '../../../engine/renderer/two-d-plan.mjs';
import {createProductionGPU} from '../../../engine/renderer/production-gpu.mjs';
import {createTwoDGPU} from '../../../engine/renderer/two-d-gpu.mjs';
// A render target only: no kernel, physics, script worker, audio or RAF ownership.
export function parallelView({device,gpu,pipeline,textureFor,getTexture,reportError,onPointer=()=>{}}) {
 let target=null,context=null,depth=null,production=null,twoD=null,ready=false,epoch=0,lastPlan=null,baseWidth=960,baseHeight=540;const baseSizes=new WeakMap();const pointer=e=>onPointer(e,target,lastPlan);
 const timing={writes:()=>undefined,resolve(){},submitted(){}};
 function clear(){target?.canvas.removeEventListener?.('pointerdown',pointer,{capture:true});lastPlan=null;epoch++;ready=false;depth?.destroy();production?.dispose();twoD?.dispose();depth=production=twoD=null;context?.unconfigure?.();context=null;}
 async function prepare(scene,assets,draws){const ticket=++epoch;ready=false;if(!target)return;const scale=scene.rendering?.renderScale??1,width=Math.round(baseWidth*scale),height=Math.round(baseHeight*scale);if(target.canvas.width!==width||target.canvas.height!==height){target.canvas.width=width;target.canvas.height=height;production?.dispose();twoD?.dispose();production=twoD=null;depth?.destroy();depth=device?device.createTexture({size:[width,height],format:'depth24plus',usage:GPUTextureUsage.RENDER_ATTACHMENT}):null;}if(!device){ready=true;return;}
  try{if(scene.twoD){twoD??=await createTwoDGPU({device,format:gpu.getPreferredCanvasFormat()+'-srgb',width:target.canvas.width,height:target.canvas.height,textureFor});await twoD.prepare([...assets.values()].filter(a=>a.kind==='sprite').map(a=>a.dataUrl));}else if(scene.rendering){production??=await createProductionGPU({device,format:gpu.getPreferredCanvasFormat(),width:target.canvas.width,height:target.canvas.height,textureFor,getTexture,reportError});production.reset();await production.prepare([...draws,...[...assets.values()].flatMap(a=>a.primitives??[])]);}if(ticket===epoch)ready=true;}catch(e){if(ticket===epoch)reportError(e);}
 }
 return {set(value,scene,assets,draws){if(target?.canvas===value?.canvas&&target?.view===value?.view)return;clear();target=value;if(!value)return;if(!baseSizes.has(value.canvas))baseSizes.set(value.canvas,[value.canvas.width,value.canvas.height]);[baseWidth,baseHeight]=baseSizes.get(value.canvas);value.canvas.addEventListener?.('pointerdown',pointer,{capture:true});if(device){context=value.canvas.getContext('webgpu');context.configure({device,format:gpu.getPreferredCanvasFormat(),viewFormats:[gpu.getPreferredCanvasFormat()+'-srgb'],alphaMode:'opaque'});depth=device.createTexture({size:[value.canvas.width,value.canvas.height],format:'depth24plus',usage:GPUTextureUsage.RENDER_ATTACHMENT});}void prepare(scene,assets,draws);},prepare,
 render({scene,assets,draws,resources,editorCamera,time,kernel,paused,frame,generation}){if(!target||!ready)return;const {canvas,view}=target,gameCamera=activeGameCamera(scene),missingCamera=view==='game'&&!gameCamera,camera=view==='scene'&&editorCamera?editorCamera:gameCamera??{position:[0,0,6],target:[0,0,0],projection:'perspective',fov:60,orthoHeight:6};const vp=cameraMatrix(camera,canvas.width/canvas.height),geometry=(missingCamera?[]:draws).map(d=>({...d,mvp:matrixMultiply(vp,d.model)}));
  const renderScene=missingCamera?{...scene,entities:[]}:scene,directional=legacyDirectionalUniforms(renderScene);
  if(device){if(scene.twoD){const plan=twoDPlan(renderScene,assets,camera,canvas.width,canvas.height,{view,time,kernel,paused});lastPlan=plan;twoD.render(plan,context.getCurrentTexture().createView({format:gpu.getPreferredCanvasFormat()+'-srgb'}),timing);}else if(scene.rendering){const plan=renderPlan(renderScene,geometry,camera,canvas.width/canvas.height,assets,{gpuCulling:device.limits.maxStorageBuffersPerShaderStage>=4});production.render(plan,camera,context.getCurrentTexture().createView(),'parallel',timing);}else{const encoder=device.createCommandEncoder(),pass=encoder.beginRenderPass({colorAttachments:[{view:context.getCurrentTexture().createView(),clearValue:{r:.025,g:.035,b:.055,a:1},loadOp:'clear',storeOp:'store'}],depthStencilAttachment:{view:depth.createView(),depthClearValue:1,depthLoadOp:'clear',depthStoreOp:'store'}});pass.setPipeline(pipeline);for(let i=0;i<geometry.length;i++){const item=resources[i],u=new Float32Array(104);u.set(geometry[i].mvp,0);u.set(geometry[i].model,16);u.set(item.color,32);u[36]=item.unlit?1:0;u[37]=directional.count;u.set(directional.data,40);device.queue.writeBuffer(item.uniform,0,u);pass.setBindGroup(0,item.bind);pass.setVertexBuffer(0,item.vertex);pass.draw(item.count);}pass.end();device.queue.submit([encoder.finish()]);}}
  canvas.dataset.activeCamera=gameCamera?.entityId??(missingCamera?'none':'legacy');canvas.dataset.frame=String(frame);canvas.dataset.generation=String(generation);canvas.dataset.camera=JSON.stringify(camera);canvas.dataset.renderer=device?'webgpu':'null';
 },get:()=>target,dispose:clear};
}
