// Human controls read the same bounded records as the public semantic tools.
export function mountProfilerEditor({document,getRenderer,getSnapshot,reportError}){
 const q=id=>document.querySelector('#profiler-'+id),panel=document.querySelector('#profiler-content');let disposed=false,selected=null,timer;
 const args=extra=>{const s=getSnapshot();return {id:s?.project?.id,expectedSceneRevision:s?.sceneRevision,workspaceId:s?.workspaceId??undefined,...extra};};
 const number=v=>v===null?'Unavailable':v.toFixed(2)+' ms';
 function explain(){try{const value=getRenderer()?.profilerQuery(args({action:'explain',frameSequence:Number(q('frame').value),metric:q('metric').value}));q('detail').textContent=JSON.stringify(value,null,2);q('verdict').textContent=value?.status==='explained'?`${value.spike?'Measured spike':'No measured spike'} · ${value.metric} · baseline ${number(value.baseline.medianMs)} · increase ${number(value.deltaMs)}`:value?.message??'Evidence unavailable';q('contributors').replaceChildren();for(const c of value?.contributors??[]){const row=document.createElement('li');row.textContent=`${c.name} · ${number(c.milliseconds)} · +${number(c.deltaMs)} over baseline${c.overlap?' · overlaps roundtrip':''}`;q('contributors').append(row);}}catch(error){reportError(error);}}
 function refresh(){if(disposed||panel.hidden||!getSnapshot()?.project)return;try{const h=getRenderer()?.profilerQuery(args({limit:20}));if(!h)return;q('summary').textContent=`${h.retained}/${h.capacity} retained · ${h.dropped} evicted · ${h.gpuSamples} timestamp samples · ${h.paused?'Collection paused':'Collecting'} · generation ${h.generation}`;q('rows').replaceChildren();const max=Math.max(1,...h.items.map(i=>i.elapsedMs));for(const f of h.items){const row=document.createElement('tr');row.dataset.frame=String(f.frameSequence);row.className=f.frameSequence===selected?'selected':'';const choose=document.createElement('button');choose.textContent=String(f.frameSequence);choose.setAttribute('aria-label','Select frame '+f.frameSequence);choose.addEventListener('click',()=>{selected=f.frameSequence;q('frame').value=String(selected);explain();refresh();});const first=document.createElement('td');first.append(choose);row.append(first);for(const text of [number(f.elapsedMs),number(f.measuredMainMs),number(f.gpuTimeMs),f.gpuStatus==='observed'?f.gpuScopes.map(s=>s.name).join(', '):f.gpuReason,`${f.view} / ${f.playing?'Play':'Stopped'} / ${f.route}`]){const td=document.createElement('td');td.textContent=text;row.append(td);}const bar=document.createElement('td'),fill=document.createElement('span');fill.className='profiler-bar';fill.style.width=(100*f.elapsedMs/max)+'%';bar.append(fill);row.append(bar);q('rows').append(row);}if(selected===null&&h.items.length)q('frame').value=String(h.items.at(-1).frameSequence);}catch(error){q('summary').textContent=error.message;}}
 q('refresh').addEventListener('click',refresh);q('explain').addEventListener('click',explain);q('pause').addEventListener('change',e=>{getRenderer()?.setProfilerPaused(e.target.checked);refresh();});q('clear').addEventListener('click',()=>{getRenderer()?.clearProfiler();selected=null;q('detail').textContent='History cleared; the game continues.';q('verdict').textContent='History cleared; collect eight comparable frames for a new baseline.';q('contributors').replaceChildren();refresh();});
 function tick(){refresh();if(!disposed){timer=setTimeout(tick,500);timer.unref?.();}}tick();return ()=>{disposed=true;clearTimeout(timer);};
}
