import {FrameProfiler} from './frame-profiler.mjs';
// Historical captures use their original lease and never enter live semantic queries.
export function mountProfilerEditor({document,getRenderer,getSnapshot,reportError}){
 const q=id=>document.querySelector('#profiler-'+id),panel=q('content');let disposed=false,selected=null,timer,analysisCount=0;
 const storage=globalThis.localStorage,key='axiom.profiler-captures.v1';let captures=[],seen=new Set(),captureId='live',reader=null;
 try{const saved=JSON.parse(storage?.getItem(key)??'[]');if(!Array.isArray(saved)||saved.length>8)throw Error('Invalid stored captures');for(const c of saved)FrameProfiler.fromCapture(c);captures=saved;seen=new Set(saved.map(c=>c.id));}catch{captures=[];}
 const args=extra=>{const s=getSnapshot();return {id:s?.project?.id,expectedSceneRevision:s?.sceneRevision,workspaceId:s?.workspaceId??undefined,...extra};};
 const number=v=>v===null?'Unavailable':v.toFixed(2)+' ms';
 function persist(){try{storage?.setItem(key,JSON.stringify(captures));}catch{q('summary').textContent='Capture kept in memory; browser storage unavailable. Export JSON to retain it.';}}
 function remember(c){FrameProfiler.fromCapture(c);if(seen.has(c.id))return;seen.add(c.id);if(seen.size>256)seen.delete(seen.values().next().value);captures.push(c);if(captures.length>8)captures.shift();persist();}
 function sessions(){for(const c of getRenderer()?.profilerCaptures?.()??[])remember(c);const value=captureId;q('session').replaceChildren();for(const c of [{id:'live'},...captures]){const o=document.createElement('option');o.value=c.id;o.textContent=c.id==='live'?'Live session':`${c.createdAt} · revision ${c.lease.sceneRevision} · generation ${c.lease.generation} · ${c.records.length} frames`;q('session').append(o);}q('session').value=value;if(!q('session').value)choose('live');}
 function choose(id){captureId=id;reader=id==='live'?null:FrameProfiler.fromCapture(captures.find(c=>c.id===id));selected=null;q('session').value=id;q('detail').textContent='Select a frame in this capture.';q('verdict').textContent=id==='live'?'Live session · select a frame.':'Saved capture · immutable measurements from the original session.';q('contributors').replaceChildren();q('pause').disabled=!!reader;refresh();}
 function history(){return reader?reader.history({limit:20}):getRenderer()?.profilerQuery(args({limit:20}));}
 function explain(){try{const query={frameSequence:Number(q('frame').value),metric:q('metric').value},value=reader?reader.explainFrameSpike(query):getRenderer()?.profilerQuery(args({action:'explain',...query}));if(!value)throw Error('Renderer not ready');q('detail').textContent=JSON.stringify(value,null,2);q('verdict').textContent=`Analysis ${++analysisCount} · frame ${query.frameSequence}\n`+(value.status==='explained'?`${value.spike?'Measured spike':'No measured spike'} · ${value.metric} · baseline ${number(value.baseline.medianMs)} · increase ${number(value.deltaMs)}`:value.message??'Evidence unavailable');q('verdict').classList.remove('profiler-feedback');void q('verdict').offsetWidth;q('verdict').classList.add('profiler-feedback');q('verdict').scrollIntoView?.({block:'nearest'});q('contributors').replaceChildren();for(const c of value.contributors??[]){const row=document.createElement('li');row.textContent=`${c.name} · ${number(c.milliseconds)} · +${number(c.deltaMs)} over baseline${c.overlap?' · overlaps roundtrip':''}`;q('contributors').append(row);}}catch(error){q('verdict').textContent='Analysis failed: '+error.message;reportError(error);}}
 function refresh(){if(disposed||!getSnapshot()?.project)return;try{sessionsWithoutRefresh();if(panel.hidden)return;const h=history();if(!h)return;q('summary').textContent=`${reader?'Saved capture':'Live'} · ${h.retained}/${h.capacity} retained · ${h.dropped} evicted · ${h.gpuSamples} timestamp samples · ${h.paused?'Collection paused':'Collecting'} · generation ${h.generation}`;q('rows').replaceChildren();const max=Math.max(1,...h.items.map(i=>i.elapsedMs));for(const f of h.items){const row=document.createElement('tr');row.dataset.frame=String(f.frameSequence);row.className=f.frameSequence===selected?'selected':'';const chooseFrame=document.createElement('button');chooseFrame.textContent=String(f.frameSequence);chooseFrame.setAttribute('aria-label','Select frame '+f.frameSequence);chooseFrame.addEventListener('click',()=>{selected=f.frameSequence;q('frame').value=String(selected);explain();refresh();});const first=document.createElement('td');first.append(chooseFrame);row.append(first);for(const text of [number(f.elapsedMs),number(f.measuredMainMs),number(f.gpuTimeMs),f.gpuStatus==='observed'?f.gpuScopes.map(s=>s.name).join(', '):f.gpuReason,`${f.view} / ${f.playing?'Play':'Stopped'} / ${f.route}`]){const td=document.createElement('td');td.textContent=text;row.append(td);}const bar=document.createElement('td'),fill=document.createElement('span');fill.className='profiler-bar';fill.style.width=(100*f.elapsedMs/max)+'%';bar.append(fill);row.append(bar);q('rows').append(row);}if(selected===null&&h.items.length)q('frame').value=String(h.items.at(-1).frameSequence);}catch(error){q('summary').textContent=error.message;}}
 // Avoid rebuilding the selector every polling tick or losing the user's selection.
 function sessionsWithoutRefresh(){const before=captures.length,ids=captures.map(c=>c.id).join();for(const c of getRenderer()?.profilerCaptures?.()??[])remember(c);if(before!==captures.length||ids!==captures.map(c=>c.id).join()||!q('session').options?.length)sessions();}
 q('session').addEventListener('change',e=>choose(e.target.value));
 q('save').addEventListener('click',()=>{const c=getRenderer()?.captureProfiler?.();if(!c?.records.length){q('verdict').textContent='No measured frames to save.';return;}remember(c);sessions();choose(c.id);});
 q('export').addEventListener('click',()=>{const c=reader?captures.find(c=>c.id===captureId):getRenderer()?.captureProfiler?.();if(!c)return;const url=URL.createObjectURL(new Blob([JSON.stringify(c,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='axiom-profiler-'+c.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 q('import').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>1000000)throw Error('Capture exceeds 1 MB');const c=JSON.parse(await file.text());remember(c);sessions();choose(c.id);}catch(error){reportError(error);q('verdict').textContent='Import failed: '+error.message;}finally{e.target.value='';}});
 q('delete').addEventListener('click',()=>{if(captureId==='live'){q('verdict').textContent='Choose a saved capture to delete.';return;}captures=captures.filter(c=>c.id!==captureId);persist();captureId='live';sessions();choose('live');});
 q('frame').addEventListener('input',e=>{const value=Number(e.target.value);selected=Number.isSafeInteger(value)&&value>0?value:null;});
 q('refresh').addEventListener('click',refresh);q('explain').addEventListener('click',explain);q('pause').addEventListener('change',e=>{getRenderer()?.setProfilerPaused(e.target.checked);refresh();});q('clear').addEventListener('click',()=>{if(reader){q('verdict').textContent='Saved captures are immutable. Use Delete capture or choose Live session.';return;}getRenderer()?.clearProfiler();selected=null;q('detail').textContent='History cleared; the game continues.';q('verdict').textContent='History cleared; collect eight comparable frames for a new baseline.';q('contributors').replaceChildren();refresh();});
 sessions();function tick(){refresh();if(!disposed){timer=setTimeout(tick,500);timer.unref?.();}}tick();return ()=>{disposed=true;clearTimeout(timer);};
}
