import {projectFiles,parentPath,leafName,projectPath,editProjectFiles} from '../../../engine/scene/project-files.mjs';
export function mountProjectBrowser({document,getState,mutate,selectAsset,selectScript,reportError,onSelection=()=>{},beforeEdit=async()=>{},onFilesChanged=()=>{}}){
 if(!document.defaultView)return {draw(){},files:()=>[],selection:()=>[],folder:()=>'',clear(){},back(){},deleteSelected(){},open(){},refresh(){}};
 const q=id=>document.querySelector('#'+id),tree=q('project-files'),icons=q('project-icons');
 let projectId=null,folder='',selected=new Set(),collapsed=new Set(),signature='',renameTimer=null,anchor=null;
 const files=()=>projectFiles(getState().project?.scene??{});
 const icon=(node,f)=>{const image=document.createElement('img');image.src=f.kind==='folder'?'/icons/folder.svg':f.kind==='script'?'/icons/csharp.svg':f.kind==='json'?'/icons/json.svg':'/icons/asset.svg';image.alt='';image.className='project-icon';node.append(image);};
 function choose(path,event={}){clearTimeout(renameTimer);if(event.shiftKey&&anchor){const visible=files().filter(f=>parentPath(f.path)===folder).map(f=>f.path),a=visible.indexOf(anchor),b=visible.indexOf(path);selected=new Set(a>=0?visible.slice(Math.min(a,b),Math.max(a,b)+1):[path]);}else if(event.ctrlKey||event.metaKey){if(selected.has(path))selected.delete(path);else selected.add(path);}else selected=new Set([path]);anchor=path;paintSelection();onSelection([...selected]);}
 function paintSelection(){for(const node of [...tree.querySelectorAll('[data-project-path]'),...icons.querySelectorAll('[data-project-path]')]){node.classList.toggle('selected',selected.has(node.dataset.projectPath));node.setAttribute('aria-selected',String(selected.has(node.dataset.projectPath)));}}
 async function edit(data){await beforeEdit();editProjectFiles(structuredClone(getState().project.scene),data);const previous=[...selected];const ok=await mutate(data);if(ok!==true)throw Error(q('project-error')?.textContent||'File operation failed');if(data.action==='move')selected=new Set(previous.map(p=>p===data.path||p.startsWith(data.path+'/')?data.to+p.slice(data.path.length):p));signature='';draw();onFilesChanged(data);onSelection([...selected]);return ok;}
 function inline(node,value,commit){clearTimeout(renameTimer);if(node.querySelector('input'))return;const label=node.querySelector('.file-name')??node,old=label.textContent;label.textContent='';const input=document.createElement('input');input.className='inline-name';input.value=value;input.maxLength=128;label.append(input);input.focus();input.select();let done=false,pending=false;
  const finish=async(cancel=false)=>{if(done||pending)return;if(cancel){done=true;label.textContent=old;if(node.classList.contains('pending-file'))node.remove();return;}const name=input.value.trim();pending=true;try{if(!name)throw Error('Enter a name');await commit(name);done=true;label.textContent=name;node.querySelector('.file-error')?.remove();}catch(e){input.setAttribute('aria-invalid','true');let error=node.querySelector('.file-error');if(!error){error=document.createElement('span');error.className='file-error';error.setAttribute('role','alert');node.append(error);}error.textContent=e.message;reportError(e);input.focus();input.select();}finally{pending=false;}};
  input.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Enter'){e.preventDefault();void finish();}if(e.key==='Escape'){e.preventDefault();void finish(true);}});input.addEventListener('blur',()=>void finish());input.addEventListener('input',()=>input.removeAttribute('aria-invalid'));input.addEventListener('click',e=>e.stopPropagation());
 }
 function rename(path,node){const f=files().find(f=>f.path===path);if(!f||['Assets','Scripts','Scenes'].includes(path))return;inline(node,leafName(path),name=>edit({action:'move',path,to:(parentPath(path)?parentPath(path)+'/':'')+name+(f.kind==='script'&&!name.endsWith('.cs')?'.cs':'')}));}
 function drag(node,f){node.draggable=true;node.addEventListener('dragstart',e=>{clearTimeout(renameTimer);if(!selected.has(f.path))choose(f.path);e.dataTransfer.setData('application/axiom-files',JSON.stringify({projectId:getState().project.id,paths:[...selected]}));});if(f.kind==='folder')drop(node,f.path);}
 function drop(node,target){node.addEventListener('dragover',e=>{if(!e.dataTransfer.types.includes('application/axiom-files'))return;e.preventDefault();e.stopPropagation();for(const n of document.querySelectorAll('#project-content .drag-target'))n.classList.remove('drag-target');node.classList.add('drag-target');});node.addEventListener('dragleave',e=>{if(!node.contains(e.relatedTarget))node.classList.remove('drag-target');});node.addEventListener('drop',e=>{if(!e.dataTransfer.types.includes('application/axiom-files'))return;e.preventDefault();e.stopPropagation();node.classList.remove('drag-target');try{const v=JSON.parse(e.dataTransfer.getData('application/axiom-files'));if(v.projectId!==getState().project.id)throw Error('Move files inside the current project');void (async()=>{const destination=typeof target==='function'?target():target,moves=v.paths.filter(p=>!v.paths.some(other=>other!==p&&p.startsWith(other+'/'))).map(path=>({action:'move',path,to:(destination?destination+'/':'')+leafName(path)})).filter(data=>data.path!==data.to);const draft=structuredClone(getState().project.scene);for(const data of moves)draft.projectFiles=editProjectFiles(draft,data);for(const data of moves)await edit(data);})().catch(reportError);}catch(error){reportError(error);}});}
 drop(icons,()=>folder); // Background destination is read dynamically below.
 // A background drop must use the currently open directory, not Project root.
 icons.addEventListener('dragover',e=>{if(e.target===icons&&e.dataTransfer.types.includes('application/axiom-files'))e.preventDefault();});
 function draw(){const state=getState();if(state.project?.id!==projectId){projectId=state.project?.id;folder='';selected.clear();collapsed.clear();signature='';}const items=files(),key=JSON.stringify([state.project?.id,state.sceneRevision,folder,[...collapsed]]);if(key===signature)return;signature=key;if(folder&&!items.some(f=>f.path===folder&&f.kind==='folder'))folder='';selected=new Set([...selected].filter(p=>items.some(f=>f.path===p)));tree.replaceChildren();icons.replaceChildren();q('project-breadcrumb').textContent='Project'+(folder?' / '+folder:'');q('project-back').disabled=!folder;
  const root=document.createElement('button');root.className='project-tree-row';root.dataset.projectRoot='true';root.textContent='Project';root.addEventListener('click',()=>{clear();folder='';signature='';draw();});drop(root,'');tree.append(root);
  const children=new Map();for(const f of items.filter(f=>f.kind==='folder')){const parent=parentPath(f.path);if(!children.has(parent))children.set(parent,[]);children.get(parent).push(f);}
  function branch(parent,depth){for(const f of children.get(parent)??[]){const row=document.createElement('div');row.className='project-tree-row';row.dataset.projectPath=f.path;row.dataset.fileKind=f.kind;row.style.paddingLeft=depth*12+'px';row.setAttribute('role','treeitem');const toggle=document.createElement('button');toggle.className='tree-toggle';toggle.textContent=collapsed.has(f.path)?'▸':'▾';toggle.addEventListener('click',()=>{if(collapsed.has(f.path))collapsed.delete(f.path);else collapsed.add(f.path);signature='';draw();});row.append(toggle);icon(row,f);const label=document.createElement('button');label.className='file-name';label.textContent=leafName(f.path);row.append(label);row.addEventListener('click',e=>{if(e.target===toggle||e.target.closest?.('input'))return;const already=selected.size===1&&selected.has(f.path);choose(f.path,e);folder=f.path;signature='';draw();if(already&&e.target.closest('.file-name')&&!e.ctrlKey&&!e.shiftKey){clearTimeout(renameTimer);renameTimer=setTimeout(()=>{const current=tree.querySelector('[data-project-path="'+CSS.escape(f.path)+'"]');if(current)rename(f.path,current);},650);}});drag(row,f);tree.append(row);if(!collapsed.has(f.path))branch(f.path,depth+1);}}
  branch('',1);
  for(const f of items.filter(f=>parentPath(f.path)===folder)){const button=document.createElement('button');button.className='project-file';button.dataset.projectPath=f.path;button.dataset.fileKind=f.kind;button.title=f.path;button.setAttribute('role','listitem');icon(button,f);const label=document.createElement('span');label.className='file-name';label.textContent=leafName(f.path);button.append(label);button.addEventListener('click',e=>{if(e.target.closest?.('input'))return;const already=selected.size===1&&selected.has(f.path);choose(f.path,e);if(already&&e.target.closest('.file-name')&&!e.ctrlKey&&!e.shiftKey)renameTimer=setTimeout(()=>rename(f.path,button),650);if(f.kind==='asset')selectAsset(f.assetId);else if(f.text!==undefined){if(f.kind==='script'){q('project-file-preview').hidden=true;}else{q('project-file-preview').textContent=f.text;q('project-file-preview').hidden=false;}}});button.addEventListener('dblclick',()=>{clearTimeout(renameTimer);if(f.kind==='folder'){folder=f.path;signature='';q('project-file-preview').hidden=true;draw();}else if(f.kind==='script')selectScript?.(f);});drag(button,f);icons.append(button);}
  paintSelection();
 }
 async function create(kind,target=folder,name){if(!getState().project)return;if(!name&&folder!==target){folder=target;signature='';draw();}
  const ext=kind==='script'?'.cs':'',base=name??(kind==='folder'?'NewFolder':'NewScript'),prefix=target?target+'/':'';if(name){projectPath(prefix+base+(ext&&!base.endsWith(ext)?ext:''));return edit({action:'create',kind,path:prefix+base+(ext&&!base.endsWith(ext)?ext:'')});}
  const pending=document.createElement('button');pending.className='project-file pending-file';icon(pending,{kind});const label=document.createElement('span');label.className='file-name';pending.append(label);icons.prepend(pending);inline(pending,base,async value=>{await edit({action:'create',kind,path:prefix+value+(ext&&!value.endsWith(ext)?ext:'')});pending.remove();});
 }
 function clear(notify=true){clearTimeout(renameTimer);selected.clear();anchor=null;paintSelection();q('project-file-preview').hidden=true;if(notify)onSelection([]);}
 function back(){if(!folder)return;clear();folder=parentPath(folder);signature='';draw();}
 async function deleteSelected(){const paths=[...selected],entries=files();if(!paths.length)return;const empty=paths.every(path=>entries.find(f=>f.path===path)?.kind==='folder'&&!entries.some(f=>f.path.startsWith(path+'/')));if(empty||confirm('Delete selected files and folders from this project?'))await edit({action:'delete',paths});}
 function open(path){const f=files().find(f=>f.path===path);if(f?.kind==='script')selectScript?.(f);else if(f?.kind==='folder'){folder=path;signature='';draw();}}
 q('project-back').addEventListener('click',back);
 for(const view of [tree,icons])view.addEventListener('click',e=>{if(!e.target.closest('[data-project-path],button,input'))clear();});
 return {draw,clear,back,deleteSelected,open,reveal:path=>{folder=parentPath(path);signature='';draw();choose(path);},folder:()=>folder,selection:()=>[...selected],select:choose,rename,create,edit,files,refresh:()=>{signature='';draw();}};
}
