export function mountReplayEditor({document,getRenderer,getSnapshot,reportError}){
 if(!document.defaultView)return ()=>{};
 const menu=document.createElement('details');menu.id='replay-menu';menu.innerHTML='<summary>Replay / Diagnostic Replay</summary><div class="submenu game-test-editor"><label>Input plan · JSON<textarea id="replay-source" rows="10" maxlength="16000"></textarea></label><label>Random seed<input id="replay-seed" type="number" min="0" max="4294967295" value="42"></label><div class="actions"><button id="replay-record">Record plan</button><button id="replay-cancel">Cancel</button><button id="replay-clear">Clear recording</button><button id="replay-export">Export recording</button><label>Import recording<input id="replay-import" type="file" accept=".json"></label></div><div class="actions"><label>From frame<input id="replay-from" type="number" min="0" max="599" value="0"></label><label>To frame<input id="replay-to" type="number" min="1" max="600" value="120"></label><button id="replay-run">Replay range</button></div><label>Diagnostic question<select id="replay-diagnostic"><option value="">Frame contacts / animation</option><option>whyNotRendered</option><option>whyNotColliding</option><option>whyAssetNotLoaded</option><option>whyScriptNotRunning</option></select></label><label>Entity<select id="replay-entity"></select></label><label>Other collision entity<select id="replay-other"></select></label><p>Record controlled inputs at 1/60s, up to 600 frames / 64 entities. Checkpoints every 60 frames. Restoration reconstructs the input prefix and verifies checkpoints, including private C# state. Use ReplayRandom for seeded C# randomness. GPU/audio/wall clocks are not replay guarantees.</p><p id="replay-status" role="status"></p><pre id="replay-result"></pre></div>';document.querySelector('#settings-menu .menu-popup').prepend(menu);
 const q=id=>document.querySelector('#replay-'+id);let project=null;
 function args(action){const s=getSnapshot();if(!s?.project)throw Error('Open a project first');return {action,id:s.project.id,expectedSceneRevision:s.sceneRevision,...(s.workspaceId?{workspaceId:s.workspaceId}:{})};}
 function act(action,extra={}){try{const result=getRenderer().replayControl({...args(action),...extra});refresh();return result;}catch(e){q('status').textContent=e.message;reportError(e);return null;}}
 q('record').addEventListener('click',()=>{try{act('record',{suite:JSON.parse(q('source').value),seed:Number(q('seed').value)});}catch(e){reportError(e);}});
 q('run').addEventListener('click',()=>act('replay',{from:Number(q('from').value),to:Number(q('to').value),...(q('diagnostic').value?{diagnostic:{kind:q('diagnostic').value,entityId:q('entity').value,...(q('diagnostic').value==='whyNotColliding'?{otherId:q('other').value}:{})}}:{})}));
 for(const a of ['cancel','clear'])q(a).addEventListener('click',()=>act(a));
 q('export').addEventListener('click',()=>{const r=act('export');if(!r)return;const url=URL.createObjectURL(new Blob([JSON.stringify(r.recording)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='axiom-replay.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 q('import').addEventListener('change',async e=>{try{const file=e.target.files[0];if(file){if(file.size>240000)throw Error('Recording exceeds 240 KiB');act('import',{recordingJson:await file.text()});}}catch(error){reportError(error);}finally{e.target.value='';}});
 function refresh(){const s=getSnapshot();if(s?.project?.id!==project){project=s?.project?.id??null;for(const id of ['entity','other']){q(id).replaceChildren();for(const e of s?.project?.scene.entities??[]){const o=document.createElement('option');o.value=e.id;o.textContent=e.name;q(id).append(o);}if(id==='other'&&q(id).options.length>1)q(id).selectedIndex=1;}q('source').value=JSON.stringify(s?.project?.editor?.gameTests?.[0]??{name:'Replay inputs',steps:[{frames:120,keys:[]}]},null,2);}const r=getRenderer()?.replayStatus()??{status:'idle'};q('status').textContent=`${r.kind??'Replay'} · ${r.status} · ${r.frames??0} frames · ${r.verifiedCheckpoints??0} verified checkpoints`;q('result').textContent=JSON.stringify(r,null,2);const active=r.status==='running';for(const a of ['record','run','clear','import'])q(a).disabled=active||!project||s.playing;q('cancel').disabled=!active;q('export').disabled=active||!r.recording;}
 refresh();const timer=setInterval(refresh,250);return ()=>clearInterval(timer);
}
