import {projectFiles,leafName} from '../../../engine/scene/project-files.mjs';
import {scriptMetadata,scriptComponents} from '../../../engine/scripting/fields.mjs';
export function mountScriptEditor({document,getState,getSelection,act,run,mutation,open,reveal,getRenderer,reportError}){
 if(!document.defaultView)return {draw(){},choices:()=>[]};
 const q=id=>document.querySelector('#'+id),host=q('script-components');let signature='';
 const editable=()=>!getState().workspaceId;
 const structural=()=>editable()&&!getState().playing;
 const choices=()=>getState().project?projectFiles(getState().project.scene).flatMap(f=>{try{const meta=f.kind==='script'&&scriptMetadata(f);return meta?[{path:f.path,name:meta.className}]:[];}catch{return [];}}):[];
 const edit=(path,action,values)=>act(()=>run('scene.script.edit',mutation({entityId:getSelection(),path,action,...(values?{values}:{})})));
 function draw(){const state=getState(),e=(state.playing?getRenderer()?.interaction?.().scene:state.project?.scene)?.entities.find(e=>e.id===getSelection()),key=JSON.stringify([state.project?.id,state.sceneRevision,state.playing,state.workspaceId,e?.id,e?.scriptComponents?.map(c=>c.path)]);if(key===signature){syncValues(e);return;}if(host.contains(host.ownerDocument.activeElement)&&host.ownerDocument.activeElement?.matches('input,select'))return;signature=key;host.replaceChildren();
  for(const c of scriptComponents(state.project?.scene,e)){const file=projectFiles(state.project.scene).find(f=>f.path===c.path);let meta;try{meta=scriptMetadata(file);}catch{continue;}const card=document.createElement('section');card.className='inspector-property script-property';card.dataset.scriptPath=c.path;const heading=document.createElement('h3');heading.className='property-heading';heading.textContent=meta.className+' (Script)';const close=document.createElement('button');close.type='button';close.className='icon-button property-close';close.innerHTML='<img src="/icons/close.svg" alt="">';close.title='Remove '+meta.className;close.disabled=!structural();close.addEventListener('click',()=>void edit(c.path,'remove').catch(reportError));heading.append(close);card.append(heading);const link=document.createElement('button');link.className='script-source-link';link.textContent=leafName(c.path);link.title=c.path;link.addEventListener('click',()=>open(c.path));card.append(link);
   for(const f of meta.fields){if(f.title){const title=document.createElement('h4');title.textContent=f.title;card.append(title);}const row=document.createElement('label');row.className='script-field';row.dataset.field=f.name;row.style.marginTop=f.space+'px';row.title=f.tooltip??(f.defaultKnown===false?'C# initializer is evaluated at runtime; editing overrides it':'');const name=document.createElement('span');name.textContent=f.name;row.append(name);const value=c.values[f.name]??f.default,inputs=[];function input(v,i){const n=document.createElement('input');n.type=f.type==='bool'?'checkbox':f.type==='string'?'text':'number';if(n.type==='checkbox')n.checked=v;else n.value=String(v);n.disabled=f.readOnly||!editable();if(f.minimum!==undefined)n.min=f.minimum;if(f.maximum!==undefined)n.max=f.maximum;if(n.type==='number')n.step=f.type.endsWith('Int')||['int','uint','byte','short','long','Color32'].includes(f.type)?'1':'any';n.setAttribute('aria-label',f.name+(i===undefined?'':' '+['X','Y','Z','W','Size Y','Size Z'][i]));inputs.push(n);return n;}
    if(f.options){const n=document.createElement('select');for(const o of f.options){const option=document.createElement('option');option.value=o.value;option.textContent=o.name;n.append(option);}n.value=value;n.disabled=f.readOnly||!editable();inputs.push(n);row.append(n);}else if(Array.isArray(value)){const group=document.createElement('div');group.className='vector-inputs';value.forEach((v,i)=>group.append(input(v,i)));row.append(group);}else row.append(input(value));
    if(!Array.isArray(value)&&['byte','short','int','uint','long','float','double'].includes(f.type)){name.dataset.scrub='true';name.classList.add('numeric-label');}row.addEventListener('change',()=>{if(f.readOnly||!editable()||inputs.some(n=>!n.checkValidity()))return;const read=n=>f.type==='bool'?n.checked:f.type==='string'?n.value:Number(n.value),next=Array.isArray(value)?inputs.map(read):read(inputs[0]);void edit(c.path,'values',{[f.name]:next}).catch(reportError);});card.append(row);
   }host.append(card);
  }
 }
 function syncValues(entity){for(const card of host.querySelectorAll('[data-script-path]')){const component=scriptComponents(getState().project?.scene,entity).find(c=>c.path===card.dataset.scriptPath);if(!component)continue;for(const row of card.querySelectorAll('[data-field]')){if(!Object.hasOwn(component.values,row.dataset.field))continue;const inputs=[...row.querySelectorAll('input,select')];if(inputs.some(input=>input.ownerDocument.activeElement===input&&!input.disabled))continue;const value=component.values[row.dataset.field],values=Array.isArray(value)?value:[value];inputs.forEach((input,i)=>{if(input.type==='checkbox')input.checked=!!values[i];else if(input.value!==String(values[i]))input.value=String(values[i]);});}}}
 const inspector=document.querySelector('.inspector');inspector.addEventListener('dragover',event=>{if(!event.dataTransfer.types.includes('application/axiom-files')||!getSelection()||!structural())return;event.preventDefault();inspector.classList.add('drag-target');});inspector.addEventListener('dragleave',event=>{if(!inspector.contains(event.relatedTarget))inspector.classList.remove('drag-target');});inspector.addEventListener('drop',event=>{if(!event.dataTransfer.types.includes('application/axiom-files'))return;event.preventDefault();event.stopPropagation();inspector.classList.remove('drag-target');try{const v=JSON.parse(event.dataTransfer.getData('application/axiom-files'));if(v.projectId!==getState().project.id||v.paths.length!==1||!choices().some(c=>c.path===v.paths[0]))throw Error('Drop one Project MonoBehaviour source on a selected entity');void edit(v.paths[0],'attach').catch(reportError);}catch(error){reportError(error);}});
 const timer=setInterval(()=>{if(getState().playing)draw();},100);timer.unref?.();return {draw,choices,open,reveal};
}
