// Small authored fixtures use the same standard GLB importer as user assets.
export function animationGlb({skinned=true,interpolation='LINEAR'}={}){
 const parts=[],views=[],accessors=[];let length=0;
 function accessor(values,type,componentType=5126){const count=values.length/({SCALAR:1,VEC3:3,VEC4:4,MAT4:16}[type]),size=componentType===5126?4:2,b=Buffer.alloc(values.length*size);values.forEach((v,i)=>componentType===5126?b.writeFloatLE(v,i*size):b.writeUInt16LE(v,i*size));const padded=Buffer.alloc(Math.ceil(b.length/4)*4);b.copy(padded);const view=views.length;views.push({buffer:0,byteOffset:length,byteLength:b.length});parts.push(padded);length+=padded.length;const index=accessors.length;accessors.push({bufferView:view,componentType,count,type});return index;}
 const positions=[],normals=[],joints=[],weights=[];
 const faces=[[0,1,2,0,2,3],[4,6,5,4,7,6],[0,4,5,0,5,1],[3,2,6,3,6,7],[0,3,7,0,7,4],[1,5,6,1,6,2]];
 for(let segment=0;segment<(skinned?3:1);segment++){const y=segment,points=[[-.3,y,-.2],[.3,y,-.2],[.3,y+1,-.2],[-.3,y+1,-.2],[-.3,y,.2],[.3,y,.2],[.3,y+1,.2],[-.3,y+1,.2]];for(const face of faces){const a=points[face[0]],b=points[face[1]],c=points[face[2]],u=b.map((v,i)=>v-a[i]),v=c.map((v,i)=>v-a[i]),n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],len=Math.hypot(...n);for(const i of face){positions.push(...points[i]);normals.push(...n.map(v=>v/len));joints.push(segment,0,0,0);weights.push(1,0,0,0);}}}
 const attributes={POSITION:accessor(positions,'VEC3'),NORMAL:accessor(normals,'VEC3')};if(skinned){attributes.JOINTS_0=accessor(joints,'VEC4',5123);attributes.WEIGHTS_0=accessor(weights,'VEC4');}
 const matrices=[];for(let i=0;i<3;i++)matrices.push(1,0,0,0,0,1,0,0,0,0,1,0,0,-i,0,1);const ibm=skinned?accessor(matrices,'MAT4'):null;
 const time=accessor([0,.5,1,1.5,2],'SCALAR');const quaternion=angle=>[0,0,Math.sin(angle/2),Math.cos(angle/2)];
 function clip(name,angles,node=skinned?2:0){return {name,samplers:[{input:time,output:accessor(angles.flatMap(quaternion),'VEC4'),interpolation}],channels:[{sampler:0,target:{node,path:'rotation'}}]};}
 const animations=[clip('Idle',[0,.12,0,-.12,0]),clip('Wave',[0,1.1,-.6,1.1,0]),{name:'Bounce',samplers:[{input:time,output:accessor([0,0,0,0,.65,0,0,0,0,0,.65,0,0,0,0],'VEC3'),interpolation}],channels:[{sampler:0,target:{node:skinned?1:0,path:'translation'}}]}];
 const nodes=skinned?[{mesh:0,skin:0},{children:[2]},{translation:[0,1,0],children:[3]},{translation:[0,1,0]}]:[{mesh:0}];
 const json={asset:{version:'2.0'},buffers:[{byteLength:length}],bufferViews:views,accessors,meshes:[{primitives:[{attributes,material:0}]}],materials:[{pbrMetallicRoughness:{baseColorFactor:[.12,.75,.85,1],metallicFactor:.15,roughnessFactor:.6}}],nodes,scenes:[{nodes:skinned?[0,1]:[0]}],scene:0,animations,...(skinned?{skins:[{joints:[1,2,3],inverseBindMatrices:ibm}]}:{})};const jsonBytes=Buffer.from(JSON.stringify(json)),padded=Buffer.alloc(Math.ceil(jsonBytes.length/4)*4,32);jsonBytes.copy(padded);const bin=Buffer.concat(parts),out=Buffer.alloc(28+padded.length+bin.length);out.writeUInt32LE(0x46546c67,0);out.writeUInt32LE(2,4);out.writeUInt32LE(out.length,8);out.writeUInt32LE(padded.length,12);out.writeUInt32LE(0x4e4f534a,16);padded.copy(out,20);const offset=20+padded.length;out.writeUInt32LE(bin.length,offset);out.writeUInt32LE(0x004e4942,offset+4);bin.copy(out,offset+8);return out;
}
export const demoAnimator=(initialState='Idle',autoplay=true)=>({initialState,autoplay,speed:1,states:[{name:'Idle',clip:'Idle',loop:true,speed:1},{name:'Wave',clip:'Wave',loop:true,speed:1},{name:'Bounce',clip:'Bounce',loop:false,speed:1}],parameters:[{name:'energy',value:0}],transitions:[{source:'Idle',target:'Wave',parameter:'energy',comparison:'gt',threshold:.5,duration:.6},{source:'Wave',target:'Idle',parameter:'energy',comparison:'lt',threshold:.5,duration:.6},{source:'Bounce',target:'Idle',parameter:'',comparison:'eq',threshold:0,duration:.4}]});
