// Generated by scripts/generate-script-bindings.mjs. Do not edit.
using System.Text.Json;
namespace Axiom.Gameplay;
public readonly record struct Transform(Vec3 Position, Quat Rotation, Vec3 Scale) {
 internal static Transform Read(JsonElement value) => new(Vec3.Read(value.GetProperty("position")), Quat.Read(value.GetProperty("rotation")), Vec3.Read(value.GetProperty("scale")));
}
public readonly record struct RigidBody(Vec3 Velocity) {
 internal static RigidBody Read(JsonElement value) => new(Vec3.Read(value.GetProperty("velocity")));
}
internal static class Limits {
 internal const int Entities = 1024;
 internal const int Attachments = 32;
 internal const int Operations = 128;
 internal const int Spawns = 64;
 internal const int Logs = 32;
 internal const int SourceBytes = 65536;
}
