// Generated by scripts/generate-script-bindings.mjs. Do not edit.
using System.Text.Json;
namespace Axiom.Gameplay;
public readonly record struct Transform(Vector3 Position, Quaternion Rotation, Vector3 Scale) {
 internal static Transform Read(JsonElement value) => new(Vector3.Read(value.GetProperty("position")), Quaternion.Read(value.GetProperty("rotation")), Vector3.Read(value.GetProperty("scale")));
}
public readonly record struct RigidBody(Vector3 Velocity) {
 internal static RigidBody Read(JsonElement value) => new(Vector3.Read(value.GetProperty("velocity")));
}
internal static class Limits {
 internal const int Entities = 1024;
 internal const int Attachments = 32;
 internal const int Operations = 128;
 internal const int Spawns = 64;
 internal const int Logs = 32;
 internal const int SourceBytes = 65536;
}
